### ISSUE TITLE
Disable v2 blocks for mainnet.

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1011]
They're no longer valid, yet some miners produce them. I guess it would be easy for us to validate this rule.

**Comment by schildbach** [comment]
I guess I would add the rule to AbstractBlockChain.connectBlock() and throw a VerificationException if after a certain block height (defined as a network parameter) block version is still below 3. What do you think about that approach?

**Comment by mikehearn** [comment]
Yeah, sounds OK.

**Comment by mikehearn** [comment]
Note that there's no implementation of BIP66 or even the chain-height-in-coinbase rule that triggered v2. I'm still thinking of just removing some of the full verification code paths as nobody cares much to maintain them. If we still have the database code and the script interpreter, that's probably good enough (though, I note that OP_CHECKLOCKTIMEVERIFY is now in Core master).

**Comment by rnicoll** [comment]
Not sure if you still want a block-height lock for when syncing from checkpoint, or are the checks in #1037 enough?

**Comment by schildbach** [comment]
Good question. Theoretically when syncing from a checkpoint nearby the v3 block trigger a node could trick us into a fork because we don't count correctly. However, it's probably too difficult to pull off and it would not pay off. So I'll close this. If anyone sees a serious attack vector, please speak up and I'll reopen.
