### ISSUE TITLE
Bitcoinj 0.11 ignores outputs having multisig address and (therefore) gives wrong indices

### ISSUE THREAD

**Issue by bugtracker123** [bitcoinj/bitcoinj#1082]
**Version:** Bitcoinj-0.11-SNAPSHOT (downloaded sources from official site and compiled). Compiled on Windows 7, 64 bit running 64 bit Java 7. The bug is not present in Bitcoinj-0.12.

**The bug:** when reading a transactions outputs, this version will skip outputs sending to multisig addresses (that is, output scripts of type `OP_HASH160 <some_hash> OP_EQUAL`).

**Details:** Suppose a transaction has following outputs 

     A (ordinary address)
     B (multisig address)
     C (ordinary address)

The outputs interpreted by bitcoinj will be

     A (ordinary address)
     C (ordinary address)

(i.e., it has skipped all outputs with multisig address)
If we use this information to spend the outputs then the indices will be incorrect and the new spending tx will be rejected.

**Test:** To test if your version of bitcoinj contains this bug, do this: 

1. Browse to blockchain.info and view tx with hash [5d575861ba308c1ffd0b9f21861d23674397486291f150d5ed4ed2d5f392f663](https://blockchain.info/tx/5d575861ba308c1ffd0b9f21861d23674397486291f150d5ed4ed2d5f392f663)

2. From the tx, pick any output address after index 12 (the first index with a multisig output address). Let's pick index 65, which is the address `16b2aujEEHGmkPkMaqB1X22LzgmpmkXSzv`.

3. Get the hex of this tx: [5d575861ba308c1ffd0b9f21861d23674397486291f150d5ed4ed2d5f392f663](https://blockchain.info/tx/5d575861ba308c1ffd0b9f21861d23674397486291f150d5ed4ed2d5f392f663?format=hex) and decode to bytes. (We can use the same link as above and prefix `?format=hex` to it)

4. Convert the above bytes to a bitcoinj Transaction using the following code (snippet):
     
        val tx = new Transaction(MainNetParam, hex_bytes) // Scala code

5. Get the outputs and extract the address at index 65 using this code
       
        val out = tx.getOutputs(65)
        val address = out.getScriptPubKey.getToAddress(MainNetParam).toString
        printn (address)

**Result:** If your bitcoinj version does not have a bug, the address printed should be the correct one from blockchain.info (in our case `16b2aujEEHGmkPkMaqB1X22LzgmpmkXSzv`). On the other hand, if it has the bug, it will show a different address (for our example, it will show `13RJvPMzxdAyzXQNnLAAimrMQBGseRJRmC`, incorrectly)

**Comment by mikehearn** [comment]
The current version of bitcoinj is 0.13 - old versions are not supported, so reporting bugs against them which are already fixed isn't especially useful.
