### ISSUE TITLE
Script::executescript fails if Script has OP_0 (null byte)

### ISSUE THREAD

**Issue by bbuenz** [bitcoinj/bitcoinj#1086]
In executescript the code either handles input as an OP_CODE or as data. Since OP_0 is neither it fails with a null pointer exception (chunk.data==null).
This makes it impossible to run multisig scripts.

     if (!chunk.isOpCode()) {
                if (chunk.data.length > MAX_SCRIPT_ELEMENT_SIZE)
                    throw new ScriptException("Attempted to push a data string larger than 520 bytes");
                
                if (!shouldExecute)
                    continue;
                
                stack.add(chunk.data);
            } else {

**Comment by mikehearn** [comment]
Multisig scripts are unit tested, so it's not impossible to run them. But the handling of OP_0 is ridiculous in both bitcoinj and the original code. I remember it changed recently, I think @schildbach tweaked it? I can't recall. We're probably not identical to the original C++ anymore.

**Comment by schildbach** [comment]
I think this is fixed by https://github.com/bitcoinj/bitcoinj/pull/1115, which I just merged. Can you confirm the fix works for you?

**Comment by schildbach** [comment]
Fixed.
