### ISSUE TITLE
Commit d3d11df for BIP34 has issue on Block 224430 

### ISSUE THREAD

**Issue by n1bor** [bitcoinj/bitcoinj#1097]
Issue is that the coinbase has a load of junk after the height.
https://blockchain.info/tx/e55cf5e0442aadf707d122282a26a134b145c3ce240a4a621d3f596ea140c6cc

So Transaction.java can not parse script and so throws ValidationException.

Infact script does not NEED to be valid just needs to have height set correctly.

**Comment by rnicoll** [comment]
Now #1101 has been applied, can you confirm you're happy this is fixed and can be closed, please?

**Comment by schildbach** [comment]
Assuming this is fixed on master.
