### ISSUE TITLE
j2objc could be used to transpile bicoinj to Objective-C

### ISSUE THREAD

**Issue by metteo** [bitcoinj/bitcoinj#1103]
See https://github.com/google/j2objc

**Comment by schildbach** [comment]
Thanks for your suggestion, but keeping this as an open issue doesn't make much sense. If you want to see this happen, either start a call for help on the mailing list or implement it yourself and submit a PR.

**Comment by metteo** [comment]
Transpilation using j2objc works on any platform, but to compile the sources Objective-C toolchain is required which is only available on Mac with XCode and I don't have it. I added the issue because some projects on gihub have 'feature' label for issues which contain development suggestions.
