### ISSUE TITLE
Should validate block headers to detect IsSuperMajority() softforks, e.g. BIP65/CLTV

### ISSUE THREAD

**Issue by petertodd** [bitcoinj/bitcoinj#1114]
See https://github.com/bitcoin/bips/blob/master/bip-0065.mediawiki#SPV_Clients

**Comment by schildbach** [comment]
Can you check https://github.com/bitcoinj/bitcoinj/pull/1111 ?

**Comment by petertodd** [comment]
Done: https://github.com/bitcoinj/bitcoinj/pull/1111#issuecomment-157226720

**Comment by schildbach** [comment]
Fixed via #1111.
