### ISSUE TITLE
How to use PostgresFullPrunedBlockStore with bitcoinj-core-0.13-bundled.jar

### ISSUE THREAD

**Issue by shivamg705** [bitcoinj/bitcoinj#1139]
i am getting following error while using PostgresFullPrunedBlockStore with bitcoinj-core-0.13-bundled.jar.It is working fine with bitcoinj-core-0.12.2.jar and bitcoinj-tools-0.12.2.jar.Can anybody tell me what should i do to handle this error?

| Error 2015-12-17 15:32:54,712 [localhost-startStop-1] ERROR context.GrailsContextLoaderListener  - Error initializing the application: org.bitcoinj.core.Sha256Hash.wrap([B)Lorg/bitcoinj/core/Sha256Hash;
Message: org.bitcoinj.core.Sha256Hash.wrap([B)Lorg/bitcoinj/core/Sha256Hash;
    Line | Method
->>  590 | initFromDatabase                 in org.bitcoinj.store.DatabaseFullPrunedBlockStore
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    189 | <init>                           in     ''
|    104 | <init> . . . . . . . . . . . . . in org.bitcoinj.store.PostgresFullPrunedBlockStorett
|     29 | get                              in com.dcx.wallet.BlockChainProvider
|     28 | <clinit> . . . . . . . . . . . . in com.dcx.wallet.WalletRefreshService
|    190 | forName                          in java.lang.Class
|     71 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    262 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1145 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run                              in java.lang.Thread

**Comment by schildbach** [comment]
Can you ask questions on the mailing list please? The latest stable release is 0.13.3. Can you test that version, and maybe also the master branch (0.14-SNAPSHOT)?
