### ISSUE TITLE
Does Bitcoinj have a JSON-RPC API?

### ISSUE THREAD

**Issue by pobri19** [bitcoinj/bitcoinj#1176]
I want to interface with Bitcoinj using Go, and since Go can't use Java in the same way that things like Jython can, I'll need to do so through a JSON RPC API. Does Bitcoinj have this already?

**Comment by msgilligan** [comment]
You can look at [bitcoinj-addons](https://github.com/msgilligan/bitcoinj-addons) for a nearly complete JSON-RPC client and a very limited JSON-RPC server.

This issue should probably be closed as a duplicate of Issue #895.
