### ISSUE TITLE
Cost of open/close micropayment channels?

### ISSUE THREAD

**Issue by pobri19** [bitcoinj/bitcoinj#1193]
21.co have been bragging on Reddit about their micropayment channel solution, but it comes with a huge caveat: The cost to open and close a channel is around 10cents USD. This makes it infeasible for most applications that rely on these types of payments. My question is, does BitcoinJ suffer from the same, or a similar, limitation? What are the costs associated with open/close of a BitcoinJ micropayment channel? Thanks.

**Comment by schildbach** [comment]
Can you ask questions on the mailing list please?
