### ISSUE TITLE
Sha256Hash.compareTo() is broken

### ISSUE THREAD

**Issue by tbocek** [bitcoinj/bitcoinj#1213]
Sha256 has the following compareTo()

```
@Override
public int compareTo(Sha256Hash o) {
  return this.hashCode() - o.hashCode();
}
```

This may not always work, as hashCode only uses the last 4 bytes, where equals() uses the complete byte array. So compareTo() may return 0 in the following cases and equal returns false:
```
[..., 1, 2, 3, 4, 5]
[..., 9, 2, 3, 4, 5]
```

**Comment by schildbach** [comment]
Right, good catch, although this behavious is documented in a comment in the quoted method.

What do you think of [this fix](https://github.com/bitcoinj/bitcoinj/pull/1214)?

**Comment by tbocek** [comment]
Just a minor detail: I would mask the byte with 0xff. This makes it more readable when outputting a sorted list of Sha256 hashes. Otherwise its fine.

```
if ((bytes[i] & 0xff) > (o.bytes[i] & 0xff))
```

**Comment by schildbach** [comment]
Ok, I added the "& 0xff" and merged.

**Comment by tbocek** [comment]
thx!
