### ISSUE TITLE
Payment channel docs don't render properly anymore

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#1218]
https://bitcoinj.github.io/working-with-micropayments

Somehow markup is not being converted to HTML properly.

**Comment by schildbach** [comment]
Thanks! There was a change in the supported markdown by GitHub recently (switch to Jekyll 3.0 or something?).

**Comment by schildbach** [comment]
Fixed by 7ca7db001355841fae3a6126162bdafa818d2d50.
