### ISSUE TITLE
Endianness mix-up in sequence check for OptInRBF

### ISSUE THREAD

**Issue by Xekyo** [bitcoinj/bitcoinj#1225]
The transaction sequence numbers appear to be [Unsigned Little Endian](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-January/012268.html), but Java naturally uses [Signed Big Endian](http://stackoverflow.com/questions/362384/are-integers-in-java-little-endian-or-big-endian).

This appears to cause `nLockTime` transactions that have a sequence number of `0xFEFFFFFF` to be falsely recognized as "OptInRBF", because [TransactionInput.java](https://github.com/bitcoinj/bitcoinj/blob/becd8641c92817e85029ddd63d1f424cdd626278/core/src/main/java/org/bitcoinj/core/TransactionInput.java#L385) compares the sequence `sequence < NO_SEQUENCE - 1;` where `NO_SEQUENCE` is `0xFFFFFFFF`.

This may be occurring somewhat often, as all transactions created by Bitcoin Core 0.12.0 are `nLockTime` transactions.

**Comment by instagibbs** [comment]
This appears to be the offending line: https://github.com/bitcoinj/bitcoinj/blob/becd8641c92817e85029ddd63d1f424cdd626278/core/src/main/java/org/bitcoinj/core/TransactionInput.java#L139

**Comment by Xekyo** [comment]
Created a pull-request here: https://github.com/bitcoinj/bitcoinj/pull/1226

**Comment by schildbach** [comment]
Fixed via 5aa4b66c7ed07275a0c396d2acee46f5b943a176. The issue was not an endianess mix-up, but rather a bad serialization to protobuf with large sequence numbers.

**Comment by instagibbs** [comment]
Glad to hear this was not all for naught!
