### ISSUE TITLE
Wallet file serialization rework

### ISSUE THREAD

**Issue by jdojff** [bitcoinj/bitcoinj#1237]
# Motivation
Despite the fact what Bitcoinj is designed for small wallets, but it performs with large wallets (200MB+) as good. However, there is only one issue needed to be solved. Current wallet file serialization logic has several issues regarding storing large wallets:

- Hard size limit, currently 512MB (#366)
- IO load - having wallet i.e. 500MB size would generate extreme disk load even with some saving optimizations. I.e. saving wallet each minute would generate constant 10MB/s disk load.

# Solutions
There may be several different solutions to solve this issue. @mikehearn, @schildbach, maybe do you have a vision for this library to solve the issue? Or even implementation on the way? In any case it would be good to know this for possible design and pull requests.

## Fragmentation
Saving wallet information in multiple files:

- Increase risk of inconsistency
- Reduce of disk IO load dramatically since data fragmentation would be chosen by its type and count. Wallet headers - one file, watch addresses - another file, transactions - multiple files (one until size limit is reached), etc.
- Moderately difficult to implement

## Database
Saving wallet information to the database:

- Additional data store requirement
- May require additional structures for storing wallet summary information for quick wallet read, to reduce read wallet latency and disk load. As well as, maybe, asynchronous wallet integrity validation.
- Reduce of disk IO load dramatically
- Instant update write
- Complex to implement

**Comment by schildbach** [comment]
I just responded to the bitcoinj mailing list. It's a better place to discuss design.
