### ISSUE TITLE
Strange zxing dependency issue (3.2.1)

### ISSUE THREAD

**Issue by admazzola** [bitcoinj/bitcoinj#1247]
2111 [main] INFO org.bitcoinj.crypto.MnemonicCode - PBKDF2 took 906ms
2216 [main] INFO org.bitcoinj.wallet.KeyChainGroup - Creating and activating a new HD chain: org.bitcoinj.wallet.DeterministicKeyChain@5ce6d453
2263 [main] INFO org.bitcoinj.wallet.DeterministicKeyChain - 1 keys needed for M/0H/0 = 1 issued + 0 lookahead size + 0 lookahead threshold - 0 num children
2273 [main] INFO org.bitcoinj.wallet.DeterministicKeyChain - Took 8 msec
2294 [main] INFO org.bitcoinj.wallet.DeterministicKeyChain - 1 keys needed for M/0H/0 = 2 issued + 0 lookahead size + 0 lookahead threshold - 1 num children
2300 [main] INFO org.bitcoinj.wallet.DeterministicKeyChain - Took 5 msec
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/client/j2se/MatrixToImageWriter

**Comment by schildbach** [comment]
What branch or commit are you on? What exactly are you trying to do? The only subproject that depends on zxing is wallet-template – bitcoinj core should not depend on it.

**Comment by admazzola** [comment]
Woops you are right, a different library was responsible!
