### ISSUE TITLE
release 0.14 depends on orchid 1.2 which depends on 0.14-snapshot it can't find

### ISSUE THREAD

**Issue by greenaddress** [bitcoinj/bitcoinj#1255]
pom file https://jcenter.bintray.com/org/bitcoinj/orchid/1.2/orchid-1.2.pom

depends on org.bitcoinj:bitcoinj-parent:0.14-SNAPSHOT

Apologises if this is a mistake, I double checked but I may be missing something.

thanks!

**Comment by schildbach** [comment]
Darn! These artifact repositories really do a bad job at consistency checking! That bad pom.xml must have been uploaded a year ago.

Can you use "mvn install" on the v0.14 tag as a workaround?

**Comment by greenaddress** [comment]
At the moment i'm building from src as a workaround, no probs, but i thought it may impact others that try to use it

**Comment by schildbach** [comment]
Yes, I'm preparing a v0.14.1.

**Comment by greenaddress** [comment]
sweet! thank you for the super fast response!

**Comment by schildbach** [comment]
Seems as if 0.14.1 is already on Maven Central. Can you try if it works for you (without compiling from source)?

**Comment by greenaddress** [comment]
Just tried, and from the Gradle console I see:

Download https://jcenter.bintray.com/org/bitcoinj/bitcoinj-core/0.14.1/bitcoinj-core-0.14.1.pom
Download https://jcenter.bintray.com/org/bitcoinj/bitcoinj-parent/0.14.1/bitcoinj-parent-0.14.1.pom
Download https://jcenter.bintray.com/org/bitcoinj/orchid/1.2.1/orchid-1.2.1.pom
Download https://jcenter.bintray.com/org/bitcoinj/orchid/1.2.1/orchid-1.2.1.jar
Download https://jcenter.bintray.com/org/bitcoinj/bitcoinj-core/0.14.1/bitcoinj-core-0.14.1.jar

And orchid-1.2.1 correctly depends on 0.14.1, LGTM

**Comment by schildbach** [comment]
Thanks!
