### ISSUE TITLE
java.nio.CancelledKeyException new in 0.14

### ISSUE THREAD

**Issue by stefanwouldgo** [bitcoinj/bitcoinj#1258]
there is a new exception in 0.14 when our bitcoind peer dies that doesn't seem to occur in 0.13.6:

[error] [PeerGroup Thread] WARN org.bitcoinj.core.PeerGroup - Chain download stalled: received 1.25 KB/sec for 10 seconds, require average of 1.56 KB/sec, disconnecting [127.0.0.1]:8333   [196/352]
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:8333: Peer died      (1 connected, 0 pending, 2 max)
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Download peer died. Picking a new one.
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Unsetting download peer: [127.0.0.1]:8333
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Setting download peer: [85.25.200.172]:8333
[error] [PeerGroup Thread] INFO org.bitcoinj.core.listeners.DownloadProgressTracker - Chain download switched to [85.25.200.172]:8333
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Peer discovery took 25.62 μs and returned 0 items
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1501 msec before next connect attempt to [127.0.0.1]:8333
[error] [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [127.0.0.1]:8333     (1 connected, 1 pending, 2 max)
[error] [NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to /127.0.0.1:8333
[error] [NioClientManager] INFO org.bitcoinj.core.Peer - Announcing to /127.0.0.1:8333 as: /bitcoinj:0.14/
[error] [NioClientManager] INFO org.bitcoinj.core.Peer - [127.0.0.1]:8333: Got version=70012, subVer='/Satoshi:0.12.0/', services=0x5, time=2016-05-12 18:40:11, blocks=411463
[error] [NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:8333: New peer      (2 connected, 0 pending, 2 max)
[error] [main] INFO org.bitcoinj.core.Peer - Request to fetch block 0000000000000000017345af3d6cbc5beb136ffafcd18f02663ee9898c71523f
[error] [main] WARN org.bitcoinj.net.ConnectionHandler - Error writing message to connection, closing connection
[error] java.nio.channels.CancelledKeyException
[error]         at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
[error]         at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
[error]         at org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:106)
[error]         at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:152)
[error]         at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:90)
[error]         at org.bitcoinj.core.Peer.sendSingleGetData(Peer.java:1320)
[error]         at org.bitcoinj.core.Peer.getBlock(Peer.java:1293)
[error]         at core.PeerSource$$anonfun$blockSource$4.apply(PeerSource.scala:17)
[error]         at core.PeerSource$$anonfun$blockSource$4.apply(PeerSource.scala:16)
[error]         at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
[error]         at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:462)
[error]         at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
[info] Waiting for node to send us the requested block: 0000000000000000017345af3d6cbc5beb136ffafcd18f02663ee9898c71523f at Thu May 12 18:40:11 CEST 2016
[error]         at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:461)
[error]         at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error]         at core.BlockReader$class.process(BlockReader.scala:47)
[error]         at actions.ResumeBlockReader.process(ResumeBlockReader.scala:9)
[error]         at core.BlockReader$$anonfun$1.apply(BlockReader.scala:37)
[error]         at core.BlockReader$$anonfun$1.apply(BlockReader.scala:28)
[error]         at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:34)
[error]         at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
[error]         at core.BlockReader$class.$init$(BlockReader.scala:28)
[error]         at actions.ResumeBlockReader.<init>(ResumeBlockReader.scala:9)
[error]         at Explorer$.resume(Explorer.scala:107)
[error]         at Explorer$.iterateResume(Explorer.scala:146)
[error]         at Explorer$.delayedEndpoint$Explorer$1(Explorer.scala:34)
[error]         at Explorer$delayedInit$body.apply(Explorer.scala:13)
[error]         at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]         at scala.App$$anonfun$main$1.apply(App.scala:76)
[error]         at scala.collection.immutable.List.foreach(List.scala:381)
[error]         at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error]         at scala.App$class.main(App.scala:76)
...

**Comment by schildbach** [comment]
I'm pretty sure that happens on 0.13.6 as well. Yes, it indicates a broken connection. An exception is needed in this case to close down the Peer.

**Comment by KameJu** [comment]
Can I somehow handle this error so that it doesn’t write it to me in the console?
