### ISSUE TITLE
H2FullPrunedBlockStore constructor creates file with incorrect path

### ISSUE THREAD

**Issue by dcw312** [bitcoinj/bitcoinj#1260]
The following constructor:
H2FullPrunedBlockStore(NetworkParameters params, String dbName, int fullStoreDepth, int cacheSize)

... will prepend "jdbc:h2:" twice to while creating the connection URL.

I will prepare a pull request.

Steps to reproduce:
1. Call the constructor in an new Unit Test with dbName = "/tmp/foo.h2"

Expected Result: new file with absolute path /tmp/foo.h2
Actual Result: new file in current directory with name "jdbc:h2"

**Comment by schildbach** [comment]
Fixed.
