### ISSUE TITLE
H2FullPrunedBlockstore constructor bug

### ISSUE THREAD

**Issue by Frederic-R** [bitcoinj/bitcoinj#1263]
public H2FullPrunedBlockStore(NetworkParameters params, String dbName, String username, String password,
            int fullStoreDepth) throws BlockStoreException {
        super(params, DATABASE_CONNECTION_URL_PREFIX + dbName + ";create=true;LOCK_TIMEOUT=60000;DB_CLOSE_ON_EXIT=FALSE", fullStoreDepth, username, password, null);
    }
    public H2FullPrunedBlockStore(NetworkParameters params, String dbName, int fullStoreDepth)
            throws BlockStoreException {
        this(params, DATABASE_CONNECTION_URL_PREFIX + dbName + ";create=true;LOCK_TIMEOUT=60000;DB_CLOSE_ON_EXIT=FALSE", null, null, fullStoreDepth);
    }
As the second constructor calls 'this(...)', the DATABASE_CONNECTION_URL_PREFIX is added twice and cause the database to be created/opened in a wrong directory.

**Comment by schildbach** [comment]
What commit are you on? We fixed this already.

**Comment by Frederic-R** [comment]
Oups! I looked at the decompiled result of the 0.14.1 binary distribution but did not pull the last sources. I'm sorry for the disturbance ...

**Comment by schildbach** [comment]
No worries…
