### ISSUE TITLE
Java class to read bitcoin.conf

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1265]
Is there anything in **bitcoinj** that can read a `bitcoin.conf` text configuration file? (I used "search repo" and didn't find anything)
I'm about to write some code (as part of my JSON-RPC client) to do it. I'm willing to contribute the code and/or the JSON-RPC  client.

But if there is already something please let me know...

**Comment by schildbach** [comment]
No. What would this be good for?

Can you ask questions on the mailing list?

**Comment by msgilligan** [comment]
Sorry, sure.
