### ISSUE TITLE
port used for tests clashes with CrashPlan service daemon on OSX

### ISSUE THREAD

**Issue by thinkberg** [bitcoinj/bitcoinj#1269]
It would be a good idea to test on ports somewhere in the upper area of > 10000 to avoid clashing with services. Port 4243 is used by crashplan and some other service out there.

**Comment by dcw312** [comment]
Maven has a plug in to reserve a free port and pass as a system parameter. Maybe we should use that?

**Comment by schildbach** [comment]
I'd rather not add another dependency to Maven. It will complicate the switch to Gradle.

Have you tried building with the -Pno-network profile? Travis is configured like that and I haven't seen any port clashes since then.
