### ISSUE TITLE
org.bitcoinj.core.InsufficientMoneyException: Insufficient money

### ISSUE THREAD

**Issue by WhiteTrashLord** [bitcoinj/bitcoinj#1277]
My code looks like this:

        kit = new WalletAppKit(params, new File("."), filePrefix);  
        kit.startAsync();
        kit.awaitRunning();      
                
        try {
            
           Coin amountToSend = kit.wallet().getBalance().subtract(Transaction.REFERENCE_DEFAULT_MIN_TX_FEE);  
           kit.wallet().sendCoins(kit.peerGroup(), forwardingAddress, amountToSend);            

        } catch (KeyCrypterException | InsufficientMoneyException e)
        {
           e.printStackTrace();
        }

But I get this exception:
org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.0018345 BTC

What could be the problem? It's possible that my wallet contains some invalid / unconfirmed Bitcoins?

**Comment by oscarguindzberg** [comment]
First guess is fees are not enough.
I would try



       Coin amountToSend =
kit.wallet().getBalance().subtract(Transaction.REFERENCE_DEFAULT_MIN_TX_FEE.add(Coin.valueOf(183450)));


On Thu, Jun 30, 2016 at 1:30 AM, WhiteTrashLord <notifications@github.com>
wrote:

> My code looks like this:
>
>     kit = new WalletAppKit(params, new File("."), filePrefix);
>     kit.startAsync();
>     kit.awaitRunning();
>
>     try {
>
>        Coin amountToSend = kit.wallet().getBalance().subtract(Transaction.REFERENCE_DEFAULT_MIN_TX_FEE);
>        kit.wallet().sendCoins(kit.peerGroup(), forwardingAddress, amountToSend);
>
>     } catch (KeyCrypterException | InsufficientMoneyException e)
>     {
>        e.printStackTrace();
>     }
>
> But I get this exception:
> org.bitcoinj.core.InsufficientMoneyException: Insufficient money, missing
> 0.0018345 BTC
>
> What could be the problem? It's possible that my wallet contains some
> invalid / unconfirmed Bitcoins?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/bitcoinj/bitcoinj/issues/1277>, or mute the thread
> <https://github.com/notifications/unsubscribe/ABF5LDxBweQdGXkz6QqtdFJ0-fG02_vSks5qQ0ZPgaJpZM4JByqC>
> .
>



-- 
Oscar Guindzberg
