### ISSUE TITLE
How to get the master private key from a Wallet object?

### ISSUE THREAD

**Issue by YvonFortier** [bitcoinj/bitcoinj#1300]
Hi people.
I'm trying to dump the master private key from MultibitHD to monitor from other wallet, but I can't get it right.
What I do is restore a wallet and then try to get the private key from the Wallet object:

[code]NetworkParameters PARAMS = MainNetParams.get();
DeterministicKeyChain kc = wallet.getActiveKeychain();
DeterministicKey rk = kc.getRootKey();
String key = rk.getPrivateKeyAsWiF(PARAMS);[/code]

I'm getting an exception saying [b]java.lang.IllegalStateException: Private key bytes not available [/b]

Any help would be greatly appreciated.

Alternatively, if someone knows how to properly derive the master key from the seed using a third party tool, that'd help!

**Comment by schildbach** [comment]
Please ask support questions on the mailing list. If you ask there, please also state your bitcoinj version and if the wallet is perhaps encrypted.

**Comment by YvonFortier** [comment]
Will do, sorry for the mistake!
