### ISSUE TITLE
Pretty bad bug with creating transactions

### ISSUE THREAD

**Issue by jerrymg** [bitcoinj/bitcoinj#1302]
I believe I've found a pretty bad bug with creating transactions. I will get the error below when I use Bitcoin Core's bitcoin-cli to send the raw transaction. 

```
error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
```

Here is how I create the transaction.

```
        NetworkParameters params =  MainNetParams.get();
        Transaction tx = new Transaction(params);

        tx.addOutput(Coin.valueOf(9999000), Address.fromBase58(params, "1FPT9GEeYeWtDZkZDFc8X84TMWurKrLqBw"));
        tx.addOutput(Coin.valueOf(10000000), Address.fromBase58(params, "1Csfi6vRixj4gfgg6RA5XUGNFM65umSnLX"));

        ECKey key1 = DumpedPrivateKey.fromBase58(params, "key1").getKey();
        Script script1 = new Script(HEX.decode("76a9143fe4203489dfe788ef0addc69388f9475ea3375088ac"));
        String hash1 = "11d5d7d302f0e42d226cd4ebd1d07a10bfc70178a49378e87b34605179f885b9";
        tx.addSignedInput(new TransactionOutPoint(params, 2, Sha256Hash.wrap(hash1)), script1, key1);

        ECKey key2 = DumpedPrivateKey.fromBase58(params, "key2").getKey();
        Script script2 = new Script(HEX.decode("76a9147d27f5939cd361a72702b02dc9fa6624968cc15988ac"));
        String hash2 = "360ceaa4e45d2480e2c5a906c13768d95e6637741e453a21245ceab65cfbf871";
        tx.addSignedInput(new TransactionOutPoint(params, 2, Sha256Hash.wrap(hash2)), script2, key2);
        String txHex = HEX.encode(tx.bitcoinSerialize());
```

Here is the result of `txHex`. You can still try to broadcast the transaction if you want.
`0100000002b985f8795160347be87893a47801c7bf107ad0d1ebd46c222de4f002d3d7d511020000006b483045022100fbf11bb0eac7f640a8c28a7a88438ef8c799e665e7e87e5c8b61cf85a3126e1e022016c5c2b2dcf38e620983dd2fc3c952d2a11698fd9596e656a795609504ad367a0121037f473ce56001b7f20fe2b326196b774316d109163fa36a817c558fe0e16e3370ffffffff71f8fb5cb6ea5c24213a451e7437665ed96837c106a9c5e280245de4a4ea0c36020000006b483045022100afc7fb41feb382cf05c95cbc14005d31782fc724885770b99329da00c91cfce0022029c2a130a2e29237325f51d64e398cb37fd6bf524768e86ff9449d9501ee825f0121039975ef4f64dc31c0f33fcdb339115c7d96ccf9a8223a8fec38200862add6fd5affffffff0298929800000000001976a9149dd0bc1927d4a65ebff0d0568aea36a22502dd1688ac80969800000000001976a914823e7e7b65b116acb6deb4ed54d8c04603c0644a88ac00000000`

**Comment by schildbach** [comment]
Is there a reason you are not using SendRequest? What versions of bitcoinj and Bitcoin Core are you using for the test?

**Comment by schildbach** [comment]
Also, you're signing the inputs with an apparently dummy key. I would expect such transaction to not verify.

**Comment by jerrymg** [comment]
My use case is actually using bitcoinj to create a transaction and broadcast it through a blockexplorer API in blockchain.info. I saw that the api returned an error and I tried to send it through Bitcoin Core and I found that it was Bitcoin Core that was rejecting the transaction. I'm on bitcoinj version 0.14.3, and Bitcoin Core version 0.12.1.

As for the dummy key,  I just put "key1" and "key2" as a dummy key because those keys actually hold real bitcoins so I don't want to include it in my post. In my actual code I do create the transaction with the real base58 private key.

**Comment by jerrymg** [comment]
I can however send the real private keys for you to see the issue on your end if you want, like in a email or something. I don't mind since you are a trusted member of the Bitcoin community.

**Comment by schildbach** [comment]
Can you run Bitcoin Core with the debug log enabled and then paste the last couple of lines preceding the error to here? It may list the exact reason.

**Comment by jerrymg** [comment]
It looks like the only error I get is this
```
error code: -26
error message:
16: mandatory-script-verify-flag-failed (Script evaluated without error but finished with a false/empty top stack element)
```

There nothing about my attempt to send the tx in the debug.log file either.

**Comment by jerrymg** [comment]
So here are some more transactions that I create where I get the same error on Bitcoin Core. It looks like the issue always occur if I have 2 inputs or more in my transaction.


`0100000002b985f8795160347be87893a47801c7bf107ad0d1ebd46c222de4f002d3d7d511020000006b4830450221008831a735a9b14c1d0b8f532237ba0832b8f829c6aa2634b48c359dcc78b45cb402200ba4fc6ed07ed970276b749fad7d5aeb7a8f80982fc2455465ca7b9c71e8a1210121037f473ce56001b7f20fe2b326196b774316d109163fa36a817c558fe0e16e3370ffffffff71f8fb5cb6ea5c24213a451e7437665ed96837c106a9c5e280245de4a4ea0c36020000006b483045022100c9ca77c70337b3cbc42c6f2d8940682e7becb756f214285904d41038a01127d402201c517a27944999d9a22d6cc8e8845af86bcd4c098a81fc8885cf57e72fa50bfb0121039975ef4f64dc31c0f33fcdb339115c7d96ccf9a8223a8fec38200862add6fd5affffffff02706f9800000000001976a9149dd0bc1927d4a65ebff0d0568aea36a22502dd1688ac80969800000000001976a914823e7e7b65b116acb6deb4ed54d8c04603c0644a88ac00000000`


`01000000032d43075565168481e85082c26c8696436b3aede54275a749dfdb5cd188eeb70c000000006a47304402207a46a4f5f42d7f483ea76443f468f4fdfd718a56a88f8949c04b796e1d0a2005022023a576a1427c5be6b0bbe85dd01b5086a113854c70943f4c85fb32cd06824fca012103d209742d8e10ff3cbe4eaf2f70d2c7d6ab7596ade30017858894a748b72ae8d1ffffffff5a4a95eec7738b6f1174485d2f4d85d36434eac14316bc2a02aeda013aaa6922010000006b483045022100ad4dc435fccad41f2befcbb935ff5bba03451bf92a6386445beddc62c4717c8d02207255281d81a5f13ddb222f0dfa1b10aa2b03643b47de8c5200014129aed1a82401210378ba5f0053311e20beb00536117f76a8dc88188d061d2cd1e1029123f177a747ffffffff58390de3c26ed32bd46e344c79e9121f7f2a03a144f042f9cb6ffc0f67dacfed010000006b483045022100e894fe1d231f8b6e4cd6635b7ca231466aee705318e852af4bf14a24ca8e143d0220677837d6aaf68d4fab4dc5f1b93a7c41c36ff227a73f27ef68894e57eb4c299f012103e605bfcd7d7e990419b894bbc4badbd346c06a4f10af2cd5a0712d90a51d14feffffffff01cc06bd01000000001976a914edbbd098ab2117b960448d5befa3b0d464e0b7cf88ac00000000`

**Comment by jerrymg** [comment]
Is there any way this can be prioritized? I wish I could solved this issue myself, but I'm not an expert on signatures. I willing to put like a .5 btc bounty on this.

**Comment by hpbock** [comment]
This is not a bug in bitcoinj. What you do is creating a transaction with two outputs including a transaction fee, which is perfectly ok. Then you add one input to the transaction and directly sign the transaction with the private key of that input. This is still valid.

The issue is, that after signing the transaction, you modify the transaction by adding a second input to it, which renders the first input signature invalid.

You will need to initiate the transaction first with all inputs (Transaction.addInput()) and outputs without signing it in between. After you have created the complete transaction, you can add the signatures without changing the transaction itself. Unfortunately I can not yet tell you how this can be implemented. I guess it can somehow be done using Transaction.calculateSignature().

What bitcoinj could think about, is throwing an exception, if someone tries to modify an already signed transaction.

So sorry for not having a pull request for you. If you though think this comment is helpful i would appreciate a donation to 1CgVBkf49SZcxhpxyYgEeUGHLTG131bU2W very much.

**Comment by hpbock** [comment]
Thank you very much! :)
