### ISSUE TITLE
Segwit addresses can be 32-bytes long

### ISSUE THREAD

**Issue by xenog** [bitcoinj/bitcoinj#1312]
I have been working on segwit addresses on my fork of this code. I noticed that the `Address` class has a static property `LENGTH` that is set to 20. In order to work properly with segwit, the `LENGTH` property has to be set individually per address instance, or not at all. I for now left it at 20 and marked it `@Deprecated`. I would like to know if the property should instead be removed, even if it breaks backwards compatibility. My code is [here](https://github.com/xenog/bitcoinj/tree/segwit).

**Comment by schildbach** [comment]
Thanks! I have replied to this on the bitcoinj mailing list: https://groups.google.com/d/msg/bitcoinj/BC6ZqSiJyDE/hhw2zB0fCQAJ

**Comment by schildbach** [comment]
FWIW, there are two open PR for implementing (concepts for) native segwit addresses: #1515 #1516
