### ISSUE TITLE
Fee calculation very incorrect

### ISSUE THREAD

**Issue by ar-** [bitcoinj/bitcoinj#1320]
I'm using the latest release version. I'm running the example ForwardingService.java. As is now it does not work (for new/empty) wallets and requires fixing. That also came up in #1277 , which was quickly closed with a pretty lame excuse.

I fixed it by catching the "InsufficienMoney' Exception, reducing the amount that is missing and try it again (until it works). Source code is attached. The shocking output I'm getting is:

> Transaction will be forwarded after it confirms.
> Forwarding 0.001 BTC
> trying to send 0.001 BTC
> missing 0.00005 BTC
> trying to send 0.00095 BTC
> missing 0.0000465 BTC
> trying to send 0.0009035 BTC
> missing 0.000017 BTC
> trying to send 0.0008865 BTC
> Sending ...
> Sent coins onwards! Transaction hash is ae0e241a73fc65d461a4976ebf8d2812e14333f4ae8abe0c33d4cd74d1718093
> 

This runs without exception now. But is obviously very wrong. I'm reducing the missing amount from the original transaction and expect it to go through the second time. But it comes up again and tells me that almost the same amount is again missing (0.0000465 instead of 0.0005). So I'm reducing again. **This has has almost doubled my fee**.

After 4 Retries - always trusting the missing value in the exception, the transaction goes through. But I could only send 0.0008865 of my original 0.001 BTC. Which is just 88%.

Also the original expected fee of 5% (!!) seems quite high to me.

Despite of these flaws you are indication that this lib is used in productive environments like Android Wallets. I'm thinking that not-working examples should be removed from the code base, as they are mostly ran by noobs (like me) who try to understand the system.

[ForwardingService.java.zip](https://github.com/bitcoinj/bitcoinj/files/614220/ForwardingService.java.zip)

**Comment by schildbach** [comment]
So what you're saying is that the ForwardingService example is broken, rather than the fee calculation is incorrect? (Fee calculation works very well in the production wallets.)

ForwardingService should probably be fixed by using the "empty wallet" feature.

**Comment by ar-** [comment]
No, I'm saying both: Fee calculation is broken (see above), which makes the example "not-running". I was thinking of the "empty wallet" feature too - it is actually bad design that it exists at all. But that doesn't solve the problem.

I think a "forwarding service" should work either way. No matter if wallet empty, or almost empty, or not empty at all. You suggested solution would make it an "WalletTruncateService".

A cool thing would actually be, if the API would allow the user to decide, how much fee to send, but as far as I see, that option is pretty much impossible by desgin. Instead it implements a weird don'-'worry-I'm-always-right-and-add-the-"correct"-fee-for-you-and-you-can't-change-it-function.

When I search for existing issues about this I also found that existing issues (like #945 ) are just untagged, so can safely be ignored.

Could you at least be so kind and put a huge announcement on the landing page stating "THIS LIBRARY MUST NOT BE USED IN ANY PRODUCTION ENVIRONMENT AS IT HAS SEVERE BUGS". That would save people some time and trouble.

**Comment by schildbach** [comment]
I fail to see the bug in the library. You can specifiy an arbitrary fee rate and the library calculates the absolute fee. The library optionally makes sure the fee is at least the min relay fee. The library doesn't make any assumptions or guarantees about "being right" (in terms of the fee market) at all, that's up to the library user.

I agree that the example is broken. Pull request welcome.

**Comment by ar-** [comment]
Sorry, I think. I described the error in a wrong way. I'll give it another try. I'm reporting an error in the fee calculation. There is an InsufficientMoneyException being thrown containing the amount of missing money. The exception is thrown in wrong cases, has wrongful details and it strongly suggests that there is a severe error in the fee calculation. This is all core functionality - not example.

Here is how to reproduce:

- make a new wallet in the testent
- send 0.001 BTC to it
- try to send the 0.001 from the new wallet to somewhere else
- it tells you that there is 0.00005 BTC missing
- reduce the amount you want to send by that: so try to send 0.00095 BTC now
- **ERROR**: it comes again with an error and tells you that there is another 0.0000465 BTC missing

continuing this procedure leads to a situation, where you can actually only send 88% of your coins. The remainder is dumped into fees.

And as I said: I'm also sure that even just the initial "only 5%" is too high.

**Comment by schildbach** [comment]
It doesn't work like that; you don't need this iterative approach. What you're trying is to empty your wallet. For this, you need to use the "empty wallet" feature.

Also, you don't explain why "only sending 88% of your coins" is wrong. Bitcoin fee is determined by byte size, rather than amount. If you have huge transactions (in terms of bytes), it can happen that the fee is 100% of the amount, or even higher.

**Comment by ar-** [comment]
The same error occurs if I "almost empty" my wallet. Therefore the "empty wallet" feature is not the solution. I've already listed the steps twice. Please look again closely at step 5 of my previous listing. 

I try to send 0.00095 BTC of my wallet that contains 0.001 BTC. So I clearly don't want to empty it.


In regards to the amount of fee. I don't know about that. As an API user I only use "BTC" and not "kilobytes". All I know is, that such a transaction is definitely possible, and will currently be accepted, without loosing 5% or more .

**Comment by schildbach** [comment]
Here is my proposed fix for the ForwardingService example: https://github.com/bitcoinj/bitcoinj/pull/1321

Can you for your example provide the output+log? Use `BriefLogFormatter.initVerbose()` at the top if it isn't shown. Also, can you for each iteration print the exception trace and `wallet.toString()`?

**Comment by ar-** [comment]
What a ridiculous project! I'm out!
