### ISSUE TITLE
Possible hash collision in PeerAddress::hashCode() for .onion addresses.

### ISSUE THREAD

**Issue by dan-da** [bitcoinj/bitcoinj#1330]
The method hashCode presently looks like this:

    public int hashCode() {
        return Objects.hashCode(addr, port, time, services);
    }

But for .onion addresses addr is null ( or bogus? ) and hostname instance variable is used instead.    The value of time can be -1 if peer reports protocol version <= 31402.  port and services can also be the same.

I think the simple fix is to add hostname into the hash, eg:

        return Objects.hashCode(hostname, addr, port, time, services);

**Comment by dan-da** [comment]
nevermind, it seems protocolVersion is set lcoally (not from peer) but I guess peers could still send duplicate timestamps and cause collisions that way.

also the equals() method and bitcoinSerializeToStream() use addr but not hostname.  I'm not sure what value of addr is for .onion addresses (if not null) but anyway it seems like hostname should be used in this case.  My understanding is that bitcoind serializes .onion addresses as ipv6 using onioncat.  

See https://bitcointalk.org/index.php?topic=20432.0

**Comment by schildbach** [comment]
Generallly hash collisions are not a problem in Java collections except perhaps for performance. It will always check equals() to be sure.

If your concern is actually that hostname is not included in equals(): We can add that. I just removed all the setters anyway so hostname can't change after construction.

**Comment by dan-da** [comment]
ok that makes sense.   I would think that adding hostname to the hash and to equals would be the right fix.  removing setters sounds good.

Can you explain how .onion addresses are shared with peers?  I don't see any code supporting that.  For example, here is what btcd does:   https://github.com/btcsuite/btcd/blob/master/addrmgr/network.go#L74

**Comment by msgilligan** [comment]
@schildbach I think we can close this one.
