### ISSUE TITLE
 Illegal key size or default parameters

### ISSUE THREAD

**Issue by sinetek** [bitcoinj/bitcoinj#1332]
Getting a handful of errors while building bitcoinj on my system.

```
bip38testvector_noCompression_noEcMultiply_test1(org.bitcoinj.crypto.BIP38PrivateKeyTest)  Time elapsed: 0.218 sec  <<< ERROR!
java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size or default parameters
	at org.bitcoinj.crypto.BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1(BIP38PrivateKeyTest.java:42)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at org.bitcoinj.crypto.BIP38PrivateKeyTest.bip38testvector_noCompression_noEcMultiply_test1(BIP38PrivateKeyTest.java:42)
```

I tried building an older version of the library but it still fails in various mysterious ways.
If someone has an idea please leave a comment, I'm not well versed in Java yet. I'm assuming people actually run those tests for now (the default behaviour when `mvn clean package`).

**Comment by sinetek** [comment]
$ javac -version
javac 1.8.0_111

Host is a macOS Sierra, nothing fancy.

**Comment by sinetek** [comment]
I tried building on Linux as well, and get the same errors.

**Comment by schildbach** [comment]
Please post build problems to the mailing list. And can you include the branch/commit you're trying to build?

**Comment by Jaystings** [comment]
What is the solution to this problem?
