### ISSUE TITLE
Deserialization transaction with non standard transaction version number

### ISSUE THREAD

**Issue by jdojff** [bitcoinj/bitcoinj#1337]
Recently there were mined several transactions with version 2. Wallet noticed it as non standard transaction and saved them to the wallet file.
Problem is with deserialization: Transaction object is created with default version 1 and no value is taken from protobuf object. This causes protobuf object hash and newly calculated transaction hash to mismatch because of different version value in different objects of the transaction.
I believe while deserializing in ``readTransaction`` version number should be read as well. What about other issues regarding this, in other parts of the library?

**Comment by schildbach** [comment]
I assume this is on testnet? Can you state the transaction IDs? With "deserialization" you mean protobuf deseralization, as opposed to Bitcoin P2P protocol deserialization?

Is this perhaps related to #1336?

**Comment by jdojff** [comment]
No, this was on livenet, 0321b1413ed9048199815bd6bc2650cab1a9e8d543f109a42c769b1f18df4174
```
0200000001d7902864af9310420c6e606b814c8f89f7902d40c130594e85df2e757a7cc301070000006b483045022100ca1757afa1af85c2bb014382d9ce411e1628d2b3d478df9d5d3e9e93cb25dcdd02206c5d272b31a23baf64e82793ee5c816e2bbef251e733a638b630ff2331fc83ba0121026ac2316508287761befbd0f7495ea794b396dbc5b556bf276639f56c0bd08911feffffff0274730700000000001976a91456da2d038a098c42390c77ef163e1cc23aedf24088ac91062300000000001976a9148ebf3467b9a8d7ae7b290da719e61142793392c188ac22e00600
```
Yes, protobuf deserialization. I does not look like to be related with #1336

**Comment by schildbach** [comment]
Thanks, that's a good catch! I've fixed the protobuf part of this issue in #1338.

Question is, should such a transaction be allowed into the wallet? Investigating…

**Comment by schildbach** [comment]
Ok version 2 transactions seem to be relevant to [BIP68](https://github.com/bitcoin/bips/blob/master/bip-0068.mediawiki) and [BIP112](https://github.com/bitcoin/bips/blob/master/bip-0112.mediawiki).

**Comment by jdojff** [comment]
Yes, thanks ;)
