### ISSUE TITLE
alert message when connecting to bitcoin core V0.14

### ISSUE THREAD

**Issue by bockha** [bitcoinj/bitcoinj#1350]
bitcoinj reports an alert, if it connects to a peer running bitcoin core V0.14:
`14:51:54.096 [NioClientManager] INFO org.bitcoinj.net.NioClientManager - Connected to /127.0.0.1:18333`
`14:51:54.119 [NioClientManager] INFO org.bitcoinj.core.Peer - [127.0.0.1]:18333: Got version=70015, subVer='/Satoshi:0.14.0/', services=0x13, time=2017-03-14 14:51:55, blocks=1093607`
`14:51:54.133 [NioClientManager] INFO org.bitcoinj.core.PeerGroup - [127.0.0.1]:18333: New peer      (1 connected, 1 pending, 1 max)`
`14:51:54.148 [NioClientManager] INFO org.bitcoinj.core.PeerGroup - Setting download peer: [127.0.0.1]:18333`
`14:51:54.278 [NioClientManager] WARN org.bitcoinj.core.Peer - Received alert with invalid signature from peer [127.0.0.1]:18333: URGENT: Alert key compromised, upgrade required`

**Comment by schildbach** [comment]
Yes, that's expected. It received the alert from the connected peer.

**Comment by bockha** [comment]
Do you know, why the new bitcoin core daemon sends that alert to bitcoinj?
Is this alert the cause for bitcoinj to repeatedly creating new Deterministic Key Chains?
Thank you in advance!

**Comment by schildbach** [comment]
Bitcoin Core sends this to any connected node, and bitcoinj is just a Bitcoin node. Apart from printing them to the log, bitcoinj completely ignores these messages.

I think Core plans to retire these messages so you won't see them any longer.
