### ISSUE TITLE
Connecting to node Connection refused 

### ISSUE THREAD

**Issue by Shehreyar237** [bitcoinj/bitcoinj#1360]
I am trying to fetch blocks for this purpose i wanted to connect to node e.g 67.205.175.176 . now issue is my connection is refused or pending . error log is: 
391 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Starting ...
1438 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Localhost peer not detected.
1438 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Peer discovery took 144.7 μs and returned 0 items
1438 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 2032 msec before next connect attempt to [67.205.175.176]:18444
1438 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 msec before next connect attempt to [67.205.175.176]:18444
2485 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [67.205.175.176]:18444     (0 connected, 1 pending, 1 max)
3485 [PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Peer discovery took 16.42 μs and returned 0 items
4610 [NioClientManager] WARN org.bitcoinj.net.NioClientManager - Failed to connect with exception: java.net.ConnectException: Connection refused: no further information
java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:64)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
	at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:49)
	at java.lang.Thread.run(Thread.java:745)

**Comment by schildbach** [comment]
Can you post support questions to the mailing list? Thanks.

**Comment by Shehreyar237** [comment]
when i tring to connect to remort node e.g  67.205.175.176 .  why i am unable to connect to node and access to blockchain. my connecting code simple is : 
BriefLogFormatter.init();
            System.out.println("Connecting to node");
            InetAddress ip=InetAddress.getByName("91.216.149.28");
            final NetworkParameters params = TestNet3Params.get();
            BlockStore blockStore = new MemoryBlockStore(params);
            BlockChain chain = new BlockChain(params, blockStore);
            PeerGroup peerGroup = new PeerGroup(params, chain);
            peerGroup.start();
            peerGroup.addAddress(new PeerAddress(ip, params.getPort()));
