### ISSUE TITLE
Is partially resetting of transaction download supposed to work?

### ISSUE THREAD

**Issue by Giszmo** [bitcoinj/bitcoinj#1365]
I need to occasionally add addresses with past, non-zero creation times. I figured, iterating through the block headers until creation-time - 4h and feeding that block height to `public void clearTransactions(int fromHeight)` should trigger the resync but it [errors out](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L3002) in a way I miss some `// TODO:` or something.

**Comment by schildbach** [comment]
Can you please ask questions on the mailing list? Thanks.
