### ISSUE TITLE
Recovering from wallet based on bitcoinj

### ISSUE THREAD

**Issue by tastyjalapeno** [bitcoinj/bitcoinj#1379]
I have backup keys from an Android wallet based on Bitcoinj (Einsteinium) which used a password rather than a wallet.dat file. Does any one know if it's possible to recover the address to use for their current wallet somehow? I have the back up key file and know the password.

**Comment by schildbach** [comment]
This is not the place to ask questions. Please contact support of that Einsteinium wallet.
