### ISSUE TITLE
BIP148 support

### ISSUE THREAD

**Issue by luke-jr** [bitcoinj/bitcoinj#1381]
BIP148 can be enforced with only block headers, so BitcoinJ should add enforcement of it. The most complicated part is versionbits support, which hopefully already exists for #1334 (although I don't see it).

**Comment by schildbach** [comment]
We could add BIP148 support, although I'm not sure it is ever needed. Yes, support for BIP9 is still missing and needs to be implemented first.

**Comment by luke-jr** [comment]
Ironically, support for it is probably needed only if support isn't added. >_<

**Comment by amitabh123** [comment]
Ok now what is the current state? Is this added in any branch?

**Comment by schildbach** [comment]
I'm not aware of anyone currently working on it.

**Comment by amitabh123** [comment]
What are the implications for bitcoinj nodes over the coming weeks?

**Comment by luke-jr** [comment]
Current state is that they are vulnerable unless you use them with a trusted BIP148 full node.

**Comment by schildbach** [comment]
Now that BIP91 has activated, BIP148 will not happen. So I'm closing this.
