### ISSUE TITLE
Wallet.FeeCalcuation is private, whilst used in public interface

### ISSUE THREAD

**Issue by eaglerainbow** [bitcoinj/bitcoinj#1387]
Hi folks,

playing around a little with bitcoinj, I came across an issue in visibility of the public API:

* Note that the class `Wallet.FeeCalculation` is a private class (see also https://github.com/bitcoinj/bitcoinj/blob/943a139d0846afb4f1432a1cfcd3949f52dede28/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L4834 )
* Several lines below, however, method `calculateFee` is declared public and has the very same class as return type (see also https://github.com/bitcoinj/bitcoinj/blob/943a139d0846afb4f1432a1cfcd3949f52dede28/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L4845 ).

Thus, either the class `Wallet.FeeCalculation` shall be made public, or the method shall be declared private. In the current state, no (external) consumer may use the method.

Background: I have a use case where I need to "forward" the amounts of incoming transactions to another address. However, the fees shall not be covered by the local wallet, but shall reduce the amount which is sent. Thus, I need to know the exact amount the fee estimation algorithm will produce beforehand.
NB: Using `emptyWallet` is not an option to me, as there may be multiple transactions ongoing at the time of forwarding.

Thanks for checking!
Best regards,
eaglerainbow

**Comment by schildbach** [comment]
Yes, indeed. I think that API was not meant for public consumption. We should make that method private. Or both Wallet.FeeCalculation and calculateFee() protected.

Your usecase should be covered by the new "recipientPaysFees" feature. See e51428dcf6e575db1ccc103043065b6a776a37ea. Hint: testing welcome (-:

**Comment by eaglerainbow** [comment]
> Your usecase should be covered by the new "recipientPaysFees" feature. See e51428d. Hint: testing welcome (-:

Sounds like a plan. I'll be busy with some other stuff for while, but intend to give e51428dcf6e575db1ccc103043065b6a776a37ea a try. Once done, I'll give feedback here...

**Comment by eaglerainbow** [comment]
> Once done, I'll give feedback here...

I just wanted to try it out, having noticed that e51428d is part of the current `master` branch. However, I stumble into issues that neither e51428d nor the current `master` (3ec862c) is compilable to me via 

``mvn clean install -DskipTests``

Is there a certain trick, which a n00b like me should be aware of?

**Comment by schildbach** [comment]
@eaglerainbow  That sounds like your com.google.protobuf:protobuf-java:2.6.1:jar artifact is corrupt in your Maven repository. It would be interesting to know why this happened. To fix, it should be sufficient to remove the artifact directory and let Maven re-download.

**Comment by schildbach** [comment]
Closing this as indeed the original issue was fixed in e3ca8f2d50d1283559f379bf8ee931fd85959f52.

**Comment by eaglerainbow** [comment]
> To fix, it should be sufficient to remove the artifact directory and let Maven re-download.

+1
Deleting the entire version of com.google.protobuf:protobuf-java:2.6.1:jar from my local maven repository fixed it.

**Comment by eaglerainbow** [comment]
As far as I could test e51428d, I'd say it'll solve my problem very nicely.  With it I would also get rid of some very ugly coding, which I had to implement as workaround.
So, good work!
(Now, I only need that feature in a released version of bitcoinj 😋 )
