### ISSUE TITLE
Support for BIP 112 - CHECKSEQUENCEVERIFY

### ISSUE THREAD

**Issue by natzei** [bitcoinj/bitcoinj#1389]
CHECKSEQUENCEVERIFY is not implemented (yet?).
I was wondering if its implementation is scheduled, considering that in bitcoin-core and bitcoin-lib (Scala), or not. Thanks.

**Comment by schildbach** [comment]
I guess you're thinking of a lightning network implementation? Is there any other usecase than that? PR welcome.

**Comment by natzei** [comment]
I was thinking about the use cases explained in the BIP. I'm building up something on top of bitcoinj and it might be required in the future (I'm still not sure at the moment).
If not scheduled, I might consider to implement it in the future.

**Comment by natzei** [comment]
Solved with commit https://github.com/bitcoinj/bitcoinj/commit/bb176dab4d067752e7fb283f5c1fb5c47f589e2c
