### ISSUE TITLE
ScriptTests: Fix and sync MINIMALDATA tests.

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1396]
As noted in #1394, `scripts_tests.json` is missing all the `MINIMALDATA` tests from Bitcoin Core. This is because for some reason, the tests pass though they're expected to fail with a specific error.

The job would be to investigate why these tests don't behave as expected and fix this. I guess a VerifyException (or a subclass of, see next issue) should be thrown. Actually I believe there is some code that tries to get the data opcodes into minimal form. I just don't know why the tests don't trigger this.

And as soon as the issue is fixed, re-add all the `MINIMALDATA` tests from Bitcoin Core.

**Comment by natzei** [comment]
PR #1399 should solve this issue.

**Comment by schildbach** [comment]
Fixed in d8af6b4be7525459ad0f806bd1969151fdb3c0f6.
