### ISSUE TITLE
ScriptTests: Check for specific errors

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#1397]
As noted in #1394, currently no specific errors are tested for in the script tests. So the tests will not catch the case where a specific error is expected, but another VerificationException is thrown instead.

The possible errors are defined in https://github.com/bitcoin/bitcoin/blob/master/src/test/script_tests.cpp#L58, though some of them refer to not implemented features as of now (e.g. `WITNESS*`).

Maybe we can use a subclass of VerficationException for each of these errors? However, there are already some subclasses defined, can we re-use or re-arrange them? Using such subclasses it should be easy to fix the test logic.

**Comment by natzei** [comment]
I think we could just arrange ScriptException, allowing to pass the error code in the constructor.

**Comment by natzei** [comment]
I've started working on it. See PR #1399

**Comment by schildbach** [comment]
Implemented in d8af6b4be7525459ad0f806bd1969151fdb3c0f6.
