### ISSUE TITLE
SegWit activation is bitcoinj prepared?

### ISSUE THREAD

**Issue by Kay-S** [bitcoinj/bitcoinj#1398]
Hi there,

we use the bitcoinj library for our apps and I was wondering if [01.08.2017 the activation of SegWit](https://www.btc-echo.de/bitcoin-segwit-aktivierung-was-sollte-man-beachten/) will cause any problems or does this library handle this hazzle? Do we have to change our code for this? Thanks for your answers. :-)

Regards Kay

**Comment by schildbach** [comment]
This is not the place for asking questions. Please post to the mailing list.
