### ISSUE TITLE
segwit: Transaction did not deserialize completely

### ISSUE THREAD

**Issue by btcontract** [bitcoinj/bitcoinj#1418]
I'm using current segwit branch of bitcoinj (with spongycastle 1.56 added, all the changes can be seen here: https://github.com/btcontract/bitcoinj). Receiving an incoming tx sometimes results in a following error while tying to deserialize a wallet on app startup:

```
07-27 08:47:02.956 8364-8450/com.lightning.wallet W/System.err: org.bitcoinj.wallet.UnreadableWalletException: Transaction did not deserialize completely: a3b181f57ae330fd6a801ad5c79cc27357996a923f650963680cc9dac2afd9b4 vs 4a3e80eb0cb8c87e727de57a94d759ef083082aae57bcb6b00cc7b82e6d6354b
07-27 08:47:02.956 8364-8450/com.lightning.wallet W/System.err:     at org.bitcoinj.wallet.WalletProtobufSerializer.readTransaction(WalletProtobufSerializer.java:697)
07-27 08:47:02.956 8364-8450/com.lightning.wallet W/System.err:     at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:523)
07-27 08:47:02.956 8364-8450/com.lightning.wallet W/System.err:     at org.bitcoinj.wallet.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:460)
```

This never happens with incoming txs from faucets such as `https://testnet.coinfaucet.eu/en/`, only txs sent from Bitcoin Core in testnet or regtest modes sometimes cause this.

Here's a hex of problematic transaction extracted from Core in a regtest mode:

> getrawtransaction a3b181f57ae330fd6a801ad5c79cc27357996a923f650963680cc9dac2afd9b4

result

> 020000000001090095e257f1b47136f281cb4860d6607ced3a4cee1231554f9c5abda096ec2ecd0000000049483045022100adee9607cd266e62b01f348522ab7260825564a9c6e53e45b6b4e32b33d5292c022049c6d60c57db6e9ef321e05dfa49f8b7f2730184a5ce78766179f4d0d4d9d76001feffffff3e640c9e25eb092df5bce0a81bc8bc4f7e765627c1c67be674edc4a106ff55200000000048473044022014fd4fcc3e48a327db09d4327955e319fdc146a68f4a5905f486989f045e8d060220388adb1cd8cc9a1fd4e82ccaec1afbc3b0a49d7f7e3c3b2447bf0a113d29102501feffffff46a92982b6d79408a10477d058a39bfb6a7104cc591979a3bc9aefcc5743be980000000049483045022100ce948d738f479cfb03df45473e039ac9d66878e14ecfacfcaea6c267e8592aaf022012d042cfd91ea3395331fe3ace5e2df82b3ebbbd6a1d5e8695c2f6ce100ce97701feffffff4a22537ad95232052c3c4734a67d57ea19c680c08985676c90c684386b7a8e49000000004847304402206f4f88e1bdf3118edd4c3527e991c62fe6e6772de2a2281070cbd729099efbd2022011398ad2d0106f4e9db5476da34b109248f9f21db538ae62a74517e011de3c6301feffffff789226098cec1e02f8a9903a700f47c3c773ffd6838d6e9b61564593fd34cbf60000000049483045022100cc115fe87dd62c3668488dbe1526db66ec4cbc6d735a0cbde384fc8aa270a6fc022051c8eca66baa49683a8cf4520e97995ff586b4c5c35f27bb17379faadd26a8d701feffffff7ebb5679cc499c67deebb04fd8b89ef214598fbbb6012fa08e92e973704fe960000000004948304502210093b000a0b197fa997299efaf86ea09e36012dc6e97bb150255c9e4f470f05518022052af3e2473b670f5b67c384626948e281a2c0a6082808fc317d13ed01106f01301feffffffc1d7ced3cf2d5e99aa015b6be3a0b93549363e343b68ee41834de345618fef570000000049483045022100fc1f89330b88cec605a3cd3bcae23536632b3b18b82a026fc441d2c4f9fb6396022032c345afae7dcb826d628c9605c84dd320794495a7ecdd13da682ee802fe815e01feffffffe8220f08b2c24214d570dc440cf4afb68853533df9d94e3998aa76266f0da4760000000048473044022074e8416947b7a64ec7f432883510308b5a77f35c94b3d34628298c94285da04b0220221572e243c92a658759a1f3cb593314b6da9ad06d2e9aee064b5b77f645013201fefffffff6845ded4529faa52a93adb4625d65cccbd24502dbcd7796abb453c9975f948a0000000017160014aa803da714b75c40fed1fd3760a3b04834e6f400feffffff0180f0fa02000000001976a91468e5816c108e1c1914c6d184fbfa7cc8b95bde9388ac000000000000000002483045022100c754d1e111949087c4241af4fcce942ec6bc65945e01c523c49b229caaea5baa022001030ea88a3e3f42bef00365c5cdf8d3efddb38329bedac8e85065ecfec67ad4012103f1e59ea153916237dc331ccc8cd2c2c7241d93ad963f1897a33b3a9d711a705b9d1d0000

**Comment by schildbach** [comment]
The exception suggests that transactions are missing some information (e.g. their witnesses) after being protobuf-serialized and back. Since wallet.proto hasn't been touched yet on the segwit branch I'd say this is quite likely. I'll add protobuf serialization to the segwit todo list.

**Comment by schildbach** [comment]
See #1437.

**Comment by schildbach** [comment]
Should be fixed on the segwit branch now.
