### ISSUE TITLE
Remove support for alert-messages

### ISSUE THREAD

**Issue by frohal** [bitcoinj/bitcoinj#1426]
Related to the fact that those messages are retired, the code to handle them should be removed.
https://bitcoin.org/en/alert/2016-11-01-alert-retirement

**Comment by schildbach** [comment]
Bitcoinj doesn't do anything with them anyway, so do they hurt?

**Comment by frohal** [comment]
Well. They pollute the logs, as I see it, and other wallets hs removed them...  
Not a big issue, since I just removed the output in my build, but it's a bit cumbersome to remember to do this every time I update from git :)

**Comment by schildbach** [comment]
I demoted the logging of alert messages to `debug` via commit 9c49fd5692dd4da59b3980d63c460821679e78a7. I think this should be enough for now.
