### ISSUE TITLE
how to withdraw the bitcoin from the wallet created programmatically

### ISSUE THREAD

**Issue by mullex** [bitcoinj/bitcoinj#1434]
I need to create web wallets in my web project for each user. The scenario is as below:

1.The user creates an account.
2.The project automatically Create a wallet for each user.
3.The project automatically send some bitcoins to the user's wallet.

The questions are:
1.Is it an appropriate to use bitcoinj to create the wallet for each user?
2.How can the user back up the bitcoin wallet?
3.how can the user take out the bitcoins from the wallet?

**Comment by schildbach** [comment]
This is not a support forum. Please have a look at the mailing list archives.
