### ISSUE TITLE
Can commit conflicting txs

### ISSUE THREAD

**Issue by pm47** [bitcoinj/bitcoinj#1442]
The way I understood the [documentation](https://bitcoinj.github.io/working-with-the-wallet), the purpose of the functions `commitTx`/`maybeCommitTx` is to detect race conditions when creating txes.

Here is what I do (in scala, let me know if I need to _javaify_):
```scala
    val wallet: Wallet = ...

    def makeTx(amount: Coin, script: Script): Transaction = {
      val tx = new Transaction(wallet.getParams)
      tx.addOutput(amount, script)
      val req = SendRequest.forTx(tx)
      wallet.completeTx(req)
    }

    val tx1 = makeTx(amount1, script1)
    val tx2 = makeTx(amount2, script2)

    // everything is fine until here, and as expected tx1 and tx2 spend the same input
    
    wallet.maybeCommitTx(tx1) // returns true as expected
    wallet.maybeCommitTx(tx2) // returns true! how come?

```

Have I missed something?

Thanks!

**Comment by pm47** [comment]
Worth noting, I am using the branch segwit. But am I right that second maybeCommit should return false?

**Comment by schildbach** [comment]
A while ago we added a new confidence type, IN_CONFLICT. That means two (or more?) pending transactions are in conflict and not all of them will be confirmed (but all of them *could*). I assume this is what you're seeing. To be sure, have a look at the transaciton confidence of tx1 and tx2 after your program run. And also maybe test this on master and on release-0.14?

Such questions are best asked on the mailing list.

**Comment by pm47** [comment]
Ok, I am closing this issue and will follow up on the mailing list, thanks!
