### ISSUE TITLE
Please consider signing your release tags

### ISSUE THREAD

**Issue by abliss** [bitcoinj/bitcoinj#1453]
Thank you for bitcoinj! I just cloned the repo and was dismayed to find that the release tag 0.14.5 does not appear to be signed at all. That makes it slightly scarier to rely on this app to handle my unencrypted wallet files. Would you consider pgp-signing the release tags?

Thanks again!

**Comment by abliss** [comment]
Ah, I see, you have set up refs/heads/release-0.14 as a branch instead of a tag. The tag 0.14.4 itself is signed. Thanks!

**Comment by abliss** [comment]
PS where is your public key? I don't see 64851E76 on pgp.mit.edu.

**Comment by schildbach** [comment]
Yes, we only sign tags not branches/commits. The above signing subkey expired recently, my current signing subkey is F8174599.

I'm not sure if I can add another signature to a git tag.

**Comment by schildbach** [comment]
I'm sorry I just noticed there is actually a version 0.14.5 and I forgot to tag it. If you sync your git repo you should now find that tag, signed by my non-expired signing subkey F8174599.

**Comment by abliss** [comment]
Awesome, thanks! Where can I find your public key?

**Comment by schildbach** [comment]
It should be on pgp.mit.edu.
