### ISSUE TITLE
Use char[] for passphrases instead of Strings in BIP38PrivateKey

### ISSUE THREAD

**Issue by Ahmad-Saleh** [bitcoinj/bitcoinj#1456]
There is a security risk in using Strings for sensitive data, such as passphrases and private keys, as Strings in Java are immutable and they will stay in memory until the GC kicks in.

it is always recommended to use char arrays instead, as they can be manually cleared from memory once we are done with them, reducing the amount of time they stay in memory and hence lowering the risk of reading them by an attacker. 

BIP38PrivateKey uses String for passphrases.

**Comment by schildbach** [comment]
Duplicate of #1411.
