### ISSUE TITLE
Cannot send BTC

### ISSUE THREAD

**Issue by reducta** [bitcoinj/bitcoinj#1457]
Sending 0.0001 BTC minus commission (0.00005)= 0.00005 BTC using  REFERENCE_DEFAULT_MIN_TX_FEE

With an Available (and Estimated) balance of  0.00299637 

throws
org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.00390734 BTC

I cannot send anything, the exception is always raised no matter the amounts

Many thanks!

**Comment by schildbach** [comment]
This is not a support forum. Can you ask on the mailing list please?
