### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by 0pay** [bitcoinj/bitcoinj#1475]
Hi, I'm trying to build with Maven the Bitcoinj library
My environment is:
Maven 3.5.2
Java version: 1.8.0_112,
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"

-------------------------------------------------------------------------------
When I start the comand mvn clean package the build Failure.
this is the error
Test set: org.bitcoinj.core.LevelDBFullPrunedBlockChainTest
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.986 sec <<< FAILURE! - in org.bitcoinj.core.LevelDBFullPrunedBlockChainTest
testFirst100KBlocks(org.bitcoinj.core.LevelDBFullPrunedBlockChainTest)  Time elapsed: 0.142 sec  <<< ERROR!
java.lang.UnsatisfiedLinkError: Could not load library. Reasons: [no leveldbjni32-1.8 in java.library.path, no leveldbjni-1.8 in java.library.path, no leveldbjni in java.library.path, C:\Users\aka\AppData\Local\Temp\leveldbjni-32-1-4245911768728454376.8: Can't find dependent libraries]
	at org.bitcoinj.core.LevelDBFullPrunedBlockChainTest.createStore(LevelDBFullPrunedBlockChainTest.java:40)

I think there are some problem with java.library.path.
Any help ?
Thank you

**Comment by schildbach** [comment]
This is not a support forum. Can you post to the mailing list?
