### ISSUE TITLE
Android SpongyCastle: Lower Android Bitcoinj API Error

### ISSUE THREAD

**Issue by zrabatah** [bitcoinj/bitcoinj#1476]
I am currently developing an Android application with the bitcoinj library.

My app currently works with a RCA tablet I am using (Android V23, 6.0 Marshmallow), as well as two Samsung Galaxy S5 phones using (Android V23, 6.0 Marshmallow). However, when I use it with a Samsung Galaxy S5 with (Android V19, 4.4.4 Kitkat), and two different Samsung Galaxy S3's with (Android V19, 4.4.4 Kitkat) the application gives the error log below.

Based on this testing it is obviously an error with the lower android version not the hardware (maybe lower versions of android do not come with the org.spongycastle.crypto library or is missing references for it). I added the following four _italicized_ compile links to my gradle and synced it to my app. However, these references do not solve the issue; maybe these are not the correct gradle references.

    _compile 'com.madgag.spongycastle:core:1.58.0.0'
    compile 'com.madgag.spongycastle:prov:1.58.0.0'
    compile 'com.madgag.spongycastle:pkix:1.54.0.0'
    compile 'com.madgag.spongycastle:pg:1.54.0.0'_

**Method Called where failure occurs:

NetworkParameters networkParameters = TestNet3Params.get();**

This is the first call in my app that references the bitcoinj library. Of course there are wallet calls and other code that involves the bitcoinj api. I have successfully been able to create a wallet and network with the Android API 23 devices.

Does anyone have any experience with this error? Is there a step that I am missing with my integration with the gradle or is it something else? I have not been able to find this error anywhere online, hence why I am posting it here.

**ERROR LOG:**
java.lang.NoClassDefFoundError: org.spongycastle.crypto.ec.CustomNamedCurves
                                                                                       at org.bitcoinj.core.ECKey.<clinit>(ECKey.java:121)
                                                                                       at org.bitcoinj.core.Block.<clinit>(Block.java:896)
                                                                                       at org.bitcoinj.core.NetworkParameters.createGenesis(NetworkParameters.java:116)
                                                                                       at org.bitcoinj.core.NetworkParameters.<init>(NetworkParameters.java:112)
                                                                                       at org.bitcoinj.params.AbstractBitcoinNetParams.<init>(AbstractBitcoinNetParams.java:52)
                                                                                       at org.bitcoinj.params.TestNet3Params.<init>(TestNet3Params.java:39)
                                                                                       at org.bitcoinj.params.TestNet3Params.get(TestNet3Params.java:78)
                                                                                       at

**Comment by schildbach** [comment]
What branch/tag/commit of bitcoinj are you on? Note that spongycastle should never be part of any OS, as that's the whole reason this fork of bouncycastle was created.

**Comment by zrabatah** [comment]
Hello Andreas,

Thank you for your email.

I am using the following version of bitcoinj. (V 14). Do you think that I
should use a previous version in my build or should I always use the latest
version?

compile 'org.bitcoinj:bitcoinj-core:0.14.4'

I also am including these two gradle calls in the app, as they are
required to use bitcoinj based on github references and other sample
apps I have seen.

compile 'org.slf4j:slf4j-api:1.7.12'
compile 'org.slf4j:slf4j-simple:1.7.12'


zrabatah


On Thu, Nov 2, 2017 at 4:53 AM, Andreas Schildbach <notifications@github.com

**Comment by zrabatah** [comment]
schildbach,

I have done some more testing on other virtual devices. My conclusion is that your library works for Android Versions 21 & over. Android 19 and under does not work with the library for some reason. I am not sure if it is a specific issue with my build or if it is the library itself however.

**Comment by schildbach** [comment]
There is nothing wrong with using the stable branch 0.14.x. However, it is still using SpongyCastle 1.51.0.0. I recommend staying with that version because there were incompatible changes.

In fact, you don't need to add the dependencies at all since Maven knows transitive dependencies and adds them automatically if you have a bitcoinj dependency. (Unless you're depending on a SpongyCastle class in your own code, in which case you should indeed add the dependency.)

**Comment by schildbach** [comment]
Did you manage to solve your problem?
