### ISSUE TITLE
How to get notified of a new block using bitcoinj?

### ISSUE THREAD

**Issue by mahalamobile** [bitcoinj/bitcoinj#1480]
Hi,

Am looking on how to get notified of the arrival of a new block. Can this be done? will it contain the block height info and the relay as well as timestamp?

thanks

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.

**Comment by mahalamobile** [comment]
Hi,Access to public Google Groups has been restricted by your domain admin

then i follow google instructions to fix this and get

Your existing Google Apps subscription cannot be converted to G Suite
Business.


So this is why i posted on issues :)


can you help or point me to a link please?


thanks
