### ISSUE TITLE
Create a separate library that contains the parts usefull for other Blockchains

### ISSUE THREAD

**Issue by marvin-we** [bitcoinj/bitcoinj#1486]
Hello together and a big thanks for providing this library.

I have the follownig "feature" request:

I develop a Java-Library for the [Steem-Blockchain](https://github.com/steemit/steem/) called [SteemJ](https://github.com/marvin-we/steem-java-api-wrapper) and I try to reuse as much parts of bitcoinJ as possible - Why? Because this project is well documented, the code quality is really great and the lib itself is bulletproof. 

A lot of your implementations (e.g. the ECKey object or the Utils class) provide functionallities required in nearly all Blockchain libs out there. Due to that a lib developer has three options:

1. Implement something on his/her own (e.g. IOTA)
2. Use the whole bitcoinJ project (e.g. SteemJ)
3. Copy your code (e.g. EtheriumJ)

I guess number one can be pretty time consuming as it will require a lot of time until the developer gained the knowledge that you already have and will also not reach the code quality you offer.

Number two is what I am currently doing. This solution has one disadvantage: I need to add the whole BitcoinJ library while only using some specific classes.

Number three solves this problem, but you manually need to take care of updates and merge updates/changes manually.

So I was wondering if it would be possible to put classes that are not bitcoin specific into a separate package?

**Comment by Polve** [comment]
I have a similar problem and would really, really love for bitcoinj to be modularized so that I could use a few classes instead of the whole lot.

**Comment by schildbach** [comment]
Such topics are best discussed on the mailing list. Interesting idea, but please can you post this there?

**Comment by msgilligan** [comment]
FYI @marvin-we has started a thread, [Create a separate library that contains those parts which are useful for other Blockchains](https://groups.google.com/forum/#!topic/bitcoinj/OgoHv6AgvmA) on the **bitcoinj** mailing list to continue the discussion.
