### ISSUE TITLE
Unknown network parameters ID org.dogecoin.production

### ISSUE THREAD

**Issue by TheNameKevinWasTaken** [bitcoinj/bitcoinj#1496]
When running `./wallet-tool reset --wallet=/tmp/bitcoin-wallet-decrypted-backup` on an unencrypted protobuf wallet I get the error `Unknown network parameters ID org.dogecoin.production`

**Comment by langerhans** [comment]
That means you are trying to load a dogecoin wallet into bitcoinj. That obviously does not work and you should use libdohj (and make wallet-tool use its provided Dogecoin network parameters).
