### ISSUE TITLE
Unnecessary accountPath included in Watch Key Methods

### ISSUE THREAD

**Issue by HashEngineering** [bitcoinj/bitcoinj#1501]
While working on a pull request that I plan to submit soon, changes were observed in this commit that are unnecessary and in one case change the path of a key: 
 https://github.com/bitcoinj/bitcoinj/commit/e036f8174aa5acb4fa8acf3b05f2c743f4b64353 (Allow to create wallets with an arbitrary account path.)

The main point of that commit was to allow for wallets to be created that used arbitrary paths such as BIP44.  This required a change to the protobuf format to store the path related to the seed, so the correct derivation path would be used in the DeterministicKeyChain.  Other methods in bitcoinj pertaining to creating wallets with a seed would also include the path.  Some changes were made to the methods relating to watched keys to also include an account path in the same way.  However those changes were not necessary because DeterministicKey already has its own path attribute.

Take for instance this constructor:
```
public DeterministicKeyChain(DeterministicKey watchingKey) {
       this(watchingKey, ACCOUNT_ZERO_PATH);
}
```
`watchingKey` has a path and it may be different from `ACCOUNT_ZERO_PATH`.

This is the constructor called from above and the accountPath parameter is unnecessary.
`public DeterministicKeyChain(DeterministicKey watchingKey, ImmutableList<ChildNumber> accountPath)`

If a key is ever created in bitcoinj, even if from deserializing an extended private key, then it will have a relative path. 

Several other changes were made to bitcoinj due to adding the accountPath as a parameter to watched keys, including several `from...` methods in Wallet to created watched wallets from DeterministicKeys or serialized Base58 strings.

I can submit a pull request for the changes reverting the watched key methods back to their original forms before the referenced commit.

**Comment by schildbach** [comment]
Sounds good to me.

@gmagnotta @DaLN What do you think?

**Comment by DaLN** [comment]
@schildbach Seems ok to me. It would need testing that everything is working properly.

**Comment by HashEngineering** [comment]
This has been merged as https://github.com/bitcoinj/bitcoinj/commit/d3dca96a3cfdccdce65712eed0207d1c1c0e7e49 and https://github.com/bitcoinj/bitcoinj/commit/be382c68000590b9205c078e3cd8247c0ab2b905.
