### ISSUE TITLE
send btc

### ISSUE THREAD

**Issue by thomsonimjd** [bitcoinj/bitcoinj#1524]
Below code to send btc to another address, which doesnt work infact. I recieve error as `org.bitcoinj.core.InsufficientMoneyException: Insufficient money,  missing 0.10001 BTC`.  But the privatekey of the address(`mmdGi7VYs4jZgbkijwymbDQoqC4Y7GheBi`) has got more than 3 btc.
Could you please let me know how to fund transfer?  It would be greateful if there is any sample code.
`
public class Test {
    public static void main(String[] args) throws UnreadableWalletException {

        final String privateKey = "110645473594007170951217953103376391066487920337671115675429964378135171617089";
        final NetworkParameters netParams = TestNet3Params.get();
        Wallet wallet;
        try {

            ECKey key = ECKey.fromPrivate(new BigInteger(privateKey));
            wallet = Wallet.fromKeys(netParams, Arrays.asList(key));
            BigDecimal btcToSend = new BigDecimal("0.1");

            Address targetAddress = new Address(netParams, "mg2KDDsAre7StuYWUsdnBPy2KWDQywskH3");
            SendRequest sendRequest = SendRequest.to(targetAddress, Coin.parseCoin(btcToSend.toString()));

            PeerGroup peerGroup = new PeerGroup(netParams);
            // Do the send of 1 BTC in the background. This could throw InsufficientMoneyException.
            Wallet.SendResult result = wallet.sendCoins(peerGroup, sendRequest);
            System.out.println(result.tx);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
}`

**Comment by bockha** [comment]
The newly created wallet does not now anything about the blockchain nor about its UTXOs. Either you could add a peergroup and a blockstore und download the blockchain or you could feed the UTXOs manually into the wallet like it is donw when emptying paper wallets.

**Comment by wenzh913** [comment]
I encountered the same problem. Could you solve it? Can you tell me how you solved it?

**Comment by wenzh913** [comment]
I encountered the same problem. Could you solve it? Can you tell me how you solved it?
