### ISSUE TITLE
Upgrade Protobuf to 3.4.0

### ISSUE THREAD

**Issue by rabbitonweb** [bitcoinj/bitcoinj#1531]
Currently in use is `com.google.protobuf:protobuf-java:2.6.1`. Is there anything stopping us to upgrade to `3.4.0` ?

**Comment by schildbach** [comment]
Such questions are best asked on the mailig list. Proto3 is a different language which is why I'm afraid of the change. But I never took a deeper look into it.

**Comment by schildbach** [comment]
Fixed in https://github.com/bitcoinj/bitcoinj/pull/1535
