### ISSUE TITLE
Bug:  Wallet Encryption of DeterministicKeyChain with Arbitrary Path

### ISSUE THREAD

**Issue by HashEngineering** [bitcoinj/bitcoinj#1532]
This is a followup issue to this feature:  **Allow to create wallets with arbitrary path (e.g m/44'/0'/0/0)** 
https://github.com/bitcoinj/bitcoinj/commit/e036f8174aa5acb4fa8acf3b05f2c743f4b64353
#1341

When using the Wallet.encrypt feature, there is an IllegalArgumentException exception thrown if the wallet contains a DeterministicKeyChain with an arbitrary path other than (m/0H - the default for bitcoinj).

The cause is in the `DeterministicKeyChain(KeyCrypter crypter, KeyParameter aesKey, DeterministicKeyChain chain)` constructor where the account path is not set to that of `chain`.  This results in an `IllegalArgumentException` in `DeterministicHierarchy.get`.  For example in the case of BIP44, `get` will be looking for a path of `0H` but should be looking for `44H/0H`

I will further work to determine the fix and if other methods are affected by this bug.

**Comment by schildbach** [comment]
Fixed via e0d9683bd54c4e60d71840ad1ab2409016a3e0f9
