### ISSUE TITLE
Derive Addresses from xpub and tpub key

### ISSUE THREAD

**Issue by HamzaBinSarfraz** [bitcoinj/bitcoinj#1546]
Dear all, I am not able to figure out how to use the API and derive addresses from a xpub and tpub key only.
Can anybody give me an example, how this works with?

**Comment by schildbach** [comment]
Can you ask this question on the mailing list please?

**Comment by SoTDarksoul** [comment]
Where can I find an answer for this?

**Comment by HamzaBinSarfraz** [comment]
you can drive addresses from xpub key like this: 
`// Specify the Network Parameters for mainnet or testnet
NetworkParameters params = NetworkParameters.prodNet();

// Provide the public key from which you want to derive addresses
String xPub = "xpub6Cw8YA6Mko3xfkYpMQDZjGjgDTWUrJr87NBSiDPXqcmcSJTgxLXm3VCw3iQs4iC5ZrwpY3M21a43DZmiMzDXWzzhF1n7yxSXDnEHjJN6jwK";

// Create watching wallet, with the help of Wallet class
Wallet wallet = Wallet.fromWatchingKeyB58(params, xPub, DeterministicHierarchy.BIP32_STANDARDISATION_TIME_SECS);

// Print the very first derived address from provided public key
System.out.println("Receiving Address : " + wallet.currentReceiveAddress());`

**Comment by HamzaBinSarfraz** [comment]
public and private key associated with address ?

**Comment by SoTDarksoul** [comment]
Yes, a bit like on the Ian Coleman website. I manage to get the public key though with getPublicKeyAsHex() but it seems you can't get the private key, since it must certainly be the watchkey

**Comment by HamzaBinSarfraz** [comment]
yes cuz we can generate watching wallet from xpub key, which does not have prv key, you can not send money using watching wallet as you can only watch tx

**Comment by SoTDarksoul** [comment]
And do you think we can with the extended private key xpriv instead of xpub?

**Comment by HamzaBinSarfraz** [comment]
i don't think it works,
