### ISSUE TITLE
When I test restoreWalletFromSeed Download Speed is very slowly

### ISSUE THREAD

**Issue by mnock** [bitcoinj/bitcoinj#1551]
信息: 25 blocks/sec, 0 tx/sec, 38303 pre-filtered tx/sec, avg/last 7.67/1.95 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
四月 04, 2018 5:35:32 下午 org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator calculate
信息: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 7.67/0.00 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
四月 04, 2018 5:35:33 下午 org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator calculate
信息: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 7.67/0.00 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
四月 04, 2018 5:35:34 下午 org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator calculate
信息: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 7.67/0.00 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)
四月 04, 2018 5:35:35 下午 org.bitcoinj.core.PeerGroup$ChainDownloadSpeedCalculator calculate
信息: 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 7.67/0.00 kilobytes per sec (stall threshold <1.56 KB/sec for 10 seconds)

**Comment by schildbach** [comment]
I don't think this has anything to do with how you initialize the seed. Probably you were on a slow download peer. I'd check the logfile for the peer that was selected and then do some testing on that peer.

Normally bitcoinj should switch to a faster peer if the one you're downloading from is too slow.

**Comment by KaushikTechcronus** [comment]
Hello,
At time of restore from seed I used 1409478661L creation time but it will take 30 minutes to download from block chain.
Please help me to decrease the time.

**Comment by Diorrr** [comment]
@schildbach Hi, could you explain how to use CheckpointManager?
