### ISSUE TITLE
Missing Private Key Issue?

### ISSUE THREAD

**Issue by SazzadIproliya** [bitcoinj/bitcoinj#1556]
Hello All,
I was using Bitcoinj Library version 0.14.5. Also, I downloaded all classes and added Customly In project. Because I used 24 seed in place of 12 seed. So I was implemented All the class Customly.

The issue occurs at the time of send Transaction. Anyone have a proper solution so Please provide me.

**Comment by schildbach** [comment]
Please post questions to the mailing list. Thanks.
