### ISSUE TITLE
why set shouldVerifyTransactions function return false

### ISSUE THREAD

**Issue by cyssxt** [bitcoinj/bitcoinj#1560]
I want to use postgresBlockStore ,but I found that openoutput always without data!
I follow the code and fount that BlockChain.class has function shouldVerifyTransactions always return false,
that cause openoutputs has no result.
Is it a problem or for somthing else?

**Comment by cyssxt** [comment]
I found that reason！ I should use FullPrunedBlockChain to construct a BlockChain instance.

**Comment by schildbach** [comment]
Please ask questions on the mailing list. Thanks.
