### ISSUE TITLE
Why the bitcoinj sync block is very slow where block header height over 230000

### ISSUE THREAD

**Issue by cyssxt** [bitcoinj/bitcoinj#1566]
final NetworkParameters params = MainNetParams.get();
            try {
                PostgresFullPrunedBlockStore blockStore = new PostgresFullPrunedBlockStore(params, this.fullStoreDepth, this.host, this.db, this.username, this.password);
                FullPrunedBlockChain chain = new FullPrunedBlockChain(params, blockStore);
                final PeerGroup peerGroup = new PeerGroup(params, chain);
                peerGroup.addPeerDiscovery(new PeerDiscovery() {
                    @Override
                    public InetSocketAddress[] getPeers(long services, long timeoutValue, TimeUnit timeoutUnit) throws PeerDiscoveryException {
                        RpcInfo rpcInfo = ServiceUtils.getRpcInfoUtils().getRpcInfo(TokenConstant.BTC);
                        String urlBatch =rpcInfo.getUrlBatch();
                        String url = rpcInfo.getUrl();
                        InetSocketAddress inetSocketAddress = get(urlBatch);
                        InetSocketAddress urlAddress = get(url);
                        List<InetSocketAddress> socketAddresses = new ArrayList<InetSocketAddress>();
                        if(inetSocketAddress!=null){
                            socketAddresses.add(inetSocketAddress);
                        }
                        if(urlAddress!=null){
                            socketAddresses.add(urlAddress);
                        }
                        InetSocketAddress[] inetSocketAddresses = new InetSocketAddress[socketAddresses.size()];
                        return socketAddresses.toArray(inetSocketAddresses);
                    }

                    @Override
                    public void shutdown() {

                    }
                });
                peerGroup.addPeerDiscovery(new DnsDiscovery(params));
                peerGroup.start();
                peerGroup.downloadBlockChain();
            } catch (Exception e) {
                logger.error(e + "");
            }

I have sync for a week,but the current sync block height is is only 230000?Is it correct?

**Comment by cyssxt** [comment]
Can someone have same question?

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
