### ISSUE TITLE
Factor out recId search logic

### ISSUE THREAD

**Issue by matthewleon** [bitcoinj/bitcoinj#1568]
`ECKey.signMessage` contains a block of logic for determining a key's `recId`, beginning here: https://github.com/bitcoinj/bitcoinj/blob/0b0ea0c7e5a875c1b5fabe64aad6a86a8d69b0fc/core/src/main/java/org/bitcoinj/core/ECKey.java#L869

This logic is itself potentially useful to library users, and could be exposed as a new method, perhaps `public byte getRecId(ECDSASignature sig, Sha256Hash hash)`.

I would be happy to provide a PR for this.

**Comment by schildbach** [comment]
Sure, feel free to!
