### ISSUE TITLE
non final VersionedChecksummedBytes.toBase58() ?

### ISSUE THREAD

**Issue by Polve** [bitcoinj/bitcoinj#1569]
Hi, for the project I'm working on I need to overwrite that function but I'm unable to since it's final: is it really necessary?

So I'm now forced to handle a private branch and build where the difference from bitcoin is just the "final" keyword removed in the function toBase58() in class VersionedChecksummedBytes.

I would really appreciate if you could evaluate the possibility to let the method be overridable, and of course I would also create a PR for that, if accepted.

Thanks

**Comment by Polve** [comment]
For example in Groestlcoin version and bytes are not enough since a different hashing function is used.
Anyway, I just wanted to know if there was a reason to declare it final: if there are no side effects, maybe dropping the final clause is doable.

**Comment by schildbach** [comment]
Also you could override toString()?

**Comment by schildbach** [comment]
But yes, we could probably remove the final as I added it only because base58 is on the way out.

**Comment by schildbach** [comment]
Actually are you talking about the current version in master? Because there is no VersionedChecksummedBytes any more, it has been renamed to PrefixedChecksummedBytes, and it also doesn't have any base58 specific code any more.

**Comment by Polve** [comment]
I'm not using master but the latest stable release with the segwit branch.
It's not a big deal, I found a workaround without having to override the function, anyway I was curious to know possible reasons to have that method final.
Since you do not support altcoins (and I can well understand why), I find good to have the library as extensible and overridable as possible in order to avoid having to clone and handle a custom branch for trivial modifications.

**Comment by Polve** [comment]
Since master is quite different I suppose the bug report can be closed, thanks for any followups.
