### ISSUE TITLE
What is the hashing or decoding used for bitcoin message

### ISSUE THREAD

**Issue by commentors-net** [bitcoinj/bitcoinj#1573]
In the code we have 

04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73

which is a difficulty bits for message 

The Times 03/Jan/2009 Chancellor on brink of second bailout for banks

can anyone provide a update what hashing or encoding is used to get that string?

I used 

String str = "The Times 03/Jan/2009 Chancellor on brink of second bailout for banks";
String ss = BaseEncoding.base16().lowerCase().encode(str.getBytes()));

and output I have 
5468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73
 whereas in code it has extra "04ffff001d010445"

I am struggling to find that but failed so far.

A help will be very much appreciated and my job will be saved :-)

This is the output when I am decoding the string in code via 

byte[] bytes = Utils.HEX.decode(			"04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73");
String s = new String(bytes);

![decoding](https://user-images.githubusercontent.com/15863443/39478922-53754ae2-4d96-11e8-9a14-4bd06ed23c6a.PNG)

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
