### ISSUE TITLE
IntelliJ IDE - Import Problem (import class org.bitcoinj.wallet.Protos)

### ISSUE THREAD

**Issue by morismc** [bitcoinj/bitcoinj#1583]
Hello Devs,
today I tried to build the source code of the sample wallet project. After running the Main.java file, I got over 100 problems (see following image): https://imgur.com/a/KClCL0u
Did I miss anything?
Thanks in advance for your support and have a great day.
Cheers,
Maurice

**Comment by morismc** [comment]
I recently noticed that the class "Protos" seems to be missing. Can someone of you confirm?

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
