### ISSUE TITLE
ask :core:generateProto FAILED

### ISSUE THREAD

**Issue by anxiaohe** [bitcoinj/bitcoinj#1585]
> Task :core:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:generateProto'.
> java.io.IOException: Cannot run program "protoc": error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 45s
7 actionable tasks: 3 executed, 4 up-to-date

How to solved?

**Comment by schildbach** [comment]
The protobuf plugin cannot find the protobuf compiler. Do you have the Debian/Ubuntu package "protobuf-compiler" installed?

**Comment by schildbach** [comment]
I assume you fixed your problem.

**Comment by Ged0** [comment]
I meet the problem on macOS too. I have the protoc installed and I can use protoc in my terminal.

**Comment by adiaholic** [comment]
@schildbach what if im running on windows
