### ISSUE TITLE
addWallet after peerGroup starts

### ISSUE THREAD

**Issue by ddengster** [bitcoinj/bitcoinj#1588]
Hi,

I'm calling peerGroup.addWallet after the following lines of code are called:

peerGroup.addPeerDiscovery(new DnsDiscovery(TestNet3Params.get());
peerGroup.start();

However, the balance of the wallet when queried does not show up. Is this not supposed to work?

PS. I imported keys into the wallet using wallet.ImportKey

**Comment by schildbach** [comment]
It is expected. Can you ask questions on the mailing list? Thanks.
