### ISSUE TITLE
How to extend address header by two bytes?

### ISSUE THREAD

**Issue by vetal20600** [bitcoinj/bitcoinj#1593]
Hello, is there are a quick way to extend [addressHeader](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/NetworkParameters.java#L77) by two header bytes?
There already is similar feature included in latest releases of [bitcoin core source code](https://github.com/bitcoin/bitcoin/blob/master/src/chainparams.cpp#L140).

What I need is a direction for a way how to do it. Maybe bitcoinj community have suggestions where to look/what to change. It seems to me that bitcoinj requires a lot of source code modification for the way I want. Starting from **VersionedChecksummedBytes** class, **Address** class, **ECKey** class and more

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.

**Comment by vetal20600** [comment]
Ok. I will.
