### ISSUE TITLE
Package Protos does not exist

### ISSUE THREAD

**Issue by Vutov** [bitcoinj/bitcoinj#1598]
I've cloned master and followed the "Building from an IDE" instructions. The build is passing, Gradle is all green, however when I try to run any of the examples - there are over 100 compile errors - most related to "java: package Protos does not exist" or something Protos related. 
System: Win10 (latest), Java version "1.8.0_171", Gradle 4.8.1. using latest Intellij community edition.
Any help to what I'm doing wrong will be much appreciated.

**Comment by schildbach** [comment]
Duplicate of #1587
