### ISSUE TITLE
How to make Replace-By-Fee TX with BitcoinJ

### ISSUE THREAD

**Issue by muraviovvladimir** [bitcoinj/bitcoinj#1619]
First was faced with endless pending Transaction in BitcoinJ FrameWork

The main documentation says that it can be made by Replace-By-Fee. So you need to take the old transaction and create a new one but based on previous.

Sounds good, but how correctly, using Bitcoinj framework create another one?

bitcoinService = new BitCoinService();
bitcoinService.startService();

ArrayList<Transaction> pendingList = new ArrayList<>(bitCoinService.wallet.getPendingTransactions());

What is next? 
Transaction nextTx = new Transaction(pendingList.get(0)); // is not possible

**Comment by hczerpak** [comment]
First your original transaction must be RBF enabled. If you have not enabled RBF in your original transaction you will not be able to replace it. 
It is done by setting sequence number on any of transaction inputs to  value 0xffffffff - 1. I'd try

```
for (TransactionInput transactionInput : tx.getInputs()) {
                transactionInput.setSequenceNumber(0xFFFFFFFFL - 2);
            }
```

**Comment by wdd906** [comment]
I try this, but it did not work.
