### ISSUE TITLE
This class can't be found org.bitcoinj.core.LegacyAddress

### ISSUE THREAD

**Issue by 401825317** [bitcoinj/bitcoinj#1621]
env:
eclipse+jdk1.8
![image](https://user-images.githubusercontent.com/19526136/43377025-ced58d5a-93f0-11e8-8105-df39677b0914.png)
<------------------------------------------------------------------------------------------------------------->
![image](https://user-images.githubusercontent.com/19526136/43377005-a7a3535c-93f0-11e8-9461-61fe90875ac0.png)
This class can't be found org.bitcoinj.core.LegacyAddress
can you help me?

**Comment by BigAdam2005** [comment]
Show import list, did you imported it.

**Comment by natzei** [comment]
@401825317 Check your bitcoinj version

**Comment by 401825317** [comment]
I'm using 0.14.7, and I've solved zhjg

replace:

        forwardingAddress = Address.fromBase58(params, args[0]);
