### ISSUE TITLE
Base58 - Cannot resolve symbol 'encodeChecked'

### ISSUE THREAD

**Issue by faustbrian** [bitcoinj/bitcoinj#1624]
I am currently working on a project where I am making use of the Base58 class but came across an issue while trying to use `encodeChecked`.

I am using IntelliJ and while trying to call `Base58.encodeChecked()` I receive the error `Cannot resolve symbol 'encodeChecked'`.

Is this a known issue and is there a workaround for it? Tried a few different releases and none of them seem to export the `encodeChecked` method so that I could access it.

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Also, please on your post state the version of bitcoinj you're using. Thanks.
