### ISSUE TITLE
The address that is parsed from the private key is wrong

### ISSUE THREAD

**Issue by 401825317** [bitcoinj/bitcoinj#1626]
I use the testnet mode command line to generate the address,

Then export the.Txt file and copy the private key in the inside, such as the cQRZNxUmiX1aMuoVmzLVE4QAiwYCt1fjsytopudVqoYus6Yy8i1S 2018-07-27T09:31:50Z reserve=1 addr=2MwJRUgQYvDqRRb9HhDK49cY9bgjjVPmPTG hdkeypath=m/0'/0'/392'

Using DumpedPrivateKey dumpedPrivateKey = DumpedPrivateKey.fromBase58 (params, args[0]);

The address after execution is not 2MwJRUgQYvDqRRb9HhDK49cY9bgjjVPmPTG.

![image](https://user-images.githubusercontent.com/19526136/43498497-cd6d2812-9579-11e8-9045-a90f22878bd8.png)
![image](https://user-images.githubusercontent.com/19526136/43498503-d545c454-9579-11e8-91a4-bde42d811afe.png)
Excuse me, why is this?
@bumi @petertodd @gezero @ksedgwic @prusnak

**Comment by schildbach** [comment]
@401825317 Does this answer your question?

**Comment by qq592304796** [comment]
I also have the same problem
```
	NetworkParameters param = TestNet3Params.get();
        ECKey key = DumpedPrivateKey.fromBase58(param, privateKeyBase58).getKey();
        System.out.println(key.toAddress(param));
        Script p2sh = ScriptBuilder.createP2SHOutputScript(1, Arrays.asList(key));
        System.out.println(Address.fromP2SHScript(param, p2sh));
```
But the address obtained does not match the address of testnet.

**Comment by systemsplanet** [comment]
sonny, which addresses are you expecting to match?
can you provide a concrete example?

**Comment by qq592304796** [comment]
`bitcoin-cli dumpprivkey "myaddress"`
I get the private key to execute the following code
```
	NetworkParameters param = TestNet3Params.get();
        ECKey key = DumpedPrivateKey.fromBase58(param, privateKeyBase58).getKey();
        Script p2sh = ScriptBuilder.createP2SHOutputScript(1, Arrays.asList(key));
        System.out.println(Address.fromP2SHScript(param, p2sh));
```
But to get the address with "myaddress" does not match

**Comment by yanxinyue** [comment]
How to create a wallet according to the BIP44?  The generation rules is: m/44’/0’/0’/0.
but now I could only create a wallet according the  generation rules like this:M/0/0/0   .
What should I do?

**Comment by schildbach** [comment]
I'm closing this issue, as the original issue seems to have been solved. All others: please ask questions on the mailing list, thanks.
