### ISSUE TITLE
How to get the public key address for Input & Output transactions?

### ISSUE THREAD

**Issue by MaxHastings** [bitcoinj/bitcoinj#1627]
What is the appropriate way to get the public key address for input and output transactions? The getFromAddress() was removed from the TransactionInput class. The getAddressFromP2PKHScript() and getAddressFromP2SH() functions have been deprecated for the TransactionOutput class. Any help would be highly appreciated. Thanks!

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
