### ISSUE TITLE
Problem decoding a transaction.

### ISSUE THREAD

**Issue by allquantor** [bitcoinj/bitcoinj#1643]
Transactions are coming from the mempool.

**Result:**

```
  version 2
     INCOMPLETE: No inputs!
     out  [exception: Push of data element that is larger than remaining data]
     prps UNKNOWN
```

Examples

```02000000000101ab49b9f5da436465a7fa5c7dd532deb95e7b1e08c1854e2d3b3bb99b9c40f8a0010000001716001451f4089f5cf7fbcba5ed1f9deaf79a251252ff72feffffff024c717d010000000017a914c695362a4bfb6078df5d38f1d9b4d5a00fcd838687854431597200000017a914fe4b702bf62319c98ffdfa71e679d5baebd586a18702483045022100deceac21f819423657e10ea1ca1be07b6760442c6f283c3a2f3b5b98170368e8022068050cc9275f0f1f71779b6137f549af4d5be22f31bf943748b385d3ca7e90a1012103649be9f3b11c1983975e80243f502be147789a287413010d76e39aa90767068e14931500```

Webinterfaces like blockcypher or the bitcoin cli can encode it successfully.

Any ideas?

**Comment by natzei** [comment]
This is a coinbase transaction, isn't it?

**Comment by allquantor** [comment]
Nope, its a SEGWIT one. Here another example
```
02000000000102650aa13660d4bb0e633d98957e8931c43d9c527a82ffc448cbf47d5de2374d96000000001716001472e24c7675db9ab175696a9903db0b897491ec08feffffff650aa13660d4bb0e633d98957e8931c43d9c527a82ffc448cbf47d5de2374d9601000000171600143425632dfdccd79c5c6feb92c293be334566ffb2feffffff0240420f000000000017a9147b481684114e7da53e5514b69a16ed3978ea4c9b87372318000000000017a9142458dbea0dae1a9aaab610e042ba8d5dcd375fc58702473044022073da04f3695adb61bdb9227dfdf78923de3aa0cd2f8796ed5ea52cafbac2fbc3022047c960cfadc722316819d3a53cd6146dad340bcfbd68bf350830bdb57c51681f01210322672b3ff5e59d743d6c844b2ebc841b91c448ba04e6f792f7405424f76ec5d002473044022063f3f189608d72cc1b937a8209e0d5daa208a7904acf5b39c559dfe3f65e073802205b14fe8c4c2e4687d00b1b1211ceaf92b5d6a08d6cf6e8a2ae624cb3b82c36080121031ebd5a884beb30015f673eb73cce4c99d784ced71b3d1e3756129b0f0f32e1af19931500
```
you can check under
_blockcypher.com/btc/decodetx/_
or
_chainquery.com/bitcoin-api/decoderawtransaction_

**Comment by natzei** [comment]
Can you please provide a txid?

**Comment by schildbach** [comment]
And @allquantor please post such questions on the mailing list.

**Comment by allquantor** [comment]
@schildbach why a deserialisation issue should be discussed on the mailing list and not here? I found out that the `serializer` at the current state does not support SEGWIT transactions, IMO this should at least be reflected in the documentation.

For anyone else having this problem, you can avoid the SEGWIT like payload by adding the `-rpcserialversion=0` flag in `btc-core`.
