### ISSUE TITLE
怎样使用bitcoinj进行转账

### ISSUE THREAD

**Issue by sywyn** [bitcoinj/bitcoinj#1650]
我想调用 btc.com  api 进行离线转账操作，
https://chain.api.btc.com/v3/address/3PyuXGoGexFhQa6MJU1DKy8GQBVURXmmxP/unspent

{
   "tx_hash": "8a82ad00d83b62f019f35717831e73cac1f3f7e85fad1cf513890626500efcf0",
   "tx_output_n": 0,
   "tx_output_n2": 0,
   "value": 20801498,
  "confirmations": 22812
}

{
    tx_hash: string 未花费的交易哈希
    tx_output_n: int 未花费在交易输出中的纵向排序*
    tx_output_n2: int 未花费在交易输出中的横向排序*
    value: int 未花费金额
    confirmations: int 确认数
}

我现在有 地址的私钥，公钥，哪么如何使用bitcoinj的库进行交易生成并签名?

大神帮忙帮忙博云见日下，我不尽感激!

**Comment by mozaboy** [comment]
解决了吗？我也遇到了同样的问题

**Comment by berryjam** [comment]
一个简单应用开发示例：https://berryjam.gitbook.io/mastering-bitcoin-3rd/di-san-zhang-.-bitcoin-core-can-kao-shi-xian/jian-dan-de-ying-yong-kai-fa-shi-yong-bitcoinj-ke-hu-duan-jian-ting-zhuan-zhang-he-fa-qi-zhuan-zhang
