### ISSUE TITLE
How to prevent from persisting private keys 

### ISSUE THREAD

**Issue by stasbar** [bitcoinj/bitcoinj#1651]
Hello,
I'm creating the physical wallet (similar to Ledger Nano S), and I want to store private key in my own way. I don't want the BitcoinJ to store the private key in .wallet file. Is there some way to configure the library so it keep the private key in-memory and lost it after the session ? I would like to restore/import the private key after some process of authorization (button, pin, 2FA etc.). 

Or maybe should I take use of `wallet().encrypt()` and `wallet().encrypt()` is it safer ?

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
