### ISSUE TITLE
How to get a block's height?

### ISSUE THREAD

**Issue by SeanHai** [bitcoinj/bitcoinj#1653]
I want to parse all the blockchain data(blkxxx.dat) to get some key fields use bitcoinj. 

I use "BlockFileLoader" to read the raw file and get the "Block" object, then use the getter function to get the fields. but there have no field "block height".

So I want to know how to get the block height......

thanks!

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
