### ISSUE TITLE
Where do I request transactions for specific keys?

### ISSUE THREAD

**Issue by younhajo88** [bitcoinj/bitcoinj#1655]
![zzz](https://user-images.githubusercontent.com/39249723/47345896-de961500-d6e6-11e8-96fa-be8df0d1b3af.png)

'Transaction' I confirmed that I received 'Transaction' of 'changeKey' which is currently owned by 'FilteredBlock' in the above image.

I want to receive 'Transactions' of all 'ReceiveKey' and 'ChangeKey'. What should I do?
Where do I make transaction requests for my specific keys?

**Comment by schildbach** [comment]
Please ask questions on the mailing list. Thanks.
