### ISSUE TITLE
Testnet transaction decode problem

### ISSUE THREAD

**Issue by anatolykhelmer** [bitcoinj/bitcoinj#1656]
Hi,
this is HEX of the transaction I'm trying to decode:
`02000000000101ef4c1c3c60028b050a5798265c0b37719418dd71b0621e76a68a47d5d9eef55f000000001716001467d7c32c0dad98bf8dd3dea81cbb1dbd4ea4afb5feffffff02b7df02000000000017a914ebb55a85454dc15589b8a87bab4b438892b54c0c87b0ad0100000000001976a914140b85a1c430c8f4fd1f91ae1c7451902b8ce76c88ac024730440220359623836f97e9e4c04917455ed2f9fb2343b0bf96853d47313b0c96d828c889022046da37bfda03cf3481e3ef5c5b5e655d6fd280c2aec2831b6494a8207b76655b01210224c44e1af98b5c28ebf822b65e4a2872d0780b4b6935b3100f60d3ac3b78cb00b2f81500`

When I go to the blockcipher https://live.blockcypher.com/btc/decodetx/ and decode the transaction there - it's decoded no problem. But when I'm trying to do this:
`Transaction tx = new Transaction(params, HexUtils.hexToBytes(txHex));`
`LOGGER.info("Transaction to spend (OBJ): " + tx.toString());`
        `String fromAddress = "mhLwcTEoquZcAjT34fD4uPySUAdK77uqvL";`
        `String toAddress = "mixfLUpeo2Unc9sHQJ77mYQLiyMdyfo6tB";`
it prints 
`4c67f1e1b10b063210e59400466383fb18634c05430d4f53795a16216dd34ffd
  version 2
     INCOMPLETE: No inputs!
     out  [exception: Push of data element that is larger than remaining data]
     prps UNKNOWN`

Please, help!

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? And please always add what version of bitcoinj you're using. Thanks.

**Comment by schildbach** [comment]
The mailing list is here: https://groups.google.com/forum/#!forum/bitcoinj
You asked for support. This tracker is for specific work items and pull requests (code contributions).
Please cross check your code against master and see if it's a problem there.

**Comment by anatolykhelmer** [comment]
I tried to post a message at the forum you specified (https://groups.google.com/forum/#!forum/bitcoinj), but my post was deleted!

**Comment by anatolykhelmer** [comment]
Also, I checked my code against master and it worded like a charm!
  65b47da760fb781a80e8607e19c82454f12c4ee8dd699045d4e96c869e07bf25
  version 2
  time locked until block 1439922
     in   PUSHDATA(22)[001467d7c32c0dad98bf8dd3dea81cbb1dbd4ea4afb5]
          witness:30440220359623836f97e9e4c04917455ed2f9fb2343b0bf96853d47313b0c96d828c889022046da37bfda03cf3481e3ef5c5b5e655d6fd280c2aec2831b6494a8207b76655b01 0224c44e1af98b5c28ebf822b65e4a2872d0780b4b6935b3100f60d3ac3b78cb00
          outpoint:5ff5eed9d5478aa6761e62b071dd189471370b5c2698570a058b02603c1c4cef:0
          sequence:fffffffe
     out  HASH160 PUSHDATA(20)[ebb55a85454dc15589b8a87bab4b438892b54c0c] EQUAL 0.00188343 BTC
          P2SH addr:2NEjY32rnrCdi8Cve6yJ4RaPanugBnJ8fme
     out  DUP HASH160 PUSHDATA(20)[140b85a1c430c8f4fd1f91ae1c7451902b8ce76c] EQUALVERIFY CHECKSIG 0.0011 BTC
          P2PKH addr:mhLwcTEoquZcAjT34fD4uPySUAdK77uqvL
     prps UNKNOWN
