### ISSUE TITLE
ECKeyTest.java character encoding breaks the test

### ISSUE THREAD

**Issue by systemsplanet** [bitcoinj/bitcoinj#1660]
[ECKeyTest.java](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/test/java/org/bitcoinj/core/ECKeyTest.java)

This test fails under windows due to special character set 
```
 @Test
    public void signTextMessage() throws Exception {
        ECKey key = new ECKey();
        String message = "聡中本";
```

fix is to add these lines to [build.gradle](https://github.com/bitcoinj/bitcoinj/blob/master/core/build.gradle)
```
compileJava.options.encoding = 'UTF-8' 
compileTestJava.options.encoding = 'UTF-8'
javadoc.options.encoding = 'UTF-8'
```

**Comment by schildbach** [comment]
Thanks for spotting this! I just fixed it via 2992cc16ff2ccd0c42b68469e90d0cc38a1e54d9.

I've omitted your JavaDoc encoding line because it doesn't have an effect for me. Maybe if you think it's useful can you submit a PR for that?
