### ISSUE TITLE
Unable to resolve dependencies by gradle

### ISSUE THREAD

**Issue by adiaholic** [bitcoinj/bitcoinj#1663]
![capture](https://user-images.githubusercontent.com/28735558/48196238-fe306d00-e377-11e8-8255-363573fe32eb.PNG)
And
> Execution failed for task ':core:generateProto'.

**Comment by adiaholic** [comment]
Any help would be appreciated

**Comment by adiaholic** [comment]
Any help would be appreciated

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.

**Comment by adiaholic** [comment]
I tried using the kiwi IRC channels but seems like they are not being used .
Is there any other chat line I could follow ?
