### ISSUE TITLE
calling toString() in a non-HD watch-only wallet throws NPE

### ISSUE THREAD

**Issue by Ykid** [bitcoinj/bitcoinj#1664]
versions
```
scala 2.12.6
java 1.8
bitcoinj: "0.14.7"
```

debug program
```scala
import org.bitcoinj.core.ECKey
import org.bitcoinj.crypto.{DeterministicHierarchy, DeterministicKey, HDUtils}
import org.bitcoinj.params.RegTestParams
import org.bitcoinj.wallet.Wallet
import scala.collection.JavaConverters._

object BugProgram extends App {
  val netParams = RegTestParams.get()
  val pubKeyBase58 = "tpubD6NzVbkrYhZ4XD1J4TAbgtG681BAsszKoUPNYNF5xTsk5JHRWBkPkFzbjak5Gh8oSpMGwVqB8ugSZHVyacVXBo6U8pvL6QuNWrntESScqzP"
  val hierarchy = new DeterministicHierarchy(DeterministicKey.deserializeB58(pubKeyBase58, netParams))
  val pubKeys = 1 to 5 map { i =>
    val path = s"M / $i"
    ECKey.fromPublicOnly(hierarchy.get(HDUtils.parsePath(path), true, true).getPubKeyPoint)
  }
  println(Wallet.fromKeys(netParams, pubKeys.asJava).toString)
}
```

stacktrace
```
Exception in thread "main" java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
	at org.bitcoinj.wallet.KeyChainGroup.upgradeToDeterministic(KeyChainGroup.java:724)
	at org.bitcoinj.wallet.Wallet.upgradeToDeterministic(Wallet.java:551)
	at org.bitcoinj.wallet.Wallet.maybeUpgradeToHD(Wallet.java:581)
	at org.bitcoinj.wallet.Wallet.maybeUpgradeToHD(Wallet.java:572)
	at org.bitcoinj.wallet.Wallet.isWatching(Wallet.java:826)
	at org.bitcoinj.wallet.Wallet.toString(Wallet.java:3197)
	at org.bitcoinj.wallet.Wallet.toString(Wallet.java:3164)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
        ......
```

a watch-only should not has SecretBytes, maybe checking is too strict

**Comment by schildbach** [comment]
Interesting. Looks like the combination of watching wallet and non-HD hasn't been tested well. We need to prevent the HD upgrade in this case – it can't work.

What are you trying to archive? Seems like you could use `Wallet wallet = Wallet.fromWatchingKeyB58(netParams, pubKeyBase58, 0 /* creationTimeSeconds */);` and you're done?

**Comment by Ykid** [comment]
Basically for the following two reasons:

I want to store the secret information(pubKeyBase58) somewhere and rebuild the wallet every time the application restarts but this seems to be not possible as it is also written into the file. (Maybe AES is the way to go to achieve a similar level of security)

I want to add some information to each address that is handed out but there seems to be no easy way to do it. ( Maybe walletExtension is the way to go ? )

At the moment I plan to manually manage the addresses and recreate the wallet every time the application starts. It seems to be the most secure way to operate a wallet and recover easily under exceptions. If you have better suggestions, I am more than happy to know :) thanks !

**Comment by schildbach** [comment]
The implicit upgrade to HD was removed via eb15ac07d356af74216c86f969eb7f48cc032045. I believe this should fix your issue.
