### ISSUE TITLE
How to override  getAccountPath() DeterministicKeyChain, use WalletAppKit

### ISSUE THREAD

**Issue by J-Ibarra** [bitcoinj/bitcoinj#1692]
Hello, I need some help!

I need change the account path in WalletAppKit restore from seed, the default path its  
M/0H/0 = 0 issued + 100
M/0H/1 = 0 issued + 100

but I need

 M/44H/0H/0H/0 = 0 issued + 100
 M/44H/0H/0H/1 = 0 issued + 100

i the code I see this 
<img width="553" alt="image" src="https://user-images.githubusercontent.com/4218738/52064473-19f87900-254b-11e9-81a2-1a0654adef2c.png">

but I not know how to override the method! 

the code of the test its:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/4218738/52064713-8a9f9580-254b-11e9-8803-3361afbe5a5a.png">

and the logs of path:

<img width="883" alt="image" src="https://user-images.githubusercontent.com/4218738/52064930-f255e080-254b-11e9-8698-a1ad2fa4406d.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/4218738/52064966-013c9300-254c-11e9-9542-ec1d9d5f16b4.png">

**Comment by schildbach** [comment]
On current master (which will be released very soon), you can provide an account path (or an entire structure) when creating a Wallet/KeyChainGroup/DeterministicKeyChain. I suggest trying that.

Can you ask questions on the mailing list? Thanks.

**Comment by LouisWayne** [comment]
@schildbach Is there any example code?
