### ISSUE TITLE
not apply spendable balance received by Bech32 address

### ISSUE THREAD

**Issue by nayuta-ueno** [bitcoinj/bitcoinj#1693]
commit: e3e4e3f32a186a71babb42b0faff504d366b0c70

I send bitcoin to `SegwitAddress.fromKey(params, key).toBech32()` address and watch `Wallet.getBalance()`.

* `getBalance(AVAILABLE)` and `getBalance(ESTIMATED)` returns amount.
* `getBalance(AVAILABLE_SPENDABLE)` and `getBalance(ESTIMATED_SPENDABLE)` return 0.

----
(testnet)
```
WalletAppKit wak = new WalletAppKit(...);
...
ECKey key = wak.wallet().currentReceiveKey();
System.out.println("address=" + SegwitAddress.fromKey(params,key).toBech32());

while (...) {
   ...
  System.out.println("balance1=" + wak.wallet().getBalance(Wallet.BalanceType.AVAILABLE).getValue());
  System.out.println("balance2=" + wak.wallet().getBalance(Wallet.BalanceType.AVAILABLE_SPENDABLE).getValue());
  ...
}
```

from command line

```
bitcoin-cli sendtoaddress (Bech32 address) AMOUNT
```

and wait some confirmation.

* Wallet.BalanceType.AVAILABLE : apply AMOUNT
* Wallet.BalanceType.AVAILABLE_SPENDABLE : always 0

**Comment by schildbach** [comment]
What branch/commit id have you been testing this on? Did your example connect to the P2P network to actually receive the transaction?

**Comment by nayuta-ueno** [comment]
branch : master
commit : e3e4e3f32a186a71babb42b0faff504d366b0c70

> Did your example connect to the P2P network to actually receive the transaction?
Maybe, yes.
It's OK : SegwitAddress.fromKey(params, key).toBech32() --> LegacyAddress.fromKey(params, key).toBase58().

My sending transaction is native segwit, so `scriptSig` length = 0 (signature is in witness).
Do bitcoinj check witness ?

**Comment by schildbach** [comment]
The master branch doesn't yet support _receiving_ of segwit transactions. Only _sending to_ segwit addresses.

Please use and test https://github.com/bitcoinj/bitcoinj/pull/1563

**Comment by nayuta-ueno** [comment]
Thank you!

**Comment by nayuta-ueno** [comment]
I test bitcoinj v0.15, but cannot receive coin to bech32 address.
https://github.com/bitcoinj/bitcoinj/releases/tag/v0.15

Is bitcoinj v0.15 support receiving of segwit transactions ?

**Comment by schildbach** [comment]
Yes, support for receiving has been merged to master some weeks ago.

Can you post a Wallet.toString() of your wallet, and an excerpt of the log (ideally the part while synching the blocks containing your test transaction)?

**Comment by nayuta-ueno** [comment]
I send from bitcoind to bitcoinj.

* bitcoinj address: tb1qx0vmgnj7q4qngcgv0nlqd4klrkupmxpwdkl2u5
* Transaction: [7772f2c1d00b779c80f6687b7b7773b0d853eaf3636fa7c46294d79d73154705](https://testnet.smartbit.com.au/tx/7772f2c1d00b779c80f6687b7b7773b0d853eaf3636fa7c46294d79d73154705)
  * vout=0 (0.1mBTC)

log
* PeerGroup.addBlocksDownloadedEventListener()
  * log: `[CB]BlocksDownloaded:`
* PeerGroup.addOnTransactionBroadcastListener()
  * log: `[CB]TransactionBroadcast:`
* Wallet.addCoinsReceivedEventListener()
  * log: `[CB]CoinsReceived:`
* Wallet.addTransactionConfidenceEventListener()
  * log: `[CB]TransactionConfidence:`
* Wallet.addChangeEventListener()
  * log: `[CB]WalletChange:`

```
(new wallet)

========== Wallet.toString() before send ==========

wallet: Wallet
Balances:
  0.00 BTC ESTIMATED
  0.00 BTC AVAILABLE
  0.00 BTC ESTIMATED_SPENDABLE
  0.00 BTC AVAILABLE_SPENDABLE
Transactions:
  0 pending
  0 unspent
  0 spent
  0 dead
Last seen best block: 1482620 (2019-03-02T00:18:02Z): 00000000000000615ccb42b90db0b9a8d47ecfb254c8fdddfbda472c6132401a

Keys:
Earliest creation time: 2019-03-02T00:18:45Z
Seed birthday:     1551485925  [2019-03-02T00:18:45Z]
Ouput script type: P2PKH
Key to watch:      tpubD9KZpBxQqC3ngorXmKhKQC3G8djC2U2DPcGDJFvpZB3Dpc1YQgui1eCf8bMyEyM8Mx5NPTdAuZSU3LR899i7V9VRSBGNFxjUugJww9x8JZv
Lookahead siz/thr: 100/33
  addr:mteymxcp4EAqkjGRUN3HGCepfP8VJmj6c6  hash160:901e33036d1cbf7e40b19e4bc4f46bfb130995b5  (M, root)
  addr:mgtdNgmnUZNNRq5npH5n6n3aXtmn6TvGgk  hash160:0f117bb3f86594311538d8a73d0c726718747af1  (M/0H, account)
  addr:mgkiYviNpKAoEJZYm2TLcjyhfVscSJ7eSF  hash160:0d927a08978a31029cc5fbcaed2526a9631d5a0f  (M/0H/0, external)
  addr:msrJbXbvioSvQwpB3Lpz2rUwjDbKMhDGgg  hash160:874a5bfd82e43e845c7619316c6dc20940dcc3dc  (M/0H/1, internal)
  addr:mkF7ZCUtsFVYCoYiF9bBKfQz9BSXMvcwfm  hash160:33d9b44e5e054134610c7cfe06d6df1db81d982e  (M/0H/0/0)



========= send from bitcoind =========

  [CB]TransactionBroadcast: -> 7772f2c1d00b779c80f6687b7b7773b0d853eaf3636fa7c46294d79d73154705



========= 1 confirm =========

  [CB]WalletChange: -> 0.00 BTC
  [CB]BlocksDownloaded: 000000000000004f4f0f3d1b26d8f80b7e51240ec07c550822254acbae84ad47-> left:0



========== Wallet.toString() after 1 confirm ==========

wallet: Wallet
Balances:
  0.00 BTC ESTIMATED
  0.00 BTC AVAILABLE
  0.00 BTC ESTIMATED_SPENDABLE
  0.00 BTC AVAILABLE_SPENDABLE
Transactions:
  0 pending
  0 unspent
  0 spent
  0 dead
Last seen best block: 1482621 (2019-03-02T00:21:44Z): 000000000000004f4f0f3d1b26d8f80b7e51240ec07c550822254acbae84ad47

Keys:
Earliest creation time: 2019-03-02T00:18:45Z
Seed birthday:     1551485925  [2019-03-02T00:18:45Z]
Ouput script type: P2PKH
Key to watch:      tpubD9KZpBxQqC3ngorXmKhKQC3G8djC2U2DPcGDJFvpZB3Dpc1YQgui1eCf8bMyEyM8Mx5NPTdAuZSU3LR899i7V9VRSBGNFxjUugJww9x8JZv
Lookahead siz/thr: 100/33
  addr:mteymxcp4EAqkjGRUN3HGCepfP8VJmj6c6  hash160:901e33036d1cbf7e40b19e4bc4f46bfb130995b5  (M, root)
  addr:mgtdNgmnUZNNRq5npH5n6n3aXtmn6TvGgk  hash160:0f117bb3f86594311538d8a73d0c726718747af1  (M/0H, account)
  addr:mgkiYviNpKAoEJZYm2TLcjyhfVscSJ7eSF  hash160:0d927a08978a31029cc5fbcaed2526a9631d5a0f  (M/0H/0, external)
  addr:msrJbXbvioSvQwpB3Lpz2rUwjDbKMhDGgg  hash160:874a5bfd82e43e845c7619316c6dc20940dcc3dc  (M/0H/1, internal)
  addr:mkF7ZCUtsFVYCoYiF9bBKfQz9BSXMvcwfm  hash160:33d9b44e5e054134610c7cfe06d6df1db81d982e  (M/0H/0/0)
  addr:mrSzodCszHZZxwotSzTCHkvLkgoMTf8ks6  hash160:77e9d09c791262c2ce3ebb53fac54099ed204bcb  (M/0H/0/1)



========= some confirm... =========

  [CB]WalletChange: -> 0.00 BTC
  [CB]BlocksDownloaded: 000000000000015d42e365bc1e7dd46fc90dc858fcc7599c79b07e87ccddc53f-> left:0
  [CB]WalletChange: -> 0.00 BTC
  [CB]BlocksDownloaded: 00000000000000db750567134715c828341749af6b9da2f4b6cb7001725699e8-> left:0
  [CB]WalletChange: -> 0.00 BTC
  [CB]BlocksDownloaded: 0000000000000158871e0f684fbcb2e3b2577c4dd9556940f6070a05994fea21-> left:0



========== Wallet.toString() after some confirm ==========

wallet: Wallet
Balances:
  0.00 BTC ESTIMATED
  0.00 BTC AVAILABLE
  0.00 BTC ESTIMATED_SPENDABLE
  0.00 BTC AVAILABLE_SPENDABLE
Transactions:
  0 pending
  0 unspent
  0 spent
  0 dead
Last seen best block: 1482624 (2019-03-02T00:36:32Z): 0000000000000158871e0f684fbcb2e3b2577c4dd9556940f6070a05994fea21

Keys:
Earliest creation time: 2019-03-02T00:18:45Z
Seed birthday:     1551485925  [2019-03-02T00:18:45Z]
Ouput script type: P2PKH
Key to watch:      tpubD9KZpBxQqC3ngorXmKhKQC3G8djC2U2DPcGDJFvpZB3Dpc1YQgui1eCf8bMyEyM8Mx5NPTdAuZSU3LR899i7V9VRSBGNFxjUugJww9x8JZv
Lookahead siz/thr: 100/33
  addr:mteymxcp4EAqkjGRUN3HGCepfP8VJmj6c6  hash160:901e33036d1cbf7e40b19e4bc4f46bfb130995b5  (M, root)
  addr:mgtdNgmnUZNNRq5npH5n6n3aXtmn6TvGgk  hash160:0f117bb3f86594311538d8a73d0c726718747af1  (M/0H, account)
  addr:mgkiYviNpKAoEJZYm2TLcjyhfVscSJ7eSF  hash160:0d927a08978a31029cc5fbcaed2526a9631d5a0f  (M/0H/0, external)
  addr:msrJbXbvioSvQwpB3Lpz2rUwjDbKMhDGgg  hash160:874a5bfd82e43e845c7619316c6dc20940dcc3dc  (M/0H/1, internal)
  addr:mkF7ZCUtsFVYCoYiF9bBKfQz9BSXMvcwfm  hash160:33d9b44e5e054134610c7cfe06d6df1db81d982e  (M/0H/0/0)
  addr:mrSzodCszHZZxwotSzTCHkvLkgoMTf8ks6  hash160:77e9d09c791262c2ce3ebb53fac54099ed204bcb  (M/0H/0/1)
```

**Comment by schildbach** [comment]
You're sending to a P2WPKH (native segwit) address, but the keychain in your wallet is a P2PKH chain (it has only P2PKH addresses). Why are you assuming your transaction will arrive? Where did you get the P2WPKH address from? Did you somehow convert the address manually?

**Comment by nayuta-ueno** [comment]
Please show first.
I get address below:

```
WalletAppKit wak = new WalletAppKit(...);
...
ECKey key = wak.wallet().currentReceiveKey();
System.out.println("address=" + SegwitAddress.fromKey(params,key).toBech32());
```

**Comment by nayuta-ueno** [comment]
I create wallet like this.

```
NetworkParameters params = NetworkParameters.fromPmtProtocolID("test");
WalletAppKit wak = new WalletAppKit(params, new File("./wallet"), "wa")
```

Is this for P2PKH chain?

**Comment by schildbach** [comment]
> Please show first.
> I get address below:
> 
> ECKey key = wak.wallet().currentReceiveKey();
> System.out.println("address=" + SegwitAddress.fromKey(params,key).toBech32());

Rather than getting a key and converting it to an address yourself, please use

`wak.wallet().currentReceiveAddress()`

WalletAppKit has new constructors that let you specify the script type. You seem to want to use Script.ScriptType.P2WPKH at this point.

I'm closing this now. If you have further questions, can you please post to the mailing list?
