### ISSUE TITLE
Getting a bitcoin transaction's status?

### ISSUE THREAD

**Issue by mpd518** [bitcoinj/bitcoinj#1703]
How to get a bitcoin transaction's status (like how many confirmations happened)? Is this possible through bitcoinj? If not, is there any suggested approaches to do this? Thank you.

mpd

**Comment by oscarguindzberg** [comment]
Please, have a look at TransactionConfidence.getDepthInBlocks() and
TransactionConfidenceEventListener


On Mon, Feb 18, 2019 at 5:39 AM mpd518 <notifications@github.com> wrote:
>
> How to get a bitcoin transaction's status (like how many confirmations happened)? Is this possible through bitcoinj? If not, is there any suggested approaches to do this? Thank you.
>
> mpd
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Oscar Guindzberg

**Comment by oscarguindzberg** [comment]
You can use https://groups.google.com/forum/#!forum/bitcoinj for questions
