### ISSUE TITLE
Bech32 class can't be used outside of `org.bitcoinj.core` package

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1710]
The `Bech32` class provides general purpose Bech32 encoding and decoding that could be used for encoding/decoding things other than Bech32 addresses (e.g. TxRefs.) Unfortunately the `hrp` and `data` fields of `Bech32Data` are package visibility and can't be used outside the `org.bitcoinj.core` package.

Possible solutions:
* Make `public`
* Make `protected`
* Add `public` or `protected` getters

**Comment by schildbach** [comment]
Since they're final, we could simply make them public.

However, can you provide a code example for this TxRef usecase? Is this usecase already established?

**Comment by msgilligan** [comment]
> However, can you provide a code example for this TxRef usecase?

My work-in-progress commit for an implementation of the draft W3C Bitcoin Reference Decentralized Identifier is here: https://github.com/ConsensusJ/consensusj/commit/0c9a249a120c7e3ccd171de4a5abb77835528f9e

A Spock test that passes (because Groovy uses introspection to access the private fields) is here:
https://github.com/ConsensusJ/consensusj/blob/0c9a249a120c7e3ccd171de4a5abb77835528f9e/consensusj-decentralized-id/src/test/groovy/org/consensusj/decentralizedid/btcr/ExtendedTxRefSpec.groovy

> Is this usecase already established?

[BIP 173](https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki#specification) says "We first describe the general checksummed base32 format called Bech32 and then define Segregated Witness addresses using it." 

Bech32.java mostly implements the "general checksummed base32 format" but does not allow classes outside `org.bitcoinj.core` to access the parsed human readable part and data.

It seems to be the intention of the Bitcoin community to use Bech32 for more than just Segregated Witness addresses. Here are a few (early stage) use cases that I'm aware of:

1. [Bech32 Encoded Tx Position References](https://github.com/veleslavs/bips/blob/txrev_v2/bip-0136.mediawiki) (draft BIP)
2. Encoded Tx Position References are [used in W3C BTCR](https://w3c-ccg.github.io/didm-btcr/#txref) (Bitcoin Reference) DIDs (Decentralized Identifiers)
3. [SLIP-0173 : Registered human-readable parts for BIP-0173](https://github.com/satoshilabs/slips/blob/master/slip-0173.md) -- using Bech32 addresses for other coin types.

**Comment by schildbach** [comment]
Thanks for your detailed explanation. I just made the fields accessible via 1d4c8e69ebb6b122f0af61694d8cb25696449c2a.

**Comment by msgilligan** [comment]
Thanks for accepting my change!
