### ISSUE TITLE
SNAPSHOT (CI) builds of pre-release bitcoinj 

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1712]
It would be helpful to downstream projects and would also improve testing and bug reporting prior to release if there were SNAPSHOT builds of bitcoinj available for pre-release testing with these projects. Ideally these builds would be made by Continuous Integration (CI) (we are currently using Travis CI)

Obviously we'd want to make very clear to people that these pre-release builds should not be used with real keys/coins.

**Comment by msgilligan** [comment]
I'm using bitcoinj in [ConsensusJ](https://github.com/ConsensusJ/consensusj) and wanted to experiment with the `release-0.15` branch. Last night I successfully ran CI builds (on both Travis CI and Gitlab CI) for a WIP branch of ConsensusJ using bitcoinj built by [Jitpack](https://jitpack.io).

To do this I had to configure the Gradle Protocol Buffers plugin in bitcoinj to install `protoc` (I didn't see an option to install packages in Jitpack like you can in Travis, etc)  (See https://github.com/msgilligan/bitcoinj/commit/faa32f14deaded12ef9ca2ca1adac6f7070d7d77)

And here are the changes I had to make to ConsensusJ to use Jitpack: https://github.com/ConsensusJ/consensusj/commit/e8d739d3d7701c687270d80cd872a4997c508dde

**Comment by schildbach** [comment]
Jitpack seems to be the latest trend; year maybe we should make sure bitcoinj is compatible out of the box.

And yes, I also would like to see snapshot builds. I'm tagging this "wishlist item" for 0.16, but if someone wants to tackle it for 0.15 even better.

**Comment by schildbach** [comment]
I implemented your protoc suggestion in 12fc118c82727a999305343bd8f8a7b652a11831.

**Comment by msgilligan** [comment]
Cool! I think that's all we need to do to support Jitpack. I'll update my downstream repo and see if I can pull it directly from this Github repo.

**Comment by msgilligan** [comment]
So, this change https://github.com/ConsensusJ/consensusj/compare/e8d739d3d770...2d834a29dc0e pulls directly from [bitcoinj/bitcoinj](https://github.com/bitcoinj/bitcoinj) and [works](https://travis-ci.org/ConsensusJ/consensusj/builds/497614407)!

**Comment by msgilligan** [comment]
OK PR #1716 adds  a little section to the README about how to use the Jitpack builds.

**Comment by schildbach** [comment]
Looks like this is complete now.
