### ISSUE TITLE
Upgrade JavaFX wallettemplate to require JDK 11+

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1713]
It would be nice to be able to build the JavaFX components of bitcoinj with CI. In [a comment](https://github.com/bitcoinj/bitcoinj/pull/1709#discussion_r259294706) @schildbach says "there is no reliable way to declare the JavaFX dependency."

One possibility: Require a minimum of Java 11 for the JavaFX module and use OpenJFX which can be downloaded from Maven Central and should work with other Oracle JDK or Open JDK. (See [Run HelloWorld using Gradle](https://openjfx.io/openjfx-docs/#gradle).)

As the JavaFX `wallettemplate` isn't widely used (I think) and (in my opinion) the best way to deliver JavaFX apps is with a bundled JVM, it may be acceptable to require (what is currently) the latest JDK.

If there's agreement on this approach, I can try to make a PR for `wallettemplate` that requires JDK 11 and pulls the OpenJFX from Maven Central.

**Comment by schildbach** [comment]
So would that JDK 11 build on wallet-template then run in addition to what we have already? I'd certainly not want to drop JDK 8 for building in the near future.

Generally I think wallet-template in CI has not much benefit since the "wallet usecase" is already covered by wallet-tool (which _is_ under CI). This is why I excluded it quite lightheartedly when the OpenJFX dependency became a problem.

**Comment by msgilligan** [comment]
> So would that JDK 11 build on wallet-template then run in addition to what we have already?

Yes, `wallet-template` would only build on JDK 11 and later -- or at least that's my idea. Here's my first attempt at doing that: https://github.com/msgilligan/bitcoinj/commit/58e83d4b57d1af2bf1bb421df5ecd85e0973dc68

>  I'd certainly not want to drop JDK 8 for building in the near future.

I totally agree. In fact,I'm thinking about opening an issue/PR to try to get the CI builds to use JDK 7 for part of the build so we can be sure to find any accidental usages of JDK 8 features.

**Comment by msgilligan** [comment]
OK, PR #1715 is ready for your review.

**Comment by msgilligan** [comment]
PR #1715 is now (indirectly) merged. Closing.
