### ISSUE TITLE
how to change testnet bech32 public key hash to testnet public key hash?

### ISSUE THREAD

**Issue by rendezvous** [bitcoinj/bitcoinj#1714]
In the wallettemplate project, a testnet bech32 public key hash address is displayed as the wallet address. However, I'm having trouble locating transactions made with that address in the blockchain, because the explorers don't accept it.  
How can I display the testnet public key hash instead? I tried changing the preffered_output_script_type from P2WPKH to P2PKH, but that doesn't change anything. I also tried to change the call to WalletAppKit to a simpler constructor: `WalletAppKit(NetworkParameters params, File directory, String filePrefix)` , but that doesn't work too.

Another thing I'm trying to implement is displaying the sender's address in the transaction list for the incoming transactions, but all the info I read about how to do it, refers to `TransactionInput.getFromAddress() `, which doesn't exist in the current version and `getConnectedOutput().getAddressFromP2PKHScript()` appears as deprecated, so I don't know what's the right way to get the sender's address from a transaction, but my guess is that it has to do with the SegWit addresses being used now, but I would like someone to explain if that's my issue.

**Comment by schildbach** [comment]
Please ask questions on the mailing list. To change Wallet-template back to using P2PKH addresses, change the script type in `Main.PREFERRED_OUTPUT_SCRIPT_TYPE`.
