### ISSUE TITLE
Video Tutorials are down

### ISSUE THREAD

**Issue by nitro-neal** [bitcoinj/bitcoinj#1721]
The videos have been removed from youtube, is there a mirror or a timeline of when these will be back?

https://bitcoinj.github.io/document-timestamp-app
https://bitcoinj.github.io/simple-gui-wallet

**Comment by schildbach** [comment]
Yes, that's a known issue. The creator unintentionally took them down when he cancelled an account. I don't know if there are any mirrors; let me know if you find out.

In any case, the videos are likely outdated anyways. I'll probably remove the 'bitcoinj TV' section.

**Comment by schildbach** [comment]
I've removed the embedded videos. Unfortunately there is nothing more I can do right now.
