### ISSUE TITLE
Why same test in AddressTest 

### ISSUE THREAD

**Issue by show-rosarugosa** [bitcoinj/bitcoinj#1722]
In core/src/test/java/org/bitcoinj/core/LegacyAddressTest.java, I find comparisonCloneEqualTo() same as comparisonEqualTo().
I want to know why this is done.
If just a negligence， I can submit PR to delete it.

**Comment by schildbach** [comment]
Good spot, seems like a mistake. Feel free to submit a PR!

**Comment by show-rosarugosa** [comment]
Ok, I have submitted a PR recently.
