### ISSUE TITLE
Transaction failure

### ISSUE THREAD

**Issue by liuyongyi0110** [bitcoinj/bitcoinj#1723]
I added a long time equal to the current timestamp under locktime of the Transaction class. At the same time, it adds (uint32ToByteStreamLE (time, stream); time = readUint32 ();). But at the end of the transaction, the readByte method in Message, System. arraycopy (payload, cursor, b, 0, length); array subscripts cross the bounds. Where should I change the byte length?

我在Transaction类的locktime下面加了一个long time等于当前时间戳。同时在交易类中增加了（uint32ToByteStreamLE(time, stream); time = readUint32();）。但是最后交易的时候Message里面的readByte的方法 System.arraycopy(payload, cursor, b, 0, length); 数组下标越界。请问我应该在哪修改字节长度

**Comment by liuyongyi0110** [comment]
11

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.
