### ISSUE TITLE
hashForSignature return double hash for rawTx

### ISSUE THREAD

**Issue by NabilNoaman** [bitcoinj/bitcoinj#1729]
Hi ,

First thanks for great library.
I am building my custom signer to sign tx externally using non-deterministic key , I noticed that hashForSignature() return double hash for my transaction.

For example i am expecting this has : 94082E578891406A71BE463986F42C1E44912D681C8C8D04ED9B1957D30A0FF4
While calculated hash is : 
550a4d989f9eb285fd6a5c515304a54466e59cc7cc1073db024dd0eda6caa3fb
which is SHA256 for my expected value.

I tried to build tx manually and already published on network and verified based on signature calculated from my hash while signature verification if used hash calculated by library.

Is there any reason behind using Sha256Hash.twiceOf() in hashForSignature instead of   Sha256Hash.of() ?

Thanks
Nabil

**Comment by schildbach** [comment]
Yes, signature hashes (segwit or legacy) are double-sha256'ed. See https://en.bitcoin.it/wiki/OP_CHECKSIG#Final_signature_check

In future, please ask quesions on the mailing list. Thanks.
