### ISSUE TITLE
Very important issue here

### ISSUE THREAD

**Issue by KinJoonho** [bitcoinj/bitcoinj#1737]
Did you try to restore wallet from seed?

This is a very serious problem.

I know it is right to write on mailng list.

Even if block synchronization done, the wallet lost chlid path  and the balance remains at zero.

**Comment by gabrielgbs97** [comment]
Hi, I was unable to restore a wallet from mnemonic seed too, neither importing dumped keys in base58. My code was copied/inspirated from java examples folder.

**Comment by schildbach** [comment]
The thing is either you've got a question on how to use bitcoinj then the mailing list is the right place to post.

Or you've got a bug and want to report it, then this is the right place. But "Very important issue here" is not a bug report. Please show some code that reproduces the issue, ideally in the form of a (failing) unit test. Use a meaningful issue title and description.

**Comment by KinJoonho** [comment]
Thanks to reply.
I've solved issue using by this way (https://groups.google.com/forum/#!topic/bitcoinj/To3fGOlWSvs)
