### ISSUE TITLE
Can i create litecoin address using this bitcoinj

### ISSUE THREAD

**Issue by simplewhale** [bitcoinj/bitcoinj#1739]
I want to generate some litecoin addresses ,but,I don't know where to add the address prefix.

**Comment by simplewhale** [comment]
I want to generate them offline

**Comment by schildbach** [comment]
Bitcoinj only supports Bitcoin. For litecoin, there is a fork of bitcoinj called litecoinj.

**Comment by artall64** [comment]
I would say it's better to have a configurable modular structure. And for Such things to have some dependency like https://github.com/NovaCrypto/BIP44

**Comment by msgilligan** [comment]
> I would say it's better to have a configurable modular structure

@artall64 I have been doing some work in the BIP44 area and @schildbach is in the loop. There have been some merged PRs and I'm planning on a few more. See Issue #1869 .
