### ISSUE TITLE
 How do I create my own currency and which code do I need to modify?

### ISSUE THREAD

**Issue by show-rosarugosa** [bitcoinj/bitcoinj#1843]
I tried to modify the network parameters, but there was a problem with the connection. How should I try to create my own currency to learn to use.
[https://groups.google.com/forum/?hl=zh-cn#!topic/bitcoinj/WZ2ZgZMPBVU](url)

I changed the port to 8833, but the program does not work.

**Comment by show-rosarugosa** [comment]
Using RegTestParams in a wallet also rejects the connection.

**Comment by schildbach** [comment]
Please don't ask questions here. If no one replies on the mailing list then probably no one knows the answer.
