### ISSUE TITLE
ScriptChunk.toString() has exploding branch

### ISSUE THREAD

**Issue by matthewleon** [bitcoinj/bitcoinj#1860]
https://github.com/bitcoinj/bitcoinj/blob/cae0b385a40ec38807c1fd7d21939cc9d6d3e6c2/core/src/main/java/org/bitcoinj/script/ScriptChunk.java#L161

The branch in question will be reached on any `ScriptChunk` with an `opcode <= OP_PUSHDATA4` that also has a `null` `data` array.  Note that such a `ScriptChunk` is invalid, but because the constructor has no validation, it can still be constructed.

The branch has the comment "Small num", and uses `Script.decodeFromOpN`. The operations in `decodeFromOpN` are primarily meant for the `OP_`X opcodes, which are _greater_ than `OP_PUSHDATA4`.

As a consequence, pretty much any time we reach this branch, `toString()` will explode on the first line of `decodeFromOpN`, which performs on opcode validity check.

As `toString()` is itself often used as a debugging tool, it's probably not the right place to explode on an invalid `ScriptChunk`.

**Comment by schildbach** [comment]
Agreed. `toString()` should better not throw.

**Comment by schildbach** [comment]
#1861 merged.
