### ISSUE TITLE
External link(s) in JavaDoc not working

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1870]
I found at least one external link in the JavaDoc -- the **BIP 32 standard** hyperlink in the first main paragraph of the [DeterministicKeyChain](https://bitcoinj.github.io/javadoc/0.15.2/index.html?org/bitcoinj/wallet/DeterministicKeyChain.html) page -- that fails to load with the following error in Chrome:

```
about:blank:1 Refused to display 'https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

The problem is related to Content Security Policy in *frames mode* and the link works correctly when the containing page is viewed as a standalone page.

It is failing in both Chrome 74.0.3729.16 an Safari 12.1 on macOS 10.14.4.

**Comment by schildbach** [comment]
Indeed, this fails under Firefox too.

**Comment by msgilligan** [comment]
One solution to this might be to build the official release of the  javadoc with JDK 11 and set the `html5` option. I could make a PR to conditionally apply the `html5` option when available (I did this in **ConsensusJ**.) One nice thing about the html5 option is that it also adds a (client-side) search option.

**Comment by schildbach** [comment]
I think that sounds like a good solution. Feel free to PR.

**Comment by msgilligan** [comment]
Actually, I started working on a PR and found that no changes to Gradle config were needed, if we just build the javadocs with JDK11 we'll get HTML5.

**Comment by msgilligan** [comment]
This should be fixed now that we're building with JDK 11 and publishing HTML5 JavaDoc

**Comment by schildbach** [comment]
Note that JDK 11 is not yet the requirement for building. If we want to go this step for 0.17, I think we should do so as early as possible in the cycle.

**Comment by msgilligan** [comment]
My main concern in this issue is that we didn't want broken links in our _published_ JavaDoc. For this purpose we are concerned with the JDK version used in the official build (which is now JDK 11) not the minimum JDK required for a build.

But I do agree that the update to require JDK 11 for the build should be made early in the 0.17 cycle.
