### ISSUE TITLE
:bitcoinj-core:javadoc | „ECKey.java:994: error: unmappable character (0x9D) for encoding windows-1252“

### ISSUE THREAD

**Issue by lingocoder** [bitcoinj/bitcoinj#1871]
--------------------
    gradle -version

    ------------------------------------------------------------
    Gradle 5.2.1
    ------------------------------------------------------------
    
    Build time:   2019-02-08 19:00:10 UTC
    Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183
    
    Kotlin DSL:   1.1.3
    Kotlin:       1.3.20
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
    JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
    OS:           Windows 7 6.1 amd64

--------------------

## Steps To Reproduce

1. Download bitcoinj-master.zip from Code page, unzip  and cd to install dir
2. `gradle clean assemble`

## Expected Behavior

BUILD SUCCESSFUL

## Actual Behavior
 
    Including wallettemplate because Gradle 5.2.1 and Java 11
    
    > Task :bitcoinj-core:compileJava
    Note: Some input files use or override a deprecated API.
    Note: Recompile with -Xlint:deprecation for details.
    Note: Some input files use unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.
    
    > Task :bitcoinj-core:javadoc
    L:\bitcoinj-master\core\src\main\java\org\bitcoinj\core\ECKey.java:994: error: unmappable character (0x9D) for encoding windows-1252
            //        conversion routine specified in Section 2.3.4. If this conversion routine outputs ÔÇ£invalidÔÇ?, then
    
                                                                                                                   ^
    1 error

    > Task :bitcoinj-core:javadoc FAILED

    > Task :bitcoinj-examples:compileJava
    Note: L:\bitcoinj-master\examples\src\main\java\org\bitcoinj\examples\FetchBlock.java uses unchecked or unsafe operations.
    Note: Recompile with -Xlint:unchecked for details.

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':bitcoinj-core:javadoc'.
    > Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): 'L:\bitcoinj-master\core\build\tmp\javadoc\javadoc.options'

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    Run with --scan to get full insights.

    * Get more help at https://help.gradle.org

    Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
    Use '--warning-mode all' to show the individual deprecation warnings.
    See https://docs.gradle.org/5.2.1/userguide/command_line_interface.html#sec:command_line_warnings

    BUILD FAILED in 7m 5s
    13 actionable tasks: 13 executed

**Comment by schildbach** [comment]
Thanks for catching this! Fixed via 05ab09b40be7f4e752ec066c4813c7aa2ef168c3.
