### ISSUE TITLE
Problem when build Android App Bundle

### ISSUE THREAD

**Issue by vtproduction** [bitcoinj/bitcoinj#1900]
When I build normal APK file, it worked, but when I tried to build Android App Bundle, the compiler throw error:

`File 'root/lib/x86_64/darwin/libscrypt.dylib' uses reserved file or directory name 'lib'.`

This lib was used by Bitcoinj, so anyone can help? Thanks!

**Comment by schildbach** [comment]
Try to exclude the file from your package like this:

```
packagingOptions {
    exclude 'lib/x86_64/darwin/libscrypt.dylib'
}
```

Or use bitcoinj from the master branch – there is no native scrypt code any more.

**Comment by vtproduction** [comment]
thank you, I will try!
