### ISSUE TITLE
Fail to determine input address type P2PKH

### ISSUE THREAD

**Issue by ospavel** [bitcoinj/bitcoinj#1916]
Transaction: 6b5b1197f03e7ea55f5c01053ca2ef45f58d7b6bb12d28c5a203fa3bb44e795a from December 2015 has type P2PKH
(https://btc.com/6b5b1197f03e7ea55f5c01053ca2ef45f58d7b6bb12d28c5a203fa3bb44e795a)

The code 
transaction.getInputs().get(0).getScriptSig().getScriptType() 
returns null

**Comment by schildbach** [comment]
Yes, the `Script.getScriptType()` method is meant for output scripts. I'm not sure if it's possible to determine script type for input scripts in all cases. But we probably should improve the documentation.

**Comment by ospavel** [comment]
Ok.
But is it possible to get info about input address from a transaction?

That transaction's raw input data consists of 
pubkey 02ac8f34bebc1a5f7c2ecc68840c5d3ac27d6a0ead84094b0307d94e32fab875cc
r 5b6bcbb2c3f63b4ed5c4245938cee88d0c3ffcd88a82606ade88bb7a698488ea
s 77883499c2928d04875215c96d8a6c1189f20dd027fa3e621e2e26d6d44e94e3

Is it possible to get this data by the library?

**Comment by schildbach** [comment]
I suggest to post this question on the mailing list.
