### ISSUE TITLE
Prefix subprojects with bitcoinj-

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1918]
Rename `core`, `examples`, and `tools` directories to `bitcoinj-core`, `bitcoinj-examples`, and `bitcoinj-tools` respectively so the directory names match the subproject names.

This will also make them appear next to each other in directory listings and IDE views which generally default to alphabetic order.

@schildbach If you agree and assign to me, I'll make a PR.

**Comment by schildbach** [comment]
We decided not to prefix the subdirs because e.g. `bitcoinj/bitcoinj-core/` is redundant. It will only lead to command line completion to be less "snappy".

I don't understand the IDE part. IDEs should pick up the project names. At least Eclipse does.

**Comment by msgilligan** [comment]
I guess there's a tradeoff between redundancy in the full filesystem path and the mismatch between directory name and project name. Personally I prefer that the subprojects all sort together in directory listings and my preferred IDE view. As for command-line completion, having the `bitcoinj-` prefix allows autocomplete to work for commands like:

    gradle bitcoinj-core:test

IntelliJ does pick up the correct project name, but it doesn't sort by it in my preferred view, which looks like this:

![IntelliJ_bitcoinj](https://user-images.githubusercontent.com/61612/62719170-44286900-b9bc-11e9-9ce3-81876dcadaf4.png)

**Comment by schildbach** [comment]
Just for clarification: the documentation is a sub-project too, so it would need to be renamed as well. So nothing would change regarding the sorting.

**Comment by schildbach** [comment]
fyi https://github.com/bitcoinj/bitcoinj/pull/1922 would remove the misc folder.
