### ISSUE TITLE
PrivateKeys sendCoins Error

### ISSUE THREAD

**Issue by syuukawa** [bitcoinj/bitcoinj#1920]
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.PeerGroup$9 run
Claiming 7.77 BTC
INFO: Stopping ...
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.PeerGroup setDownloadPeer
INFO: Unsetting download peer: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.17.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2019-08-08 14:32:26, height=267}
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet completeTx
INFO: Completing send tx with 1 outputs totalling 0.10 BTC and a fee of 0.001 BTC/vkB
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.PeerGroup$9 run
INFO: Stopped, took 4.521 ms.
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.DeterministicKeyChain maybeLookAhead
INFO: 1 keys needed for M/0H/1 = 1 issued + 0 lookahead size + 0 lookahead threshold - 0 num children
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.DeterministicKeyChain maybeLookAhead
INFO: Took 1.022 ms
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet completeTx
INFO:   with 7.669773 BTC change
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet completeTx
INFO:   completed: Transaction{c84218b12beee8e19e73b96895261dfa8f3b2197b6a6957ab44039b4039bc961
weight: 900 wu, 225 bytes
purpose: USER_PAYMENT
   in   PUSHDATA(71)[304402207064d8d56e07c0006059b93bb0b1d10f24ffaed19c08f6e13c1b583cf53ea7d002205da890eb32815f6f86c8b149f82b45c4db04d57d9f27681780930e48148b4bb701] PUSHDATA(33)[031e0a60af65c17c31598bf48686958ef2ec29709a6b650ff725fe9b4f625a142a]  7.77 BTC
        P2PKH addr:mqWesEVvbq1r2sD7VfCY46mjnM7Whg2yBA  outpoint:8d960933b4724284be7f90bd42912f807b780b70f978ba7616c7f924bc39b63c:1
   out  DUP HASH160 PUSHDATA(20)[6da2b5b0a8990a9f6f352e9dc60b5b6b0f7060bb] EQUALVERIFY CHECKSIG  0.10 BTC
        P2PKH addr:mqWesEVvbq1r2sD7VfCY46mjnM7Whg2yBA
   out  DUP HASH160 PUSHDATA(20)[b9e600784be7550ff5e9062b10c971c2b2911db0] EQUALVERIFY CHECKSIG  7.669773 BTC
        P2PKH addr:mxTtqMGpaPg844Z1JsihgHWyQqi9tohZC7
   fee  0.00025222 BTC/wu, 0.00100888 BTC/kB  0.000227 BTC
}
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet maybeCommitTx
INFO: commitTx of c84218b12beee8e19e73b96895261dfa8f3b2197b6a6957ab44039b4039bc961
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet updateForSpends
INFO:   marked 8d960933b4724284be7f90bd42912f807b780b70f978ba7616c7f924bc39b63c:1 as spent by c84218b12beee8e19e73b96895261dfa8f3b2197b6a6957ab44039b4039bc961
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet maybeMovePool
INFO:   8d960933b4724284be7f90bd42912f807b780b70f978ba7616c7f924bc39b63c prevtx <-unspent ->spent
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet maybeCommitTx
INFO: ->pending: c84218b12beee8e19e73b96895261dfa8f3b2197b6a6957ab44039b4039bc961
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.Wallet maybeCommitTx
INFO: Estimated balance is now: 7.769773 BTC
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.KeyChainGroup maybeMarkCurrentKeyAsUsed
INFO: Marking key as used: DeterministicKey{pub=02aced87bb6f2a0077b481c4e1b5928545bf502baa1ceebff8494d7fb0a765cd3a, chainCode=cafb3324bd2d531d9b0e76c3b0c92bf1628a5e6021fc5d9bb37f78a6ff271807, path=M/0H/1/0, creationTimeSeconds=1565245945 (inherited), isEncrypted=false, isPubKeyOnly=false}
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.DeterministicKeyChain maybeLookAhead
INFO: 1 keys needed for M/0H/1 = 2 issued + 0 lookahead size + 0 lookahead threshold - 1 num children
Aug 08, 2019 2:32:26 PM org.bitcoinj.wallet.DeterministicKeyChain maybeLookAhead
INFO: Took 596.5 μs
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.TransactionBroadcast broadcast
INFO: Waiting for 1 peers required for broadcast, we have 1 ...
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.TransactionBroadcast$EnoughAvailablePeers run
INFO: broadcastTransaction: We have 1 peers, adding c84218b12beee8e19e73b96895261dfa8f3b2197b6a6957ab44039b4039bc961 to the memory pool
Aug 08, 2019 2:32:26 PM org.bitcoinj.core.TransactionBroadcast$EnoughAvailablePeers run
INFO: Sending to 1 peers, will wait for 0, sending to: Peer{[127.0.0.1]:18444, version=70015, subVer=/Satoshi:0.17.1/, services=1037 (NETWORK, BLOOM, WITNESS, NETWORK_LIMITED), time=2019-08-08 14:32:26, height=267}
Aug 08, 2019 2:32:26 PM org.bitcoinj.net.ConnectionHandler writeBytes
WARNING: Error writing message to connection, closing connection
java.nio.channels.CancelledKeyException
	at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
	at sun.nio.ch.SelectionKeyImpl.interestOps(SelectionKeyImpl.java:77)
	at org.bitcoinj.net.ConnectionHandler.setWriteOps(ConnectionHandler.java:106)
	at org.bitcoinj.net.ConnectionHandler.writeBytes(ConnectionHandler.java:152)
	at org.bitcoinj.core.PeerSocketHandler.sendMessage(PeerSocketHandler.java:92)
	at org.bitcoinj.core.TransactionBroadcast$EnoughAvailablePeers.run(TransactionBroadcast.java:159)
	at org.bitcoinj.utils.Threading$2.execute(Threading.java:139)
	at com.google.common.util.concurrent.ImmediateFuture.addListener(ImmediateFuture.java:39)
	at org.bitcoinj.core.TransactionBroadcast.broadcast(TransactionBroadcast.java:114)
	at org.bitcoinj.core.PeerGroup.broadcastTransaction(PeerGroup.java:2084)
	at org.bitcoinj.core.PeerGroup.broadcastTransaction(PeerGroup.java:2021)
	at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:4100)
	at org.bitcoinj.wallet.Wallet.sendCoins(Wallet.java:4059)
	at org.bitcoinj.examples.PrivateKeys.main(PrivateKeys.java:79)

Aug 08, 2019 2:32:26 PM org.bitcoinj.core.PeerSocketHandler exceptionCaught
INFO: [127.0.0.1]:18444 - java.nio.channels.CancelledKeyException

**Comment by schildbach** [comment]
The CancelledKeyException is just a warning. It is caused by some I/O error talking to the peer.

**Comment by syuukawa** [comment]
I know you means,But How Can i solve the problem .And let the Sencoin transaction successfully;

**Comment by syuukawa** [comment]
> The CancelledKeyException is just a warning. It is caused by some I/O error talking to the peer.

I know you means,But How Can i solve the problem .And let the Sencoin transaction successfully;

**Comment by schildbach** [comment]
You need to find out the cause of the I/O error. In most cases this is a network problem. Have a look at the log file of your bitcoind too, it might contain relevant information.

**Comment by syuukawa** [comment]
> You need to find out the cause of the I/O error. In most cases this is a network problem. Have a look at the log file of your bitcoind too, it might contain relevant information.

I donot think so ; 
One : I used the local evn ; 
Two : **Claiming 7.77 BTC** may tell me that the network is ready . 
Three : i am so confused with the PrivateKeys Method can not be run successfully;  
Four ; I try to find the error by browser ; But i can not find the answer ;
If there ; i can not find the answer;So  i do not know Where i can ;
Thanks you so much;

**Comment by syuukawa** [comment]
> You need to find out the cause of the I/O error. In most cases this is a network problem. Have a look at the log file of your bitcoind too, it might contain relevant information.

The SendRequest Method Can be run successfully ; in the same env;

**Comment by syuukawa** [comment]
> You need to find out the cause of the I/O error. In most cases this is a network problem. Have a look at the log file of your bitcoind too, it might contain relevant information.

Maybe i have found the reason ：
--- peerGroup.stopAsync();

1: origin source :
peerGroup.stopAsync();
wallet.sendCoins(peerGroup, destination, wallet.getBalance());

Before the sendCoins ,The peerGroup is stoped; And the CancelledKeyException is throw out;

2: Mod source:
wallet.sendCoins(peerGroup, destination, wallet.getBalance());
peerGroup.stopAsync();

the sendCoins run successfully；

i am not very well with bitcoinj ; if it is the problem; And proved. Please let me know. Thank you

**Comment by schildbach** [comment]
Hmm yes, that example should probably be rewritten to properly handle the asynchronity. Current is simply invokes `Thread.sleep(5000);` at the end, which introduces a race condition.

**Comment by schildbach** [comment]
I pushed a quick fix to the master branch. It doesn't rewrite the example, but makes sure to stop the PeerGroup not before sending the transaction.

Can you try again?

**Comment by syuukawa** [comment]
PrivateKeys.java is the test file  I have moded;

I used the regtest Env;

The  log-sendcoin is about running the privateKeys methods ;
The log-Getbalance is about after the sendCoin transaction; And check if the sendCoin is successful;







On Aug 9, 2019, at 5:32 PM, Andreas Schildbach <notifications@github.com<mailto:notifications@github.com>> wrote:


I pushed a quick fix to the master branch. It doesn't rewrite the example, but makes sure to stop the PeerGroup not before sending the transaction.

Can you try again?

**Comment by syuukawa** [comment]
> I pushed a quick fix to the master branch. It doesn't rewrite the example, but makes sure to stop the PeerGroup not before sending the transaction.
> 
> Can you try again?

PrivateKeys.java is the test file;

I used the regtest Env;

The  log-sendcoin is about running the privateKeys methods ;
The log-Getbalance is about after the sendCoin transaction; 
And check if the sendCoin is successful;

The file you can find it here:
https://github.com/syuukawa/bitcoinj/tree/master/examples/src/main/test
