### ISSUE TITLE
Convert OP script to Hex

### ISSUE THREAD

**Issue by mmo2112** [bitcoinj/bitcoinj#1929]
Hi there, I have a script like that:
```
Script script = ScriptBuilder.createOutputScript(Address.fromString(network, address));
UP HASH160 PUSHDATA(20)[afc36eef306b2eb01ac4a88c77c0127d4211196a] EQUALVERIFY CHECKSIG
```
And I wanna convert from OP to Hex `76a914afc36eef306b2eb01ac4a88c77c0127d4211196a88ac`. Is there anyway to convert it? I have searched on latest release but can't find any related function for that, or I have missed something important... Thanks for help so much and have a nice day.

**Comment by schildbach** [comment]
Did you look at `Script.getProgram()`? It'll get you the bytes, and from there you can convert to hex using Guava or whatever you like.
