### ISSUE TITLE
Support BouncyCastle 1.64 

### ISSUE THREAD

**Issue by lfeagan** [bitcoinj/bitcoinj#1951]
When using bitcoinj with BouncyCastle 1.64, errors occur because of bitcoinj using deprecated methods, such as `org.bouncycastle.math.ec.ECPoint.isCompressed()`, which has been replaced with `public byte[] getEncoded(boolean compressed)`. I see someone had a TODO about tracking compression in `org.bitcoinj.core.ECKey`. I have some cycles and am happy to help if you accept PRs.

**Comment by schildbach** [comment]
Thanks for your offer! I believe this has already been implemented on master via 7629677103dbdd80f14c63b066ed27e1fad47014.

**Comment by benwaffle** [comment]
is there a plan to backport this to 0.15?

**Comment by schildbach** [comment]
Is there a specific reason for this? The change was kind of intrusive, so I'd prefer to run it though good testing.

**Comment by xellDart** [comment]
Hi I get this error java.lang.NoSuchMethodError: 'boolean org.bouncycastle.math.ec.ECPoint.isCompressed()'

This is my pom 
<dependency>
            <groupId>org.bitcoinj</groupId>
            <artifactId>bitcoinj-core</artifactId>
            <version>0.15.7</version>
            <scope>compile</scope>
        </dependency>

**Comment by haorenlin** [comment]
DumpedPrivateKey dumpedPrivateKey = DumpedPrivateKey.fromBase58(BitConfig.params(), privateKey);
ECKey key = dumpedPrivateKey.getKey();
出现：
org.bouncycastle.math.ec.ECPoint.isCompressed

> org.bitcoinj bitcoinj-core 0.15.8

**Comment by laalaguer** [comment]
I think use 0.14.7 will solve the problem "for now".

but 0.15.x isn't working still.

**Comment by dlecan** [comment]
So what is the solution when 0.15.x series is mandatory for us and this bugfix is missing from it?

**Comment by schildbach** [comment]
Again, is there a specific reason you want to update to later BouncyCastle versions?

**Comment by dlecan** [comment]
> Again, is there a specific reason you want to update to later BouncyCastle versions?

In the same webapp, another dependency (out of our control) requires at least BouncyCastle 1.65.

**Comment by schildbach** [comment]
fyi: I backported the changes to 0.15.10, just released.
