### ISSUE TITLE
the balance is  0  when  restore the new wallet from seed

### ISSUE THREAD

**Issue by yuzhongrong** [bitcoinj/bitcoinj#1952]
//from seed
    public static WalletAppKit getWalletKit(String seedcode, AbstractWalletLiveData.DownloadAsynLister downloadAsynLister) {

        WalletAppKit walletAppKit = new WalletAppKit(Constants.NETWORK_PARAMETERS, new File(BaseApp.getContext().getFilesDir().getPath()), "CMC_WALLET") {
            @SuppressLint("CheckResult")
            @Override
            protected void onSetupCompleted() {

                if (wallet().getImportedKeys().size() < 1) {
                    wallet().importKey(new ECKey());
                }
//                wallet().allowSpendingUnconfirmedTransactions();
                BitUtil.INSTANCE.setupWalletListeners(wallet());
                ECKey ecKey = wallet().getImportedKeys().get(0);

//                test2(ecKey);
//                //print seed
                List<String> seedWordsFromWallet = BitUtil.INSTANCE.getSeedWordsFromWallet(wallet());
                Logger.e("-------seedWordsFromWallet---->" + JsonUtil.toJson(seedWordsFromWallet));

            }
        };

        walletAppKit.setAutoSave(true);
        walletAppKit.setBlockingStartup(false);

        if (downloadAsynLister != null)
            BitUtil.INSTANCE.setDownListener(walletAppKit, downloadAsynLister);

        if (!TextUtils.isEmpty(seedcode)) {
            try {
                Logger.e("-------seedcode111--->" + seedcode);
                // Logger.e("-------getKeyChainSeed-hex--seedcode->"+walletAppKit.wallet().getKeyChainSeed().toHexString());
                //seed=助记词+盐（）
                DeterministicSeed seed = new DeterministicSeed(seedcode, null, "", Utils.currentTimeSeconds());
                walletAppKit.restoreWalletFromSeed(seed);
            } catch (UnreadableWalletException e) {
                e.printStackTrace();
            }
        }

        try {

            byte[] addr = IpV4Util.ipToBytes(Constants.NETWORK_PARAMETERS.getId());
            walletAppKit.setPeerNodes(new PeerAddress(Constants.NETWORK_PARAMETERS, InetAddress.getByAddress(addr), Constants.NETWORK_PARAMETERS.getPort()));
        } catch (UnknownHostException e) {
            e.printStackTrace();
        }

        walletAppKit.startAsync().awaitRunning();
        Logger.e("-------walletAppKit.state()--->" + walletAppKit.state());

        return walletAppKit;
    }

**Comment by yuzhongrong** [comment]
The new wallet has a lot of coins, but now the balance is 0 after recovery

**Comment by yuzhongrong** [comment]
i user the method to restore:


  public void restoreWallet(String seed){
        //stop sync
        if(walletAppKit!=null){ walletAppKit.stopAsync().awaitTerminated();}
        Flowable.just(seed)
                .observeOn(Schedulers.io())
                .map(s -> Kit.getWalletKit(s,null))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(walletAppKit -> {
                    this.walletAppKit=walletAppKit;
                    wallet=walletAppKit.wallet();

                    notifyAllWalletRestore(wallet);
                });


    }

**Comment by schildbach** [comment]
Can you post the Wallet.toString() of your wallet? It will contain the transaction history.

**Comment by yuzhongrong** [comment]
ok

**Comment by yuzhongrong** [comment]
Balances:
      0.123 BTC ESTIMATED
      0.123 BTC AVAILABLE
      0.123 BTC ESTIMATED_SPENDABLE
      0.123 BTC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      1 unspent
      0 spent
      0 dead
    Last seen best block: 13916 (2019-12-13T13:32:01Z): 0000000072610cd2444b5831bbdf464ef9710572da412a1a1bc91265834df78f
    
    Keys:
    Earliest creation time: 2019-12-13T13:42:19Z
      addr:mvNBm2jFEbqD4uqGYnE9LjTR9oiHmqX63e,tb1q5tskyx39pj65s69gkul6yc86pdneq6xtj8fnx5  hash160:a2e1621a250cb54868a8b73fa260fa0b679068cb  creationTimeSeconds:1576244539 [2019-12-13T13:42:19Z]  (imported)
    Seed birthday:     1576244539  [2019-12-13T13:42:19Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD8NVENRZdoraRmLsKVqj6kWd1ZHSRnrsd28BUScjYL7GscLjVVE9nZ58Q3q8AWiqktVWezHaADW41bA6mYUPzHxpE9wmQzEUwkEg9knqSSU
    Lookahead siz/thr: 100/33
      addr:mgsqVDWmc97VZnFCpoqRqTy2FaZyJxyWSC  hash160:0eeb2da71c1ac2bb451613e55bf7242f7f0cc314  (M, root)
      addr:n3RTUqBh6Thn874AwKXvDSi4LhgVwdb8ZH  hash160:f048a2730c3fdb8ddb9a49ad7e6333221db5842b  (M/0H, account)
      addr:mw9Aeaws7sFBkL7TaZz4TKJgmXb8VmXMSp  hash160:ab632c8a14c767b967c465b5488651ad6b8eb907  (M/0H/0, external)
      addr:mr56kp1uqSaaBtVEdS36273eyJSS77yjuc  hash160:73c5a1bc6f10f9de26b5f40249a34b146d230ce9  (M/0H/1, internal)
      addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS  hash160:7efdc23ae64c33936b76f12d1bc3e73b755478ea  (M/0H/0/0)
      addr:mzSVE7xoJWQohBz5gc2iEqP4aLj4DNdanv  hash160:cf922187614e3689388438b63e9d86992705ca68  (M/0H/0/1)
    
    
    >>> UNSPENT:
    0.123 BTC total value (sends 0.00 BTC and receives 0.123 BTC)
      confidence: Appeared in best chain at height 13460, depth 457. Source: NETWORK
      3442c7aba28dba383d1cc46efb61f0c7f15bba06bd2e5ade4bc847f9a954093b
      weight: 900 wu, 225 bytes
      updated: 2019-12-08T19:18:18Z
      time locked until block 13459
      purpose: UNKNOWN
         in   PUSHDATA(71)[3044022032097525a4ec7e8f852c3b4f6c4a5cf2ea173e653731d4c7420e0b133762a460022057d3b970cd8b1435a95fc24608d48770faccf7af72db263ffc7a7f6cfc22b46a01] PUSHDATA(33)[02f110cb9418728c92d75203a7ed1f4cfa8be8e85c0dcd3d4b580d5f626fecf8af]
              unconnected  outpoint:c72369dd4bd6e3523cc9057e3c8ee6a81990718cff5afe8820482ba1afee62e0:1
              sequence:fffffffe
         out  DUP HASH160 PUSHDATA(20)[7efdc23ae64c33936b76f12d1bc3e73b755478ea] EQUALVERIFY CHECKSIG  0.123 BTC
              P2PKH addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS
         out  DUP HASH160 PUSHDATA(20)[b53e8dc4be2616dd6e8d02a175f96e49723fae08] EQUALVERIFY CHECKSIG  655.8769166 BTC
              P2PKH addr:mx3HY65b3Wn256uDY3AjzWuMz1nzUCZyUV

**Comment by yuzhongrong** [comment]
this is the wallet info look

**Comment by yuzhongrong** [comment]
My wallet is more than just a little bit of money now that the money is gone

**Comment by yuzhongrong** [comment]
DUP HASH160 PUSHDATA(20)[b53e8dc4be2616dd6e8d02a175f96e49723fae08] EQUALVERIFY CHECKSIG  655.8769166 BTC
          P2PKH addr:mx3HY65b3Wn256uDY3AjzWuMz1nzUCZyUV       this balance should be included in my wallet

**Comment by yuzhongrong** [comment]
The specific data should be more than 600+ coins

**Comment by yuzhongrong** [comment]
is 655.8769166 BTC+0.123BTC

**Comment by yuzhongrong** [comment]
but now only have 0.123btc

**Comment by yuzhongrong** [comment]
I found that the transaction history is cleared from time to time. I do n’t know what happened.

**Comment by schildbach** [comment]
> DUP HASH160 PUSHDATA(20)[b53e8dc4be2616dd6e8d02a175f96e49723fae08] EQUALVERIFY CHECKSIG 655.8769166 BTC
> P2PKH addr:mx3HY65b3Wn256uDY3AjzWuMz1nzUCZyUV this balance should be included in my wallet

The address `mx3HY65b3Wn256uDY3AjzWuMz1nzUCZyUV` is not part of your wallet, according to the wallet dump you posted. That's why it's not in your wallet.

**Comment by yuzhongrong** [comment]
In other words, I transferred this out？

**Comment by schildbach** [comment]
From what we can see from your wallet dump, someone sent 0.123 Testnet-BTC into your wallet, keeping the remaining change for him/herself. If this seems weird to you, we suggest reading:

https://en.bitcoin.it/wiki/Transaction#Output

**Comment by yuzhongrong** [comment]
I understand that this 0.123 is transferred to me, and the 600+ is the change address of others

**Comment by schildbach** [comment]
Yes, that's correct.

**Comment by yuzhongrong** [comment]
ok  I now know why the amount is small.

**Comment by yuzhongrong** [comment]
Wallet transaction records will be deleted after the past 9 days and the amount will be reduced.

**Comment by yuzhongrong** [comment]
???

**Comment by yuzhongrong** [comment]
come on

**Comment by phanduytunglinh** [comment]
@yuzhongrong 
Do you have this issue recently?
