### ISSUE TITLE
Why the balance is not 655.8769166 +0.123

### ISSUE THREAD

**Issue by yuzhongrong** [bitcoinj/bitcoinj#1953]
Balances:
      0.123 BTC ESTIMATED
      0.123 BTC AVAILABLE
      0.123 BTC ESTIMATED_SPENDABLE
      0.123 BTC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      1 unspent
      0 spent
      0 dead
    Last seen best block: 13913 (2019-12-13T12:20:40Z): 000000007c665564da297be9022bac22bf7bd8e135cec3bac6bedd73424ddf37
    
    Keys:
    Earliest creation time: 2019-12-13T10:21:34Z
      addr:n29wjwaZsQ2uwTq1y8zCMUTov7yiRspaxy,tb1qufshrtl3sdw8yggsd07dxd9semyp6j59pxufnx  hash160:e26171aff1835c7221106bfcd334b0cec81d4a85  creationTimeSeconds:1576232495 [2019-12-13T10:21:35Z]  (imported)
    Seed birthday:     1576232494  [2019-12-13T10:21:34Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD8NVENRZdoraRmLsKVqj6kWd1ZHSRnrsd28BUScjYL7GscLjVVE9nZ58Q3q8AWiqktVWezHaADW41bA6mYUPzHxpE9wmQzEUwkEg9knqSSU
    Lookahead siz/thr: 100/33
      addr:mgsqVDWmc97VZnFCpoqRqTy2FaZyJxyWSC  hash160:0eeb2da71c1ac2bb451613e55bf7242f7f0cc314  (M, root)
      addr:n3RTUqBh6Thn874AwKXvDSi4LhgVwdb8ZH  hash160:f048a2730c3fdb8ddb9a49ad7e6333221db5842b  (M/0H, account)
      addr:mw9Aeaws7sFBkL7TaZz4TKJgmXb8VmXMSp  hash160:ab632c8a14c767b967c465b5488651ad6b8eb907  (M/0H/0, external)
      addr:mr56kp1uqSaaBtVEdS36273eyJSS77yjuc  hash160:73c5a1bc6f10f9de26b5f40249a34b146d230ce9  (M/0H/1, internal)
      addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS  hash160:7efdc23ae64c33936b76f12d1bc3e73b755478ea  (M/0H/0/0)
      addr:mzSVE7xoJWQohBz5gc2iEqP4aLj4DNdanv  hash160:cf922187614e3689388438b63e9d86992705ca68  (M/0H/0/1)
    
    
    >>> UNSPENT:
    0.123 BTC total value (sends 0.00 BTC and receives 0.123 BTC)
      confidence: Appeared in best chain at height 13460, depth 454. Source: NETWORK
      3442c7aba28dba383d1cc46efb61f0c7f15bba06bd2e5ade4bc847f9a954093b
      weight: 900 wu, 225 bytes
      updated: 2019-12-08T19:18:18Z
      time locked until block 13459
      purpose: UNKNOWN
         in   PUSHDATA(71)[3044022032097525a4ec7e8f852c3b4f6c4a5cf2ea173e653731d4c7420e0b133762a460022057d3b970cd8b1435a95fc24608d48770faccf7af72db263ffc7a7f6cfc22b46a01] PUSHDATA(33)[02f110cb9418728c92d75203a7ed1f4cfa8be8e85c0dcd3d4b580d5f626fecf8af]
              unconnected  outpoint:c72369dd4bd6e3523cc9057e3c8ee6a81990718cff5afe8820482ba1afee62e0:1
              sequence:fffffffe
         out  DUP HASH160 PUSHDATA(20)[7efdc23ae64c33936b76f12d1bc3e73b755478ea] EQUALVERIFY CHECKSIG  0.123 BTC
              P2PKH addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS
         out  DUP HASH160 PUSHDATA(20)[b53e8dc4be2616dd6e8d02a175f96e49723fae08] EQUALVERIFY CHECKSIG  655.8769166 BTC
              P2PKH addr:mx3HY65b3Wn256uDY3AjzWuMz1nzUCZyUV

**Comment by yuzhongrong** [comment]
Why is there an unconnected endpoint, is this the cause?

**Comment by schildbach** [comment]
It's unconnected because the parent transaction is not in your wallet (it's not relevant to your wallet).

Can you please ask questions on the mailing list? This issue tracker is meant for bug reports.

**Comment by yuzhongrong** [comment]
but  the balance is wrong

**Comment by schildbach** [comment]
You need to provide details. What transactions are missing?

**Comment by yuzhongrong** [comment]
yes
