### ISSUE TITLE
About a week later, the transaction history is cleared.

### ISSUE THREAD

**Issue by yuzhongrong** [bitcoinj/bitcoinj#1954]
About a week later, the transaction history is cleared.

**Comment by yuzhongrong** [comment]
A transaction record will disappear in 9 days, and the amount will also decrease.

**Comment by yuzhongrong** [comment]
A transaction record will disappear in 9 days, and the amount will also decrease.

**Comment by yuzhongrong** [comment]
12-17:statistical

 2019-12-17 18:16:59.571 7695-7878/cn.wildfirechat.imshat E/CJT: --------sync seccess------>address+balance==mm8CCHAGWP3a9i7peWVGh9SdJ2HpybFjF9  Wallet
    Balances:
      522.023 CMC ESTIMATED
      522.023 CMC AVAILABLE
      522.023 CMC ESTIMATED_SPENDABLE
      522.023 CMC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      6 unspent
      0 spent
      0 dead
    Last seen best block: 14267 (2019-12-17T10:16:46Z): 00000000bf2a24aaabb1805b91c9265bc97b4cec83e6ca06ce001655ecd96746
    
    Keys:
    Earliest creation time: 2019-12-15T07:52:33Z
      addr:mrRMNb4YdT8VcDjPQQ2tDqqUrMN4k6FEb8,tb1qw7dzwrxeyk7dt6pjkywsapj8hc3x865kcawjnz  hash160:779a270cd925bcd5e832b11d0e8647be2263ea96  creationTimeSeconds:1576396354 [2019-12-15T07:52:34Z]  (imported)
    Seed birthday:     1576396353  [2019-12-15T07:52:33Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD8NVENRZdoraRmLsKVqj6kWd1ZHSRnrsd28BUScjYL7GscLjVVE9nZ58Q3q8AWiqktVWezHaADW41bA6mYUPzHxpE9wmQzEUwkEg9knqSSU
    Lookahead siz/thr: 100/33
      addr:mgsqVDWmc97VZnFCpoqRqTy2FaZyJxyWSC  hash160:0eeb2da71c1ac2bb451613e55bf7242f7f0cc314  (M, root)
      addr:n3RTUqBh6Thn874AwKXvDSi4LhgVwdb8ZH  hash160:f048a2730c3fdb8ddb9a49ad7e6333221db5842b  (M/0H, account)
      addr:mw9Aeaws7sFBkL7TaZz4TKJgmXb8VmXMSp  hash160:ab632c8a14c767b967c465b5488651ad6b8eb907  (M/0H/0, external)
      addr:mr56kp1uqSaaBtVEdS36273eyJSS77yjuc  hash160:73c5a1bc6f10f9de26b5f40249a34b146d230ce9  (M/0H/1, internal)
      addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS  hash160:7efdc23ae64c33936b76f12d1bc3e73b755478ea  (M/0H/0/0)
      addr:mzSVE7xoJWQohBz5gc2iEqP4aLj4DNdanv  hash160:cf922187614e3689388438b63e9d86992705ca68  (M/0H/0/1)
      addr:n3qSTi3b2wn6B6To3TBB52sVJvaeqgHbYa  hash160:f4d1c448587f70b0e251b88cd9ee8a10dd10f3b0  (M/0H/0/2)
      addr:mqf1gprkSGavuYogB2seYNRKuxTqkyVs2y  hash160:6f376ae4705f710df24ad86990ba20f0b75293ab  (M/0H/0/3)
      addr:n1rvZ4rZX2xNj9YtLfXGE8uFwQk1oKKJSj  hash160:df2961a823405795f9a3d0878fd5f7548bef40c4  (M/0H/0/4)
      addr:mpxhWFVHMjpMPRLEiYoQ4Qe4AJw7NDhn3T  hash160:679799ea23779c61daeabf6a911ce405caaeabc4  (M/0H/0/5)
      addr:mywf3kWRnyeD8MfyrmgoXoRGm7FZrv69tW  hash160:ca1e443394e2694fb08075955dd79ac67d38b819  (M/0H/0/6)
      addr:miWHX6fcPpE1jjTkSu6juxwJ8r5Wj7ifik  hash160:20c80270aefeebc9eb0a795a9391088f07a1007f  (M/0H/0/7)
      addr:mm8CCHAGWP3a9i7peWVGh9SdJ2HpybFjF9  hash160:3d82ca8469306ec71538fcc8f97137976e0182ff  (M/0H/0/8)
    
    
    >>> UNSPENT:
    300.00 CMC total value (sends 0.00 CMC and receives 300.00 CMC)
      confidence: Seen by 1 peer (most recently: 2019-12-17T10:16:30Z). Appeared in best chain at height 14267, depth 1. Source: NETWORK
      600b834e4af95765ef1e4fe088a6a03c090e922ab5724270d67cac6aa14f6651
      weight: 900 wu, 225 bytes
      updated: 2019-12-17T10:10:34Z
      purpose: UNKNOWN
         in   PUSHDATA(71)[304402207e98c368436c4d39711dbf94fa899cecd560be6a33c25604e3bc71bb8a3665ef022022edd5b3778fa0def0bfcbae2ee763a70813c3cafa65242e7cd1abcdb5efea2901] PUSHDATA(33)[0339bf92d1d327689d664cd83b3399bc8933a740e4a93951623c12a68cffb447f2]  790.098865 CMC
              P2PKH addr:mpijwX9DUec1d9VAq4iuHvdTayn5sshgKi  outpoint:13d2689f900c5009fe3685a0137466fbb101e52f68f9688b1dece57d1c0f7641:0
         out  DUP HASH160 PUSHDATA(20)[7d7bf2f2937ee3e684944a664a3facaa282e6219] EQUALVERIFY CHECKSIG  490.0982975 CMC
              P2PKH addr:mrxTFAJqXTwwoDb2Ha4qJCmRrCaBMgumsv
         out  DUP HASH160 PUSHDATA(20)[20c80270aefeebc9eb0a795a9391088f07a1007f] EQUALVERIFY CHECKSIG  300.00 CMC
              P2PKH addr:miWHX6fcPpE1jjTkSu6juxwJ8r5Wj7ifik
         fee  0.00063055 CMC/wu, 0.00252222 CMC/kB  0.0005675 CMC
    159.00 CMC total value (sends 0.00 CMC and receives 159.00 CMC)
      confidence: Seen by 1 peer (most recently: 2019-12-17T04:00:56Z). Appeared in best chain at height 14248, depth 20. Source: NETWORK
      13d2689f900c5009fe3685a0137466fbb101e52f68f9688b1dece57d1c0f7641
      weight: 900 wu, 225 bytes
      updated: 2019-12-17T03:29:43Z
      purpose: UNKNOWN
         in   PUSHDATA(71)[304402201372161b2eaf90f045ce7d8501d990c00f3e826b8fcaa41f7009a39e1d94654702203c98451d91ce900540d441f43fb10b62e2801341a8271cd70e8720024f31dcf501] PUSHDATA(33)[02aea69f99aec7d9afb8aae412224f56dcf091ff3e80516e0c58a300423d756a24]  949.0994325 CMC
              P2PKH addr:mhXqGpuRrJzCGgSQUZzBJ9dBb3sZN

**Comment by yuzhongrong** [comment]
2-18: statistical

21-18统计

    Balances:
      521.90 CMC ESTIMATED
      521.90 CMC AVAILABLE
      521.90 CMC ESTIMATED_SPENDABLE
      521.90 CMC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      5 unspent
      0 spent
      0 dead
    Last seen best block: 14341 (2019-12-18T06:53:03Z): 00000000b49012ad2210ce784a70c82f08923863cabb6dfb4644b21b903b8918
    
    Keys:
    Earliest creation time: 2019-12-18T06:48:02Z
      addr:mrHgApyWeVznzSRdQ2cNixNvYcGDqdoFYF,tb1qwcngg9lhwzuwj47uf2fr90r3x7qvq6vq32fuwg  hash160:76268417f770b8e957dc4a9232bc713780c06980  creationTimeSeconds:1576651683 [2019-12-18T06:48:03Z]  (imported)
    Seed birthday:     1576651682  [2019-12-18T06:48:02Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD8NVENRZdoraRmLsKVqj6kWd1ZHSRnrsd28BUScjYL7GscLjVVE9nZ58Q3q8AWiqktVWezHaADW41bA6mYUPzHxpE9wmQzEUwkEg9knqSSU
    Lookahead siz/thr: 100/33
      addr:mgsqVDWmc97VZnFCpoqRqTy2FaZyJxyWSC  hash160:0eeb2da71c1ac2bb451613e55bf7242f7f0cc314  (M, root)
      addr:n3RTUqBh6Thn874AwKXvDSi4LhgVwdb8ZH  hash160:f048a2730c3fdb8ddb9a49ad7e6333221db5842b  (M/0H, account)
      addr:mw9Aeaws7sFBkL7TaZz4TKJgmXb8VmXMSp  hash160:ab632c8a14c767b967c465b5488651ad6b8eb907  (M/0H/0, external)
      addr:mr56kp1uqSaaBtVEdS36273eyJSS77yjuc  hash160:73c5a1bc6f10f9de26b5f40249a34b146d230ce9  (M/0H/1, internal)
      addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS  hash160:7efdc23ae64c33936b76f12d1bc3e73b755478ea  (M/0H/0/0)
      addr:mzSVE7xoJWQohBz5gc2iEqP4aLj4DNdanv  hash160:cf922187614e3689388438b63e9d86992705ca68  (M/0H/0/1)
      addr:n3qSTi3b2wn6B6To3TBB52sVJvaeqgHbYa  hash160:f4d1c448587f70b0e251b88cd9ee8a10dd10f3b0  (M/0H/0/2)
      addr:mqf1gprkSGavuYogB2seYNRKuxTqkyVs2y  hash160:6f376ae4705f710df24ad86990ba20f0b75293ab  (M/0H/0/3)
      addr:n1rvZ4rZX2xNj9YtLfXGE8uFwQk1oKKJSj  hash160:df2961a823405795f9a3d0878fd5f7548bef40c4  (M/0H/0/4)
      addr:mpxhWFVHMjpMPRLEiYoQ4Qe4AJw7NDhn3T  hash160:679799ea23779c61daeabf6a911ce405caaeabc4  (M/0H/0/5)
      addr:mywf3kWRnyeD8MfyrmgoXoRGm7FZrv69tW  hash160:ca1e443394e2694fb08075955dd79ac67d38b819  (M/0H/0/6)
      addr:miWHX6fcPpE1jjTkSu6juxwJ8r5Wj7ifik  hash160:20c80270aefeebc9eb0a795a9391088f07a1007f  (M/0H/0/7)
    
    
    >>> UNSPENT:
    300.00 CMC total value (sends 0.00 CMC and receives 300.00 CMC)
      confidence: Appeared in best chain at height 14267, depth 75. Source: NETWORK
      600b834e4af95765ef1e4fe088a6a03c090e922ab5724270d67cac6aa14f6651
      weight: 900 wu, 225 bytes
      updated: 2019-12-17T10:16:46Z
      purpose: UNKNOWN
         in   PUSHDATA(71)[304402207e98c368436c4d39711dbf94fa899cecd560be6a33c25604e3bc71bb8a3665ef022022edd5b3778fa0def0bfcbae2ee763a70813c3cafa65242e7cd1abcdb5efea2901] PUSHDATA(33)[0339bf92d1d327689d664cd83b3399bc8933a740e4a93951623c12a68cffb447f2]  790.098865 CMC
              P2PKH addr:mpijwX9DUec1d9VAq4iuHvdTayn5sshgKi  outpoint:13d2689f900c5009fe3685a0137466fbb101e52f68f9688b1dece57d1c0f7641:0
         out  DUP HASH160 PUSHDATA(20)[7d7bf2f2937ee3e684944a664a3facaa282e6219] EQUALVERIFY CHECKSIG  490.0982975 CMC
              P2PKH addr:mrxTFAJqXTwwoDb2Ha4qJCmRrCaBMgumsv
         out  DUP HASH160 PUSHDATA(20)[20c80270aefeebc9eb0a795a9391088f07a1007f] EQUALVERIFY CHECKSIG  300.00 CMC
              P2PKH addr:miWHX6fcPpE1jjTkSu6juxwJ8r5Wj7ifik
         fee  0.00063055 CMC/wu, 0.00252222 CMC/kB  0.0005675 CMC
    159.00 CMC total value (sends 0.00 CMC and receives 159.00 CMC)
      confidence: Appeared in best chain at height 14248, depth 94. Source: NETWORK
      13d2689f900c5009fe3685a0137466fbb101e52f68f9688b1dece57d1c0f7641
      weight: 900 wu, 225 bytes
      updated: 2019-12-17T04:28:41Z
      purpose: UNKNOWN
         in   PUSHDATA(71)[304402201372161b2eaf90f045ce7d8501d990c00f3e826b8fcaa41f7009a39e1d94654702203c98451d91ce900540d441f43fb10b62e2801341a8271cd70e8720024f31dcf501] PUSHDATA(33)[02aea69f99aec7d9afb8aae412224f56dcf091ff3e80516e0c58a300423d756a24]  949.0994325 CMC
              P2PKH addr:mhXqGpuRrJzCGgSQUZzBJ9dBb3sZN8CStV  outpoint:1d3db641fd15f106227e6b6b8f86ecbbc498f5fd7fdf8e1ee52f4d77bab6a101:1
         out  DUP HASH160 PUSHDATA(20)[64f3cf9bf9410c60389b1d0029d7669dfc2d0744] EQUALVERIFY CHECKSIG  790.098865 CMC
              P2PKH ad
2019-12-18 15:01:27.261 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------confidence----->Appeared in best chain at height 14181, depth 161. Source: NETWORK
2019-12-18 15:01:27.261 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------process---->接收|发送 成功
2019-12-18 15:01:27.261 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------transaction-time----->1576482036000
2019-12-18 15:01:27.263 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------confidence----->Appeared in best chain at height 14198, depth 144. Source: NETWORK
2019-12-18 15:01:27.263 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------process---->接收|发送 成功
2019-12-18 15:01:27.264 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------transaction-time----->1576496020000
2019-12-18 15:01:27.265 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------confidence----->Appeared in best chain at height 14267, depth 75. Source: NETWORK
2019-12-18 15:01:27.265 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------process---->接收|发送 成功
2019-12-18 15:01:27.265 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------transaction-time----->1576577806000
2019-12-18 15:01:27.267 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------confidence----->Appeared in best chain at height 14248, depth 94. Source: NETWORK
2019-12-18 15:01:27.267 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------process---->接收|发送 成功
2019-12-18 15:01:27.267 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------transaction-time----->1576556921000
2019-12-18 15:01:27.382 23015-23015/cn.wildfirechat.imshat E/Skychat: │ ------balanceLiveData----->52190000000
2019-12-18 15:01:27.383 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------balanceLiveData-getUnspents----->300.00 CMC
2019-12-18 15:01:27.384 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------balanceLiveData-getUnspents----->159.00 CMC
2019-12-18 15:01:27.384 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------balanceLiveData-getUnspents----->10.00 CMC
2019-12-18 15:01:27.384 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------balanceLiveData-getUnspents----->2.00 CMC
2019-12-18 15:01:27.384 23015-23015/cn.wildfirechat.imshat E/Skychat: │ -------balanceLiveData-getUnspents----->50.90 CMC

**Comment by yuzhongrong** [comment]
Obviously one record is missing 0.123!!!

**Comment by schildbach** [comment]
It looks like you're connected to some other network, rather than Bitcoin:

> Last seen best block: 14341 (2019-12-18T06:53:03Z): 00000000b49012ad2210ce784a70c82f08923863cabb6dfb4644b21b903b8918

That block hash doesn't exist on the Bitcoin network, and the date also doesn't match the height.

**Comment by yuzhongrong** [comment]
this is demo  ，What I want to ask is is there a setting to delete the transaction history and hide the amount about bitcoinj

**Comment by schildbach** [comment]
You can reset your wallet and remove all transactions, but you cannot remove individual transactions. Your balance is always adjusted accordingly, because it's the sum of all incoming and outgoing value.

**Comment by schildbach** [comment]
I'm closing this because this is no issue report. If you've got questions please post to the mailing list.
