### ISSUE TITLE
Every time the wallet birthday is restored to the current time

### ISSUE THREAD

**Issue by yuzhongrong** [bitcoinj/bitcoinj#1955]
Every time the wallet birthday is restored to the current time

correct：

  Balances:
      391.8821707 BTC ESTIMATED
      391.8821707 BTC AVAILABLE
      391.8821707 BTC ESTIMATED_SPENDABLE
      391.8821707 BTC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      5 unspent
      59 spent
      0 dead
    Last seen best block: 14617 (2019-12-21T09:41:59Z): 000000009e21fcc9815914e6227a89b9f1671a2b107bae68e681f86caa7f07f4
    
    Keys:
    Earliest creation time: 2019-09-24T15:11:45Z
    Seed birthday:     1569337905  [2019-09-24T15:11:45Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD9fQfSfRxqW4qSdVya7YiGTNHM2CiPMoGdNSkZyBm92RDMNecKnN1oBFnLT9hnAJ5mdkA5SQo5xU6y9onM3aV8m9GZxshbAs4JtTbM6Ypru
    Lookahead siz/thr: 100/33
      addr:mxu5iL6pBjqcJ3wZoZWai3w32rrTSj1ihK  hash160:bea97b702ac67d07eb1b98d9ab58e1b10e59a5e6  (M, root)
      addr:mgukY1zBLBSDihURaXqE6gNdNmEJLD9rs2  hash160:0f47e074c1f42ac2e1c11de9832693ee92ce3058  (M/0H, account)
      addr:mqDEYQHBoHSC57Lz6vRJ4d94p6xWrTUvci  hash160:6a575549c88f77d9dff8bb8def399f95e682b359  (M/0H/0, external)
      addr:mp8SL31Ue9PsW4UGrcWfQzXAxi5UbAXCTZ  hash160:5e76f777e3d553301d40611c31c3a3a1e7892434  (M/0H/1, internal)

Incorrect：
 Balances:
      525.8694325 BTC ESTIMATED
      525.8694325 BTC AVAILABLE
      525.8694325 BTC ESTIMATED_SPENDABLE
      525.8694325 BTC AVAILABLE_SPENDABLE
    Transactions:
      0 pending
      7 unspent
      1 spent
      0 dead
    Last seen best block: 14620 (2019-12-21T10:11:20Z): 0000000030f9068360c130d6bb11d8fafd3f229fbd9453016b0ae49aab61a7b0
    
    Keys:
    Earliest creation time: 2019-12-21T08:57:42Z
      addr:mjqgjLwwRNBa9EGf8g2huTDGePZSw6yGLk,tb1q9a4k5r03rwkgsz8f670cmaz5w0wks6qdkr3zlc  hash160:2f6b6a0df11bac8808e9d79f8df45473dd68680d  creationTimeSeconds:1576918663 [2019-12-21T08:57:43Z]  (imported)
    Seed birthday:     1576918662  [2019-12-21T08:57:42Z]
    Ouput script type: P2PKH
    Key to watch:      tpubD8NVENRZdoraRmLsKVqj6kWd1ZHSRnrsd28BUScjYL7GscLjVVE9nZ58Q3q8AWiqktVWezHaADW41bA6mYUPzHxpE9wmQzEUwkEg9knqSSU
    Lookahead siz/thr: 100/33
      addr:mgsqVDWmc97VZnFCpoqRqTy2FaZyJxyWSC  hash160:0eeb2da71c1ac2bb451613e55bf7242f7f0cc314  (M, root)
      addr:n3RTUqBh6Thn874AwKXvDSi4LhgVwdb8ZH  hash160:f048a2730c3fdb8ddb9a49ad7e6333221db5842b  (M/0H, account)
      addr:mw9Aeaws7sFBkL7TaZz4TKJgmXb8VmXMSp  hash160:ab632c8a14c767b967c465b5488651ad6b8eb907  (M/0H/0, external)
      addr:mr56kp1uqSaaBtVEdS36273eyJSS77yjuc  hash160:73c5a1bc6f10f9de26b5f40249a34b146d230ce9  (M/0H/1, internal)
      addr:ms6RRgv5xyLyYofydkWLKoMvk37RqbnweS  hash160:7efdc23ae64c33936b76f12d1bc3e73b755478ea  (M/0H/0/0)

Birthday should not be the current time to restore the wallet

**Comment by schildbach** [comment]
It's a fresh wallet, so the birthdate is fresh too.

You need to make sure in your code you're saving and loading your wallet. Please have a look at the examples, and/or look at and use the WalletAppKit class.
