### ISSUE TITLE
Is there any way to transfer bitcoins from one wallet to other wallet on the same same system?

### ISSUE THREAD

**Issue by abhishekrajawat** [bitcoinj/bitcoinj#1958]
I am looking for code by which I can transfer bitcoins from one wallet to another wallet. Both wallet's files are on my machine and I have full access of the wallets. I tried to find any code in bitcoinj liberary but I didn't find. Can anyone help me with some code example, how to transfer bitcoins from 1 wallet to another without internet connection (on my local machine). You can also understand it as offline transfer of bitcoins because I have both wallets. I just want to save transaction fees attached to transaction. This is actually my project's part of implementation but but I am not getting any sample code to do this.
Please help...

**Comment by schildbach** [comment]
Can you ask questions on the mailing list? Thanks.

**Comment by abhishekrajawat** [comment]
I am new to github asking question. Can you please tell where I acn find mailing list of bitcoinj project stackholders? Thanks in advance.

**Comment by schildbach** [comment]
It's listed at https://bitcoinj.github.io/#community.

**Comment by mmo2112** [comment]
@abhishekrajawat, which type of address are you using? Legacy or P2SH or other? Please post your few sample address.

**Comment by abhishekrajawat** [comment]
Here are 2 sample addresses:
mkXEgXhnZqKHaHs27zZU9BvaC3WqCjhAPk
mjXUEvRYmKuC1QrqV6F2Ny4evman5nn8kb

I created using below code 
```
NetworkParameters params = TestNet3Params.get();
WalletAppKit kit = new WalletAppKit(params, new File("./wallet"), "sendrequest-example");
kit.startAsync();
kit.awaitRunning();
System.out.println("Wallet Details are: \n" + kit.wallet());
```
here I changes `"sendrequest-example"` to `"forwarding-service-testnet"` to create another wallet file. I have both files on my local system. I have taken some test coins and now I want to transfer from one wallet to another on system without any network use or by just using localhost network. 
Is it possible? If yes, how? Can you provide some sample codes?

**Comment by mmo2112** [comment]
@abhishekrajawat, here is your example for legacy address. Please check the doc more carefully by path: \bitcoinj\core\src\test\java\org\bitcoinj\core\TransactionTest:
BigDecimal BTC_TO_SAT = new BigDecimal(10).pow(8);
NetworkParameters network = TestNet3Params.get();
String fromAddress = "msSjXNhzh9mabmrkW4wquj2PLS9W29FXAt";
String toAddress = "n1wqtR8sLNFeKTsDWtdiciSymjaPe3AYdo";
String outputAmount = "0.001";
String changeAddress = fromAddress;
String privateKey = "xxx";

//Previous Tx
String prevInputAmount = "0.00444934";
String prevTxHash = "2f061d35373cc1b8ebd31fbd4495d6ba672d594003c0a5e3b22b2da2e74320b7";
long prevTxIndex = 3;
TransactionOutPoint prevTx = new TransactionOutPoint(network, prevTxIndex, Sha256Hash.wrap(prevTxHash));

long inputAmountInLong = new BigDecimal(prevInputAmount).multiply(BTC_TO_SAT).longValue();
long outputAmountInLong = new BigDecimal(outputAmount).multiply(BTC_TO_SAT).longValue();;
long feeAmountInLong = 5000;
long changeAmountInLong = inputAmountInLong - outputAmountInLong - feeAmountInLong;

Address fromAddr = LegacyAddress.fromString(network, fromAddress);
Script scriptPubKey = ScriptBuilder.createP2PKHOutputScript(fromAddr.getHash());

Transaction tx = new Transaction(network);
tx.addOutput(Coin.valueOf(outputAmountInLong), Address.fromString(network, toAddress));
tx.addOutput(Coin.valueOf(changeAmountInLong), Address.fromString(network, changeAddress));
ECKey ecKey = ECKey.fromPrivate(new BigInteger(privateKey, 16));
tx.addSignedInput(prevTx, scriptPubKey, ecKey);
System.out.println("serialized Tx: " + Utils.HEX.encode(tx.bitcoinSerialize()));

**Comment by abhishekrajawat** [comment]
I am new to bitcoinj liberary. As far as I understood, above code create a transaction but doesn't send bitcoin to other wallet. I am looking for any solution where I can send bitcoins between 2 wallets only through localhost network/peer (without using online network/peer) so that I can save transaction fees for at least localhost transactions of wallets on same server/machine. Is it possible? If yes, can you please suggest me some code sample?

**Comment by mmo2112** [comment]
@abhishekrajawat, I think you don't understand enough about bitcoin or crypto asset. There is no many difference about addresses on your local machine and other addresses. Or you meaning about hd key, the base of that is managing all private key of these addrresses by mnemonic words and derivation path. Thus, each address of bitcoin address has own private key, and if you have this key you can do anything with this address. Instead of remember your private key, you can create mnemonic words and derivation path for retrieve this private key. Okay, it's hierarchical deterministic key, you can search it more.
Return to your problem, you can't "send bitcoins between 2 wallets only through localhost network/peer (without using online network/peer)", because nobody can confirm for your transaction and that is not p2p or base nature of bitcoin or other crypto asset. And as I said, your address on your local machine are same as other address on network, they must be broadcast to one node and wait other to confirm by paying a little bitcoin fee.

**Comment by abhishekrajawat** [comment]
@mmo2112 Thanks for your clearification. Its now more clear to me.
