### ISSUE TITLE
Guava Gradle dependency in 'core' should be 'api' not 'implementation'

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1963]
Since (for now at least) Guava types are used in **bitcoinj**'s public API.  (Example `PeerGroup#startAsync()` returns a `ListenableFuture`)

When building apps with more recent versions of Gradle, Guava won't be included in the compile class path and users will manually need to add Guava to their dependencies -- even when it's only needed for the **bitcoinj** API.

**Comment by msgilligan** [comment]
@schildbach If you agree with this, I'll submit a PR.

**Comment by schildbach** [comment]
Generally I agree. However, 'api' doesn't seem to be available under Gradle 4.4.

**Comment by msgilligan** [comment]
Actually `api` is available under Gradle 4.4 if you use the `java-library` plugin instead of the `java` plugin.

I made a PR: https://github.com/bitcoinj/bitcoinj/pull/1965

**Comment by msgilligan** [comment]
PR #1965 is merged.
