### ISSUE TITLE
How to use addr broadcasts to connect to more peers and identify their type?

### ISSUE THREAD

**Issue by AlexSJJ** [bitcoinj/bitcoinj#1969]
1.In public class DnsDiscovery, it shows that If you want more peers to connect to, you need to discover them via other means (like addr broadcasts).  Does anyone know how to achieve this？

2.How to identify the type of a new peer when it is connected, such as a Bitcoin Core or just a SPV?

**Comment by schildbach** [comment]
> 1.In public class DnsDiscovery, it shows that If you want more peers to connect to, you need to discover them via other means (like addr broadcasts). Does anyone know how to achieve this？

Currently addr messages are parsed, but mainly ignored. The part that adds them into the inactive queue has yet to be implemented. Should be easy to do though.

> 2.How to identify the type of a new peer when it is connected, such as a Bitcoin Core or just a SPV?

You can read the version message of the remote peer. It has a subVer field, containing the name (e.g. "Satoshi" for Bitcoin Core). Note that bitcoinj doesn't support inbound connections, so you won't see any SPV nodes at all.
