### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [bitcoinj/bitcoinj#1976]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by Neustradamus** [comment]
@schildbach: No duplicates:
- https://github.com/bitcoinj/bitcoinj.github.io/issues/42
- https://github.com/bitcoinj/wallet-template/issues/6

Sources:
- bitcoinj: https://github.com/bitcoinj/bitcoinj/search?q=spongycastle&unscoped_q=spongycastle
- bitcoinj.github.io: https://github.com/bitcoinj/bitcoinj.github.io/search?q=spongycastle&unscoped_q=spongycastle
- wallet-template: https://github.com/bitcoinj/wallet-template/search?q=spongycastle&unscoped_q=spongycastle

**Comment by schildbach** [comment]
Bitcoinj is using BouncyCastle since over a year!

I just updated BC to the latest minor version via f925c6313c838b4d5313658c982b41328e207c79.

**Comment by Neustradamus** [comment]
@schildbach: Sorry, I mix links!
Yes the title is update not replace.

**Comment by Neustradamus** [comment]
@schildbach: Sorry, I mix links, it is good now!
Yes the title is update not replace.

Can you look for wallet-template now?

**Comment by schildbach** [comment]
Wallet-template is not using BouncyCastle directly. Rather, BC is a transitive dependency via bitcoinj-core (which was just updated).

**Comment by Neustradamus** [comment]
@schildbach: But...
- https://github.com/bitcoinj/wallet-template/search?q=spongycastle&unscoped_q=spongycastle

**Comment by schildbach** [comment]
Again, that's an old version. Current versions use BC.

**Comment by Neustradamus** [comment]
Where is the current Wallet?

**Comment by schildbach** [comment]
The current master branch is here: https://github.com/bitcoinj/bitcoinj/commits/master
The current release branch is here: https://github.com/bitcoinj/bitcoinj/commits/release-0.15

**Comment by Neustradamus** [comment]
@schildbach: But the "wallet-template", if it is old repository, I think it is needed to archive.

**Comment by schildbach** [comment]
The current master of wallet-template is here: https://github.com/bitcoinj/bitcoinj/tree/master/wallettemplate
I just deleted the outdated standalone repository.

**Comment by Neustradamus** [comment]
@schildbach: Can you update to 1.69?
