### ISSUE TITLE
Remove dependency on OkHttp in bitcoinj-core

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1978]
If I inspected the code correctly it is only used by an experimental feature (`org.bitcoinj.net.discovery.HttpDiscovery` and `org.bitcoinj.net.discovery.MultiplexingDiscovery`)

There are at least 4 ways we could do this:

1) Move experimental features to another module/JAR.
2) Remove the experimental feature all together (or put it on a branch) 
3) Replace the direct dependency on OkHttp with an interface that is implemented elsewhere
4) Mark the dependency as optional in Gradle (I've never done this, but would be willing to try it out)

**Comment by schildbach** [comment]
Hmm, what's so bad about OkHttp? I can't think of any app that could do without it nowadays.

`HttpDiscovery` is in production use since a couple of years. Maybe we should reword the comment in its class JavaDoc?

Isn't OkHttp also used in the payment protocol implementation?

**Comment by schildbach** [comment]
> Isn't OkHttp also used in the payment protocol implementation?

Actually it uses `HttpURLConnection` (in `PaymentSession`). It's a long-time todo to migrate that to OkHttp. We could think about splitting off payment protocol support to a submodule though.

**Comment by msgilligan** [comment]
> Hmm, what's so bad about OkHttp? I can't think of any app that could do without it nowadays.

OkHttp is great. However, there are plenty of applications using **bitcoinj** in environments with other HTTP implementations, running offline, or needing to use a different version of OkHttp. As you know I'm working on packaging apps using `jpackage` and also on native compilation with Graal's `native-image`. In general, I'm trying to minimize dependencies as much as possible,  which is always a good practice for library developers.

(In one particular case, I'm using the `java.net.http` implementation -- see [Introduction to the Java HTTP Client](https://openjdk.java.net/groups/net/httpclient/intro.html) -- that was added in JDK 11. I had problems trying to run Retrospect/OkHttp inside a Java Module and to resolve the issue I created an abstract base class that uses `CompletableFuture`, an Android/JDK8 subclass using Retrospect/OkHttp and and a JDK11+ subclass using `java.net.http`. This allows my `jpackage`-d JavaFX app to use the `java.net.http` and only depend on built-in JDK networking. When I port the app to Android, I'll use the OkHttp subclass/JAR.)

In the short-term I'm looking to eliminate whatever dependencies I can. (For example, I've been trying to replace Guava objects/methods with standard JDK APIs wherever possible.)

In the long-term, I'm hoping we can split `bitcoinj-core` into two or three separate modules. (See Issue #1874, which proposes 2 modules.) For three modules it might be something like:

base/core -- no dependencies except standard JDK (likely JDK 8)
messages -- adds protobuf dependency
network -- adds networking dependencies

Once we're at JDK 8+, we could create network interfaces that use `CompletableFuture` and then provide an implementation that uses `OkHttp` and (optionally) another that uses `java.net.http`

> 
> `HttpDiscovery` is in production use since a couple of years. Maybe we should reword the comment in its class JavaDoc?

Yeah, I took the JavaDoc at face value and that made me think removing OkHttp would be "low-hanging fruit".

**Comment by msgilligan** [comment]
> [the payment protocol implementation] uses `HttpURLConnection` (in `PaymentSession`). It's a long-time todo to migrate that to OkHttp. We could think about splitting off payment protocol support to a submodule though. That would free us from X.509 deps.

Payment protocol support in a submodule sounds like a good idea.

In cases where we are looking to migrate away from `HttpURLConnection`, I would encourage defining networking interface abstractions that use `CompletableFuture` (since the plan is to require JDK8 in the next major version, right?) and then provide at least an OkHttp implementation and possibly a `java.net.http` implementation.

**Comment by msgilligan** [comment]
(Issue title updated to remove the word "unnecessary")

**Comment by msgilligan** [comment]
> > Hmm, what's so bad about OkHttp? I can't think of any app that could do without it nowadays.
> 
> OkHttp is great. However...

Another use case for Http-library independent networking is unit testing.

**Comment by msgilligan** [comment]
PR #2189 is (in my opinion) a step in the right direction.

**Comment by msgilligan** [comment]
Resolved by merged PR #2279.
