### ISSUE TITLE
Protobuf 0.8.12+, require minimum of Gradle 5.6 for build

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#1985]
We are currently two releases behind on the [protobuf-gradle-plugin](https://github.com/google/protobuf-gradle-plugin/) because the latest version requires Gradle 5.6 or later.  In PR #1973, we upgraded to v0.8.10 which was (and is) two versions behind the latest (currently v0.8.12)

I think we should upgrade our minimum Gradle requirements for the build to version 5.6 or later and update our build scripts and documentation accordingly. Protobuf is a key component of bitcoinj and we will want to track the latest version of it's build tool.

**Comment by msgilligan** [comment]
@schildbach If you agree that we should do this, I will create and submit a Pull Request.

**Comment by msgilligan** [comment]
@schildbach I went ahead and created PR #1986 for this.

**Comment by schildbach** [comment]
The best way to see this happening is helping the Linux distros with packaging Gradle. As far as I know, currently packaging Kotlin is the prerequisite for more recent Gradle versions.

I agree that following the latest tools is a good thing generally. However introducing another download dependency (by using the Gradle Wrapper) is a step backwards in terms of security and build reproducibility. Third party repos have a horrible security history, just lately hundreds of Bitcoin stealers and other malware have been found in a common repo for Ruby packages.

**Comment by msgilligan** [comment]
> The best way to see this happening is helping the Linux distros with packaging Gradle. As far as I know, currently packaging Kotlin is the prerequisite for more recent Gradle versions.

In general, I am not a fan of using Linux distros packaging for getting Java tools. I think the Linux philosophy of source and binary packages does not map well to Java, nor does it work well for developers working on a wide variety of project each project requiring different versions of the tools. (Also, my main development platform is macOS) So helping the Linux distros to bundle a newer Gradle isn't very appealing to me.

> 
> I agree that following the latest tools is a good thing generally. However introducing another download dependency (by using the Gradle Wrapper) is a step backwards in terms of security and build reproducibility. Third party repos have a horrible security history, just lately hundreds of Bitcoin stealers and other malware have been found in a common repo for Ruby packages.

Actually, if you look at PR #1986 I have not changed the basic behavior of any of the builds. The wrapper is not being included in Git, just the `gradle wrapper` command is being used to upgrade Gradle as it was before. I just changed the version of Gradle that is being downloaded. I discovered there is a way to add a shasum check to those downloads, so I'm going to update the PR to use it.

Personally (as I've said before) I think our overall security and build reproducibility would be improved by standardizing on a recent version of Gradle and using the wrapper (with proper precautions) but we can discuss that elsewhere.

What I had intended in this Issue/PR was _not_ to change the project's build philosophy, just to update the minimum version of Gradle from 4.4 to 5.6.

**Comment by msgilligan** [comment]
> I discovered there is a way to add a shasum check to those downloads, so I'm going to update the PR to use it.

That didn't work out. There is a `--gradle-distribution-sha256-sum=$GRADLE_SHA256` option when running `gradle wrapper`, but unfortunately it doesn't exist in Gradle 4.4.

**Comment by schildbach** [comment]
As far as I remember, the gradlew stuff is only there for people who insist to use `gradlew`. The official way to build bitcoinj is still via `gradle`.

My vision is to get bitcoinj into Debian, and hopefully also some wallet based on it. Requiring a Gradle version that is currently not available in Debian is sadly kind of a shopstopper for Debian, and using gradlew is out of question because downloading binaries is not allowed either afaik.

I'll keep your PR around. I'm not against the upgrade, I just think it's too early at the moment.

**Comment by msgilligan** [comment]
> As far as I remember, the gradlew stuff is only there for people who insist to use `gradlew`. The official way to build bitcoinj is still via `gradle`.

We're using `gradle wrapper` (not `gradlew`) in a few places on CI to load a newer Gradle.

> 
> My vision is to get bitcoinj into Debian, 

Thanks for this explanation!

> and hopefully also some wallet based on it.

Hmm. Maybe an OpenJFX-based wallet?

**Comment by msgilligan** [comment]
We have had conditional inclusion of newer Protobuf for some time now. Closing.
