### ISSUE TITLE
Has anybody built a reusable wallet service with bitcoinj?

### ISSUE THREAD

**Issue by msafi** [bitcoinj/bitcoinj#2004]
I'm looking for a wallet service to use with my desktop app. I tried bitcoind and btcwallet but each had its limitations. I'm wondering if somebody had already built a full bitocoinj wallet service that my desktop client can interact with to offer wallet features?

**Comment by msgilligan** [comment]
Have you seen [WalletAppKit.java](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/kits/WalletAppKit.java)?

**Comment by msafi** [comment]
@msgilligan I have not seen that. But even now that I've seen it, I'm not sure what it is. It doesn't seem like a complete backend wallet service like bitcoind or btcwallet. Is it?

**Comment by msgilligan** [comment]
>  I'm not sure what it is.

It's what I would call a "Service Object" -- I've used it to make a Java-based desktop wallet (and you can look at `wallettemplate` for an example JavaFX-based desktop wallet.

>  It doesn't seem like a complete backend wallet service like bitcoind or btcwallet. Is it?

So you're looking for an HTTP-based (localhost) network service you can talk to?

**Comment by msafi** [comment]
>So you're looking for an HTTP-based (localhost) network service you can talk to?

Yes, with its own database and all :)

**Comment by msgilligan** [comment]
I've dabbled with it over here: https://github.com/ConsensusJ/consensusj
You can configure `bitcoinj` to use a database (and even be a full node.) So it should be possible to use that bitcoinj configuration and use the RPC wrapper in consensus and build what you want. But it's not going take some work to finish it and make it reliable.

I'm hoping to build out the Block-level RPCs over the next month or two.

**Comment by msgilligan** [comment]
Why can't you use `bitcoind`?

**Comment by msgilligan** [comment]
You should also take a look at the `WalletTool` command-line tool in the `tools` subproject. I had some success in compiing it to a native command-line tool using the GraalVM `native-image` command.

**Comment by msafi** [comment]
> Why can't you use `bitcoind`?

I wanted something with SPV, or something that can support `xpub` watch-only HD wallets. `bitcoind` doesn't have those features and given their rate of development and architectural challenges, I doubt they'll be able to add these features anytime soon. But that's not really what prevented me. What prevented me is that I don't know how to compile an executable macOS binary for `bitcoind`. Unlike with Windows and Linux, Bitcoin Core doesn't ship an headless binary for macOS. I opened a ticket for that but I don't think they're interested in supporting my use-case, which is another concern I have with using `bitcoind`.

> You should also take a look at the `WalletTool` command-line tool in the `tools` subproject. I had some success in compiing it to a native command-line tool using the GraalVM `native-image` command.

I'll take a look at that. Thanks :)

**Comment by Stiles-X** [comment]
Sorry, didn't want to make a useless appreciation "issue" thread. It's wonderful how this project is still alive. I also have a question to ask.
How does using Java affect performance, ease, etc. vs "non gc / compiled" languages such as rust / c++ / c. I put it in quote because compiled and gc is not exclusive, but you get my point.
Not trying to start religious wars, just curious. Also, what language / language type would you wish a btc project like this is most suitable to develop with? Would dot net core be good enough?

**Comment by msgilligan** [comment]
> I wanted something with SPV, or something that can support `xpub` watch-only HD wallets. 

Then you should definitely take a look at the `wallettemplate` subproject, as well. I'm hoping to release an application (hopefully to the macOS store) that does exactly that (`xpub`, watch-only) and will continue to be pushing improvements upstream to **bitcoinj**. I've also been working on adding the ability for the watch-only wallet to use an external device with the HD private keys to sign transactions and then have the watch-only wallet submit them to the network.

> What prevented me is that I don't know how to compile an executable macOS binary for `bitcoind`. Unlike with Windows and Linux, Bitcoin Core doesn't ship an headless binary for macOS.

I've struggled with this (and eventually succeeded) in the past. But I haven't (yet) tried with more recent versions of `bitcoind`.

I may take a shot at compile macOS `bitcoind` again in the future, but for now my focus is on other things including the **bitcoinj**-based "network wallet" (watch-only with external "signing wallet") and possibly a **bitcoinj**-based RPC server that saves blocks and transactions in a database.

**Comment by msgilligan** [comment]
> How does using Java affect performance, ease, etc. vs "non gc / compiled" languages such as rust / c++ / c. I put it in quote because compiled and gc is not exclusive, but you get my point.

> what language / language type would you wish a btc project like this is most suitable to develop with? Would dot net core be good enough?

@Stiles-X I don't want to hijack this thread with discussion of language and performance issues, but (in my opinion) Java/JVM, C#/DotNet, Rust, C++, C are all performant enough to implement Bitcoin (provided the appropriate low-level hashing/crypto functions are optimized.)

I should also mention that I have been experimenting with GraalVM's `native-image` tool to AOT (ahead-of-time) compile bitcoinj Java code to native binaries. This greatly speeds startup performance, reduces memory usage, and allows distributions that don't require a Java runtime.

**Comment by msgilligan** [comment]
@schildbach I think we can close this issue.
