### ISSUE TITLE
How export BicoinJ wallet to external app (wallets).

### ISSUE THREAD

**Issue by BitcoinJ-Questions** [bitcoinj/bitcoinj#2007]
Hello.

The first:

I have created a wallet (mainnet) use Bitcoinj, after sent some coins to this wallet. 

`DeterministicSeed deterministicSeed = new DeterministicSeed(new SecureRandom(), 128, passphrase);
        Wallet wallet = Wallet.fromSeed(chainService.getParams(), deterministicSeed, Script.ScriptType.P2PKH);`

I have get the mnemonic.

`deterministicSeed.getMnemonicCode()`

And now I want to import this wallet for example to the "Electrum" (https://electrum.org/#home)
Using MnemonicCode which I get above. But the wallet is different. It is empty. But should contain some coins which I have already send before.

Is it possible to export bitcoin J wallet? 

The second:

I have tried to import to the Bitcoinj existing wallet. Wallet has some amount of coins.

```
DeterministicSeed deterministicSeed  = new DeterministicSeed(
                MnemonicCode.toSeed(mnemonic, passphrase),
                passphrase, creationTimeSeconds());
```

Use AppWalletKit restoreWalletFromSeeds(deterministicSeed);

But I don't understand how to do it because "Electrum" doesn't has  "creationTime" and "passphrase" when I create the wallet.

P.S. Maybe someone facing with this problems before.

**Comment by java4tech** [comment]
You'll have to check the derivation path. You are using different path based on BIP32 but electrum uses BIP44. Check their path and then use sometime like:
`Wallet wallet = Wallet.fromSeed(params, seed, Script.ScriptType.P2PKH, ImmutableList.of(new ChildNumber(44, true), new ChildNumber(0, true), ChildNumber.ZERO_HARDENED, ChildNumber.ZERO));`

> But I don't understand how to do it because "Electrum" doesn't has "creationTime" and "passphrase" when I create the wallet.

Creation-time: It helps with the blockchain sync. With this time mentioned we don't have to scan the whole blockchain for any relevant transactions, Instead we can start forward from the time mentioned.
passphrase: This acts as a salt. its not necessary and it could be "null". 

For more info regarding electrum, please check their documentations.

**Comment by BitcoinJ-Questions** [comment]
new DeterministicSeed(MnemonicCode.toSeed(mnemonic, ""), "", 1577836800);

**Comment by java4tech** [comment]
No, Please read BIP 32 and BIP44 first and get a basic Idea about its working. Now, Let  me make it even simpler for you. If you have already sent transaction to the old wallet then you'll have to manually send it to BIP44 complaint wallets. You can use the method I mentioned to create new wallet and that will allow you to use the Mnemonic phrase to switch wallet applications without creating new transactions.
In-short -  You are trying to -->
BIP32 --> BIP44 (You can't do, because they use different paths)
You can do -->
BIP44 --> BIP44 (You can use Mnemonic phrases across different wallet)

**Comment by BitcoinJ-Questions** [comment]
Please correct me in case I am wrong.

1. Create wallet: 

```
DeterministicSeed deterministicSeed = new DeterministicSeed(new SecureRandom(), 128, passphrase); 
// I want to use it in the Electrum wallet and in the Bitcoinj app
String mnemonic = deterministicSeed.getMnemonicCode() 

// This wallet I will use in bitcoinj
Wallet wallet = Wallet.fromSeed(params, seed, Script.ScriptType.P2PKH, ImmutableList.of(new ChildNumber(44, true), new ChildNumber(0, true), ChildNumber.ZERO_HARDENED, ChildNumber.ZERO));
```

2. Recover and use wallet in the Bitcoinj

```
// 1592634573 = 20.06.2020 ...
// mnemonic - which I get above (converted to the List<String>)
DeterministicSeed seed = new DeterministicSeed(MnemonicCode.toSeed(mnemonic, ""), "", 1577836800);

// params mainnet
Wallet wallet = Wallet.fromSeed(params, seed, Script.ScriptType.P2PKH, ImmutableList.of(new ChildNumber(44, true), new ChildNumber(0, true), ChildNumber.ZERO_HARDENED, ChildNumber.ZERO));

// Add this wallet to the peer group and download blockchain 
// ...

```
3. Recover and use wallet in the Electrum using mnemonic which I get above.
