### ISSUE TITLE
How to convert the unit from satoshi to btc?

### ISSUE THREAD

**Issue by LouisWayne** [bitcoinj/bitcoinj#2010]
Sorry for asking such a basic question, but I can't find it from the official document.  What I have now is:

```
public void Foo(Transaction tx) {
    for (TransactionOutput output : tx.getOutputs()) {
        Coin coin = output.getValue();
        Double satoshiAmount = (double)coin.getValue(); // This is satoshi amount
    }
```

I'd like to get amount in BTC unit from `coin.getValue()`.  How do I do that?

p.s. Thanks for making awesome library!

**Comment by schildbach** [comment]
The `Coin` class always holds satoshis internally. You do the conversion to BTC or mBTC when showing an amount to the user, e.g. by using `MonetaryFormat`.

This is similar to the `Date` and `DateFormat` classes in the Java SDK.
