### ISSUE TITLE
no address variation

### ISSUE THREAD

**Issue by ashtonhogan** [bitcoinj/bitcoinj#2016]
eckey addresses always begin with `1`?  Surely this is wrong if there are other [addresses](https://www.blockchain.com/btc/address/36QUQXc8AgCUDexLLa3YRtienWCpzy6EU3) in existence?

**Comment by msgilligan** [comment]
The `3` addresses are Pay-to-script-hash (P2SH) and can properly be created with **bitcoinj**.  Pay-to-pubkey-hash (P2PKH) addresses always start with a `1`.

**Comment by ashtonhogan** [comment]
@msgilligan To create a P2PKH address we just use `ECKey key = new ECKey();` but how do you create a P2SH address?

**Comment by schildbach** [comment]
@ashtonhogan Can you join our Matrix room and ask questions there? https://matrix.to/#/#bitcoinj:matrix.org

**Comment by ashtonhogan** [comment]
@schildbach It doesn't let me join... do you have example source that I can look at for the simplest way to create a P2SH address by any chance?
