### ISSUE TITLE
Setup custom domain at bitcoinj.org for Github Pages site

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2026]
See: https://docs.github.com/en/github/working-with-github-pages/configuring-a-custom-domain-for-your-github-pages-site

We do have control of bitcoinj.org, right?

**Comment by schildbach** [comment]
Thanks for your pointer. Done!

Can you close this issue once the site resolves from your place?

**Comment by msgilligan** [comment]
https://bitcoinj.org is working! Thanks @schildbach !
