### ISSUE TITLE
Receive Event and Context

### ISSUE THREAD

**Issue by Tockra** [bitcoinj/bitcoinj#2034]
Hi Guys, 

I have two questions, which aren't related:

1. I get always the message 
```
[11:24:54 ERROR]: [org.bitcoinj.core.Context] Performing thread fixup: you are accessing bitcoinj via a thread that has not had any context set on it.
[11:24:54 ERROR]: [org.bitcoinj.core.Context] This error has been corrected for, but doing this makes your app less robust.
[11:24:54 ERROR]: [org.bitcoinj.core.Context] You should use Context.propagate() or a ContextPropagatingThreadFactory.
[11:24:54 ERROR]: [org.bitcoinj.core.Context] Please refer to the user guide for more information about this.
[11:24:54 ERROR]: [org.bitcoinj.core.Context] Thread name is bitcoinj user thread.
```
There is a refrence to the user guide. But I didn't find a guide with a small example, which explains where to place which function to disable this error message.

2. At the moment I'm listen on a receiving coin event:
```java
this.wallet().addCoinsReceivedEventListener(new WalletCoinsReceivedEventListener() {
            @Override
            public void onCoinsReceived(Wallet w, Transaction tx, Coin coin, Coin coin1) {
                Coin value = tx.getValueSentToMe(w);
                log.info("Received tx for " + value.toFriendlyString() + ": " + tx);
                log.info("Transaction will be forwarded after it confirms.");
                Futures.addCallback(tx.getConfidence().getDepthFuture(3), new FutureCallback<TransactionConfidence>() {
                    @Override
                    public void onSuccess(TransactionConfidence result) {
                        // Do Stuff
                    }

                    @Override
                    public void onFailure(Throwable t) {}
                }, MoreExecutors.directExecutor());
            }
        });
```
The problem is, that this event will be called if I send coins to a different wallet. This is caused by the bitcoin protocol. It splits 17 coin to 10.0 and 7.0. The 10.0 it will send. The 7.0 it will send to itself. But this triggers a receive event...

**Comment by Tockra** [comment]
So now I have following workaround:
Everytime when I send a amount of coin, I will save the address of the corresponding transaction to a list. 
Then I check `sendTransactions.contains(tx.getTxId().toString()))`. 
But I have still the issue with Context.propagate. Is there some documentation which really describe a solution?

**Comment by schildbach** [comment]
If you are not using a custom thread factory, use `Context.propagate(context)` as a first statement in your callbacks.

**Comment by Tockra** [comment]
> If you are not using a custom thread factory, use `Context.propagate(context)` as a first statement in your callbacks.

I'm using it, but I think this isn't multi thread compatible and cause a race condition ?
If two threads at the same time call `Context.propagate(context)` !?
