### ISSUE TITLE
SPVBlockStoreTest.performanceTest intermittently failing on Github actions

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2039]
```
java.lang.AssertionError: took 1.568 s for 100000 iterations
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.bitcoinj.store.SPVBlockStoreTest.performanceTest(SPVBlockStoreTest.java:154)
```

See:

* Code: [SPVBlockStoreTest.performanceTest](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/test/java/org/bitcoinj/store/SPVBlockStoreTest.java#L139-L157) 
* Test failure: https://github.com/bitcoinj/bitcoinj/runs/1048620971

The performance test sets a threshold of 1.5 s which we barely exceeded.

I propose we increase the threshold to 2 s and see if it happens again.

**Comment by schildbach** [comment]
I increased the threshold to 2s via 551b5a18f77e1424fcf1d7ac7b981dcd7c4bd6b1.
