### ISSUE TITLE
Can't send more than 2 spends.

### ISSUE THREAD

**Issue by Tockra** [bitcoinj/bitcoinj#2045]
Hi Guys,

I can't send multiple spends. If I do it, I got a `InsufficientMoneyException`. I think I need not to tell you, that I have enough coins on that wallet.
I'm using this library for dogecoin, but that shouldn't be the reason.
The number of transactions that work is different. Sometimes works just one. Sometimes two or three. But never more.
I tried to rise the fee to 1Coin/kb . But that didn't change anything.

Its not so cool because my program should send multiple transactions at once.

T

**Comment by schildbach** [comment]
A wallet dump would be necessary to say anything. But why don't you report this to dogecoinj?

**Comment by Tockra** [comment]
Because I'm using bitcoinj just with a different network. I think this is a issue by this lib. 
What exactly do you need ? The wallet is at this moment empty or has just a few dogecoin, so I have no problem to lose it.

**Comment by schildbach** [comment]
You can't use bitcoinj on a different network. It will inevitably fail. If anything, you need to use the specific fork of bitcoinj for that network (dogecoinj for Dogecoin).
