### ISSUE TITLE
Upgrade bitcoinj-core to JDK 8 (with Android API level 24 API subset)

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2051]
Upgrading `bitcoinj-core` module to JDK 8 will allow us to make some significant improvements to the codebase that should improve code readability, performance, reliability, and flexibility.

In order to support Android OS 7.0 (Nougat) and later we'll restrict JDK 8 API usage to the Android API level 24 subset.

**Comment by msgilligan** [comment]
@schildbach I'm proposing this be part of milestone 0.17.

**Comment by schildbach** [comment]
I think this too should be one of the first actions we do in the 0.17 cycle, such that we can take advantage of the new API.

**Comment by schildbach** [comment]
fyi – Bitcoin Wallet 9.x is now requiring Android API level 24 (Nougat). So from my side I'm ready to have that requirement in bitcoinj 0.17 too.

**Comment by msgilligan** [comment]
This was merged in a2cf303655f4d1794af52a70072bc29e5a96b842
