### ISSUE TITLE
Error Massage

### ISSUE THREAD

**Issue by ashraful1980** [bitcoinj/bitcoinj#2052]
Dear Sir,
I have tried to run your software; unfortunately the jar file has given following error massage.
C:\Users\PC\Downloads\bitcoinj>java -jar bitcoinj-0.11-bundled.jar
no main manifest attribute, in bitcoinj-0.11-bundled.jar

**Comment by schildbach** [comment]
You're using a stone old version which we don't offer support any more for.

Please read https://bitcoinj.org/#getting-started for how to get version 0.15.x into your project.
