### ISSUE TITLE
bitcoin fullnode

### ISSUE THREAD

**Issue by Mahla-ch** [bitcoinj/bitcoinj#2055]
hi,
how does bitcoinj interact with blockchain? Does it use APIs to get data about addresses and their transaction details? 
I need to add some addresses different from the wallet addresses which I create by bitcoinj. how can I add and how can I get blockchain data about these addresses?

**Comment by pedr0-fr** [comment]
Bitcoinj connects to bitcoin nodes (peers) that offer the 'BLOOM' service. It then sends a bloom filter to its peers that test the filter against all transactions (or only the ones in the UTXO set?), the ones that match the filter are sent to you and, if not false positives are added to your wallet. Your wallet will only fetch the block headers by default (~160 MB on testnet, ~40 MB on mainnet) and store the latest ones. It verifies the whole blockchain so it starts from block 0. See code in https://github.com/bitcoinj/bitcoinj/issues/2064 to get inspiration.

**Comment by schildbach** [comment]
I'm closing this as the question has been answered.

@Mahla-ch If you've got further questions, feel free to join our chat room at https://matrix.to/#/#bitcoinj:matrix.org
