### ISSUE TITLE
Add support for Bitcoin Tor V3 onions

### ISSUE THREAD

**Issue by wiz** [bitcoinj/bitcoinj#2067]
Bitcoin Core 0.21 now supports V3 onions, but apparently bitcoinj cannot connect to them

**Comment by schildbach** [comment]
Bitcoind doesn't contain any Tor code afaik, so what exactly does it support?

Has the address message v2 been implemented?

**Comment by wiz** [comment]
Yes, https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki

**Comment by schildbach** [comment]
Ok, this is indeed something I'd like to see implemented in bitcoinj. It should be easy to implement by modifying the existing AddressMessage class. If nobody else beats me at it, I will implement this myself once Bitcoin Core 0.21 has an official release.

**Comment by wiz** [comment]
Thanks @schildbach :)
Yeah, we need it for Bisq and I'm sure other projects will want it as well.

**Comment by wiz** [comment]
Okay, v0.21.0rc1 has been tagged which supports Tor V3 onions https://github.com/bitcoin/bitcoin/releases/tag/v0.21.0rc1

**Comment by ripcurlx** [comment]
Hi @schildbach! As v0.21 was released publicly I wanted to check if you have already a personal timeline when you are able to implement Tor V3 support for bitcoinj? Would be awesome to get this soon into Bisq! Thanks!

**Comment by schildbach** [comment]
I'm currently waiting for the docker images to be updated, as my development environment is based on that.

**Comment by schildbach** [comment]
I've now set up Bitcoin Core 0.21 via a V3 onion, both for Mainnet and Testnet. However I see my nodes only connected to V2 onions – none of them advertises as V2. And actually I only rarely see 0.21 nodes at all. Seems it takes more time for adoption.

**Comment by ripcurlx** [comment]
> I've now set up Bitcoin Core 0.21 via a V3 onion, both for Mainnet and Testnet. However I see my nodes only connected to V2 onions – none of them advertises as V3. And actually I only rarely see 0.21 nodes at all. Seems it takes more time for adoption.

Hi Andreas! Did you have time to re-visit your test setup for the tor v3 addresses?

**Comment by schildbach** [comment]
I'm on the implementation of addrv2 messages right now: https://github.com/bitcoinj/bitcoinj/pull/2108

However, I'm not sure how that relates to bitcoinj's ability to connect via Tor. As I understand, it should be able to connect through a Tor proxy already – should not matter if it's a V2 or V3 hidden service.

**Comment by wiz** [comment]
Glad to hear it! Yes, @Emzy also suggested this potential workaround, but we haven't tested it out yet.

**Comment by schildbach** [comment]
Just to be clear about this: I currently do not plan to implement native Tor support in bitcoinj. But I want to parse addrv2 (BIP155) messages to the extent that onion V3 addresses are understood just as well as currently onion V2 addresses are.

**Comment by ripcurlx** [comment]
> Just to be clear about this: I currently do not plan to implement native Tor support in bitcoinj. But I want to parse addrv2 (BIP155) messages to the extent that onion V3 addresses are understood just as well as currently onion V2 addresses are.

Hi @schildbach! Any update on the Tor v3 addresses support? 😄

**Comment by schildbach** [comment]
It's implemented via #2108 and #2113.
