### ISSUE TITLE
Set derivation path and generate addresses from XPub

### ISSUE THREAD

**Issue by StevenCooper737** [bitcoinj/bitcoinj#2071]
I want to set derivation path and generate addresses from XPub,
My code is:

```
val wallet = Wallet.fromWatchingKeyB58(
    networkParameters,
    xPub,
    DeterministicHierarchy.BIP32_STANDARDISATION_TIME_SECS.toLong())
val address = wallet.freshReceiveAddress().toString()
```

But generated addresses doesn't match my Ledger Nano X addresses with `84'/0'/0'/0/1` path.
Any suggestions on how to set this path please?

**Comment by schildbach** [comment]
For support, please join our Matrix room: https://matrix.to/#/#bitcoinj:matrix.org
