### ISSUE TITLE
Android : synchronization on a test network has balances and transactions, but on the real network nothing happens (I had a balance in my wallet before)

### ISSUE THREAD

**Issue by suusofttruongnv** [bitcoinj/bitcoinj#2073]
Please help me!!!

In Android : 
Synchronization on a test network has balances and transactions, but on the real network nothing happens (I had a balance in my wallet before)

please help me with this problem, i think this is a library bug

Thanks!!!!

**Comment by schildbach** [comment]
For support, please join our Matrix room: https://matrix.to/#/#bitcoinj:matrix.org
