### ISSUE TITLE
Old private key

### ISSUE THREAD

**Issue by xagau** [bitcoinj/bitcoinj#2074]
I have a very old private key, it has some bitcoin on it - from my bitcoinj implementation.

It looks something like this: 7b4bdb4bddd69cd62c3fXX35XX0f83302eXXXdb7f0c7dXXXXXXXX8bf5726eb75

I have X out some of the key parts to it for privacy (obviously).
When I convert it to the public Key, it is correct.
However, the next key in the sequence, the one WITH the coins on it, I also have the public and private key in the above format, however, when I convert it into a WIF format the public key does not match the actual address.

Any ideas of what might have gone wrong or how I might get the coins back since I have both the public and private keys for the coins.

Is it possible that bitcoinj "screwed up" and those coins are gone forever? It is driving me crazy as I've already spent 10+ hours on it. It is now a reasonable amount of money so I would like to get it back somehow.

Any ideas are helpful.

**Comment by schildbach** [comment]
For support, please join our Matrix room: https://matrix.to/#/#bitcoinj:matrix.org
