### ISSUE TITLE
bitcoinj generates many wallet addresses, please tell me why there are so many wallet addresses ? 

### ISSUE THREAD

**Issue by suusofttruongnv** [bitcoinj/bitcoinj#2075]
bitcoinj generates many wallet addresses, please tell me why there are so many wallet addresses ? 

This makes it difficult for me to manage my wallet addresses

Please support me, thanks !!

**Comment by schildbach** [comment]
For support, please join our Matrix room: https://matrix.to/#/#bitcoinj:matrix.org
