### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [bitcoinj/bitcoinj#2076]
Please update Bouncy Castle, new CVEs
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by schildbach** [comment]
Afaik none of the CVEs affect us. Sadly we can't update easily, because BC 1.67 introduced an unexpected backwards incompatibility.

**Comment by Polve** [comment]
Can you please elaborate on the backward incompatibility? Even a link would be welcome, thanks!

**Comment by schildbach** [comment]
Fixed via 1bcea2a59c99fe53f2eeab788eef1fd396f4b566

**Comment by Neustradamus** [comment]
@schildbach: Thanks :)
I thought of more change than that ^^

**Comment by Neustradamus** [comment]
@schildbach: Thanks :)
I thought more change than that ^^

**Comment by schildbach** [comment]
The actual change is in 7629677103dbdd80f14c63b066ed27e1fad47014.

**Comment by schildbach** [comment]
fyi: I backported the changes to 0.15.10, already released.

**Comment by Neustradamus** [comment]
@schildbach: Can you update to 1.69?
