### ISSUE TITLE
Custom Fee not working 

### ISSUE THREAD

**Issue by osamabinsaleem** [bitcoinj/bitcoinj#2087]
To make my transactions fast I want to add custom fee to it but it is not working and it is still using `REFERENCE_DEFAULT_MIN_TX_FEE` as the fee. Below is my code to add custom fee : 

```
Transaction tx2 = new Transaction(parameters);
tx2.addOutput(paymentAmount2, address2);
SendRequest request2 = SendRequest.forTx(tx2);
request2.feePerKb = Coin.valueOf(1000);

final Wallet.SendResult sendResult = bitcoinWalletKit.wallet()
		.sendCoins(bitcoinWalletKit.peerGroup(), request2);

```
I've also tried setting `request.ensureMinRequiredFee = false;` but then no fee is attached to the transaction.

**Comment by schildbach** [comment]
What tag or commit are you on?

**Comment by osamabinsaleem** [comment]
I'm on tag `0.14.7`

Here is my snippet from  pom.xml file:

```
<dependency>
	<groupId>org.bitcoinj</groupId>
	<artifactId>bitcoinj-core</artifactId>
	<version>0.14.7</version>
	<scope>compile</scope>
</dependency>
```

**Comment by schildbach** [comment]
Can you check on at least `0.15.9`? And/or on master?

**Comment by schildbach** [comment]
I'm closing this for now. I believe your issue is fixed in the current stable version. If it is not, then let us know and I'll reopen your issue.
