### ISSUE TITLE
Can we get estimatesmartfee (0.21.0 RPC) ?

### ISSUE THREAD

**Issue by A000ANB** [bitcoinj/bitcoinj#2090]
Hi,
bitcoinj version : 0.15
I want to set fee per KB as per current blockchain load for send transaction.
For example - https://bitcoincore.org/en/doc/0.21.0/rpc/util/estimatesmartfee/
`> bitcoin-cli estimatesmartfee 6`
@schildbach  Can bitcoinj provide any ways to get above ?
Thanks.

**Comment by schildbach** [comment]
This would only be possible for full nodes, but bitcoinj is not a full node. So unfortunately you've got to estimate the fee yourself.

**Comment by A000ANB** [comment]
> This would only be possible for full nodes, but bitcoinj is not a full node. So unfortunately you've got to estimate the fee yourself.

Ok. Thanks for reply.
