### ISSUE TITLE
Unable to create Segwit Addresses from xPub/yPub

### ISSUE THREAD

**Issue by LandyLane** [bitcoinj/bitcoinj#2095]
Currently, I've found no way to create an address that uses the Segwit format. Current implementation works for Legacy addresses such as:

```
String xPub = "xpub....";

Wallet wallet = Wallet.fromWatchingKeyB58(params, xPub, DeterministicHierarchy.BIP32_STANDARDISATION_TIME_SECS);

System.out.println(wallet.freshReceiveAddress().toString());
```

I've tried generating Segwit by using an online converter to convert the xPub to yPub and I get an error: 'Unknown header bytes: ypub' as the prefix changes of course.

I've seen in version .15 there was an addition to segwit and I'm hoping there exists such a function where these types of addresses can be generated from the extended public keys. However, I've failed to find any examples/code indicating how to do so.

**Comment by schildbach** [comment]
Native SegWit addresses (P2WPKH) use `zpub`.
Legacy addresses (P2PKH) use `xpub`.
`ypub` is currently unsupported.

Can you for future questions join our Matrix group: https://matrix.to/#/#bitcoinj:matrix.org
