### ISSUE TITLE
gradle 7 is not supported

### ISSUE THREAD

**Issue by AndreV84** [bitcoinj/bitcoinj#2119]
it would fail due to the depreciate maven plugin
which gradle versions are supported?

**Comment by msgilligan** [comment]
Recommended Gradle versions are documented in the README.

**Comment by AndreV84** [comment]
@msgilligan it is not an answer to the question as the readme specifies:
 Gradle 4.10+
but gradle 7.0.2 satisfies the README requirements, but fails because in 7 gradle maven is depreciated

**Comment by AndreV84** [comment]
by trial and error I found that it works e.g. with gradle 5.6 but it got obsolete already
@msgilligan Could you extend how to run the app in AVD in Android Studio once it got built, please?

**Comment by msgilligan** [comment]
Right, so the README is correct for minimum version, but obviously Gradle 7 isn't supported yet.

**Comment by AndreV84** [comment]
@msgilligan bitcoinj is a library, not an application that could be executed, right? but fo rthe terminal command line?

**Comment by schildbach** [comment]
Does anyone know if Gradle 6.8.2 still works?

**Comment by AndreV84** [comment]
@schildbach it is not like something worked but then stopped
if 6.8.2 worked it still works
it is rather like gradle dropeed the maven in 7 version but if it was presented in 6.2.8 it wil remain
Actually I could build with 6.8.2
building with it has one test failed though
```
Task :bitcoinj-core:test

org.bitcoinj.wallet.BasicKeyChainTest > bloom FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertFalse(Assert.java:65)
        at org.junit.Assert.assertFalse(Assert.java:75)
        at org.bitcoinj.wallet.BasicKeyChainTest.bloom(BasicKeyChainTest.java:261)
**6870 tests completed, 1 failed, 1299 skipped**

```

**Comment by schildbach** [comment]
So my proposal for now is we change the documentation to mention the max version.

We can migrate the Maven plugin (it is only needed for installing to the local Maven repo), if I remember right the protobuf plugin fails under Gradle 7 too.

**Comment by AndreV84** [comment]
as per  https://github.com/google/protobuf-gradle-plugin/releases
v0.8.16 is released that is compatible with Gradle 7+ as it seems to me
unless the build gets updated to use gradle 7 it will become obsolete dependency at some point that will add struggle, in my opinion

**Comment by schildbach** [comment]
See #2112

**Comment by msgilligan** [comment]
See PR #2134 and PR #2135

**Comment by msgilligan** [comment]
PR #2140 combined with a rebased #2112 should fix Gradle 7.

**Comment by msgilligan** [comment]
Gradle 7 (and JDK 16!) are now working. PR #2154 updates Github Actions to use Gradle 7 and adds JDK 16 to the matrix.
