### ISSUE TITLE
Script.ScriptType.P2WPKH sign has error

### ISSUE THREAD

**Issue by dachengcheng2022** [bitcoinj/bitcoinj#2120]
for (UTXOWrapper utxoWrapper : needUtxos) {
            TransactionOutPoint outPoint = new TransactionOutPoint(mainnetParams, utxoWrapper.getN(), Sha256Hash.wrap(utxoWrapper.getTxId()));
            Address address = Address.fromString(mainnetParams, utxoWrapper.getAddress());
//            SegwitAddress address =  SegwitAddress.fromKey(mainnetParams, ecKey);
            address.getOutputScriptType();
            Script script = null;
            if (address.getOutputScriptType() == Script.ScriptType.P2PKH) {
                script = ScriptBuilder.createP2PKHOutputScript(ecKey);
            } else if (address.getOutputScriptType() == Script.ScriptType.P2PK) {
                script = ScriptBuilder.createP2PKOutputScript(ecKey);
            } else if (address.getOutputScriptType() == Script.ScriptType.P2SH) {
                script = ScriptBuilder.createP2SHOutputScript(ecKey.getSecretBytes());
            } else if (address.getOutputScriptType() == Script.ScriptType.P2WPKH) {
                script = ScriptBuilder.createP2WPKHOutputScript(ecKey);
            } else if (address.getOutputScriptType() == Script.ScriptType.P2WSH) {
                script = ScriptBuilder.createP2WSHOutputScript(ecKey.getSecretBytes());
            }

            transaction.addSignedInput(outPoint, script, ecKey, Transaction.SigHash.ALL, true);
        }

![image](https://user-images.githubusercontent.com/21340057/120156141-4197a300-c224-11eb-946d-4e92c6ca1599.png)

this is  UTXOWrapper 
![image](https://user-images.githubusercontent.com/21340057/120156177-4eb49200-c224-11eb-8ea6-97b64642339e.png)

why has NullPointerException

**Comment by John-Smith-Dav** [comment]
I  have the problem too.
class Transaction:

![image](https://user-images.githubusercontent.com/85914351/125416102-27226e64-2d76-4da0-8117-c633acac8bed.png)

**Comment by msgilligan** [comment]
Fixed by PR #2274.
