### ISSUE TITLE
Migrate from travis-ci.org to travis-ci.com

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2144]
travis-ci.org is shutdown. (Our last build there was over 5 months ago: https://travis-ci.org/github/bitcoinj/bitcoinj/builds)

We should migrate to travis-ci.com and get those builds running again.  Migration is easy (see [Migrating repositories to travis-ci.com](https://docs.travis-ci.com/user/migrate/open-source-repository-migration)) and only requires authorization and choosing repositories.

I suppose we could decide to drop Travis CI altogether, but our current `.travis.yml` tests some configurations that Github Actions lacks. Travis CI seems to provide us with a little more flexibility in environment and configuration than Github Actions do, so I think it is worth keeping it (given how easy it is to migrate.)

**Comment by msgilligan** [comment]
See also PR #2151 (Remove Travis CI) -- which is also fine with me.

**Comment by schildbach** [comment]
I think I'd prefer to just remove it. Looking back, Travis never provided stable images which broke our build several times. Also, it is my understanding we need to pay as soon as our free contingent is used up.

**Comment by schildbach** [comment]
Fixed by removing via b8c0438da2534a6421f499f6d3b3aa88174a273a.
