### ISSUE TITLE
GitLab CI tests stopped running

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2145]
About 6 months ago our **GitLab CI** jobs stopped running.  See: https://gitlab.com/bitcoinj/bitcoinj/-/pipelines

I'm not sure why. @schildbach can you try logging in to GitLab and see what is wrong and if a simple reauthorize or "kick" will start them running again.

I think having GitLab CI working is useful and important. The main reasons are that GitLab CI is the most flexible of the three CIs we currently use (it allows you to chose from a large number of Docker images -- for example, we could actually pick a **Debian** image) and it is also the only one that is Open Source and allows self-hosting.

**Comment by msgilligan** [comment]
I'm not sure why (@schildbach did you do something?) but the tests have started running again.

They are failing, but PR #2147 (or equivalent) when finished should fix the issue.

**Comment by schildbach** [comment]
There is a simple reason: I forgot to push to GitLab for a couple of months (-:

**Comment by msgilligan** [comment]
> I forgot to push to GitLab

You can configure GitLab to pull automatically

**Comment by schildbach** [comment]
> You can configure GitLab to pull automatically

Ah, didn't know. I set this up now. Thanks!
