### ISSUE TITLE
Update the Github Actions build matrix (and how to handle new JDKs)

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2189]
We've recently merged a handful of commits that have updated the Gradle build and fixed intermittent unit test issues. We also have a GitLab CI build that builds **bitcoinj** with the built-in Debian Bullseye JDK and **Debian Gradle 4.4.1**.

We also have four outstanding PRs that affect the build matrix:

* PR #2188 (adds 3 jobs on 3 OSes)
* PR #2143 (adds 1 job on `ubuntu-latest`)
* PR #2155 (adds 1 job on `ubuntu-latest`)
* PR #2142 (removes 3 jobs on 3 OSes)

I thought I'd create an issue for us to discuss the overall strategy for the CI build matrix.

I think that all 4 of those PRs should be merged and that our extended CI matrix should be as follows:

**Main Github Actions matrix**:
* java: All supported LTS releases + Latest release (e.g. `['11', 16']` -> `['11', '17']` -> `['11', '17', '18']`)
* os: `[ubuntu-latest, macOS-latest, windows-latest]`
* gradle: latest supported (e.g. `'7.2'`)

This will be either a 2x3 or 3x3 matrix depending upon whether the latest JDK is LTS.  (Add another 3 jobs if we're going to continue to support building with JDK 8)

**Additional Github Actions cases**:

* The closest **Ubuntu** configuration to our **Debian** build
* `ubuntu-latest` with the latest Early Access JDK (`'17-ea'` -> `'18-ea'`)

**GitLab CI**:

* Our target **Debian Guidelines** compliant build (e.g. currently with **Debian Gradle** 4.4.1)
* Any other builds where we want more control over the Linux distribution and/or installed packages.

**Total Jobs**

Total = Github matrix jobs + 2 non-matrix Github jobs + 1 GitLab job

Total = (2 x 3) + 2 + 1 or (3 x 3) + 2 + 1 = 9 or 12 jobs

**NOTE**: PR #2142 will allow us to test on JDK 7 and/or JDK 8 even if they are not included in the build matrix.

The above is the goal that I have been working towards, but I'm happy to discuss any other options or strategies.

**Comment by schildbach** [comment]
I think we should pay attention that the number of combination doesn't explode. VM time is limited, at least if we want to stay in the free tiers of the CI.

JDK … I think it's a good idea to test released LTS versions. That would mean we add JDK 17 asap, but don't worry about what comes after for now. I think pre-releases (EA) can be tested – if needed – on a PR, e.g. the PR that eventually becomes the final version and is then merged. I'd rather not add them to testing on master. About released interim releases (e.g. the coming JDK 18) I'm not sure – maybe test only the latest released version.

Ubuntu/MacOS/Windows … I'm personally only interested in Linux, but if people use the other OSes we should probably continue testing them. Luckily that aspect of CI has been low maintenance lately.

Gradle … from my point of view most important is the version that is currently in Debian/Ubuntu (4.4), and as soon as we know what version will be next test that one too. Having the latest released version also doesn't hurt I guess.

The most conservative combination is currently Gradle 4.4 on Debian/Ubuntu using OpenJDK 8. Given the advantages of requiring OpenJDK 11, and based on my testing I've done in the past 1½ weeks, I think we can safely advance the requirement and thus drop OpenJDK 8 from the matrix soon.

**Comment by schildbach** [comment]
Just for the records, runtime compatibility for core is currently JDK 7 and (I guess) the Android 6 API. I think we can work towards JDK 8 and Android 7, maybe shortly after we branched for 0.16.

**Comment by msgilligan** [comment]
> VM time is limited, at least if we want to stay in the free tiers of the CI.

I don't think there is any limit to VM time CI usage for Open Source / public projects on GitHub. There are limits on the maximum number of concurrent jobs and a few other things, but we're nowhere near hitting those.

>  I think pre-releases (EA) can be tested – if needed – on a PR

That works for me.

> About released interim releases (e.g. the coming JDK 18) I'm not sure – maybe test only the latest released version.

I think we should always run tests on the latest released JDK (even if not LTS.) I don't imaging we'll have many problems, but if we do we'll want to know about them. If there's a major problem we can open an issue and disable the tests until it is fixed.
 
> Gradle … from my point of view most important is the version that is currently in Debian/Ubuntu (4.4), and as soon as we know what version will be next test that one too. Having the latest released version also doesn't hurt I guess.

Sounds good.

> The most conservative combination is currently Gradle 4.4 on Debian/Ubuntu using OpenJDK 8. Given the advantages of requiring OpenJDK 11, and based on my testing I've done in the past 1½ weeks, I think we can safely advance the requirement and thus drop OpenJDK 8 from the matrix soon.

That's great news!

**Comment by msgilligan** [comment]
> runtime compatibility for core is currently JDK 7

Note that PR #2142 contains a `testOnJdk7` task, that can be run on systems with newer Gradle. This task will download (if necessary) JDK 7 and run unit tests on that runtime.

**Comment by msgilligan** [comment]
@schildbach Temurin JDK 17 LTS is here! See PR #2208

**Comment by msgilligan** [comment]
I think this has been effectively implemented and we'll create PRs for whatever changes are needed as we progress. We can open a new issue if we need a "meta" discussion.

So, I'm going to close this.
