### ISSUE TITLE
strange behaviour while connecting to node

### ISSUE THREAD

**Issue by pdrobek** [bitcoinj/bitcoinj#2237]
Im trying to build checkpoints. Since 0.16 most recent code problem occurs.

```
2021-11-16T19:49:53Z send version message: version 70015, blocks=2950553, us=[::]:0, peer=53
2021-11-16T19:49:53Z sending verack (0 bytes) peer=53
2021-11-16T19:49:53Z receive version message: /bitcoinj:0.17-SNAPSHOT/PeerMonitor:1.0/: version 70013, blocks=0, us=127.0.0.1:8333, peer=53
2021-11-16T19:49:53Z received: sendaddrv2 (0 bytes) peer=53
2021-11-16T19:49:53Z Misbehaving: 127.0.0.1:56357 peer=53 (0 -> 1)
```

When im trying 0.15 only 5 blocks were downloaded and stuck. I can see only ping-pong messages. Nothing else.

What could be wrong?

**Comment by schildbach** [comment]
What version of bitcoind are you using? I seems to think bitcoinj is misbehaving because it receives a `sendaddrv2` message.

**Comment by pdrobek** [comment]
v0.18

**Comment by schildbach** [comment]
That's pretty old. That version doesn't support `addrv2`. I'd have to look at the spec how backwards compatiblity should be handled.

Until then, you could connect against a newer version? I think 0.21.x should be fine.

**Comment by pdrobek** [comment]
You are right, that is old stuff but tell me what version of bitcoinj should work without any problems with v0.18? mayby you know how to use old style addr messages in latest bitcoinj code or in which file i can see code responsible for addrv2 messages. Mayby i could fix it on my own side.

**Comment by schildbach** [comment]
It's not really clear to me why bitcoind is thinking bitcoinj is misbehaving. Looks like bitcoinj is behaving in conformance to the [spec](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki#signaling-support-and-compatibility) and old peers should ignore the message.

Perhaps you could try raising log levels of bitcoind to see if there is more info.

You could use bitcoinj 0.15.x (currently 0.15.10) to work around the problem. On 0.16 (or master) you could remove this line in the `Peer` class:

```
sendMessage(new SendAddrV2Message(params));
```

**Comment by schildbach** [comment]
Ultimately, I recommend you should update your Bitcoin Core to 22.0 (or later). Taproot has activated and versions below 0.21.1 do not properly verify Taproot transactions.

**Comment by pdrobek** [comment]
ok i got it :-) thx for advice. i try do my best. Please tell me are there any special requirements (in bitcoin.conf) to connect peers such bitcoinj? 

In 0.15.10 i got situation in which only 5 blocks were downloaded. After 5 blocks only ping-pong messages goes throu connection

**Comment by schildbach** [comment]
Your issue with 0.15.10 is a different issue. Can you open a new GitHub issue for this and attach your bitcoinj and bitcoind logs?

**Comment by pdrobek** [comment]
yes i can. on bitcoind side i made -debug=net but how to get more verbose logs on bitcoinj side. I know about that 5 blocks because i print it on the screen but i guess there is better way. Im using intelliJ IDEA 2021 community edition.

**Comment by schildbach** [comment]
In your code, use `BriefLogFormatter.init();` or even `BriefLogFormatter.initVerbose();`.

**Comment by pdrobek** [comment]
Ok, now i where i am :-) full logs in which i can dive in. Thank you soooooo much!

**Comment by pdrobek** [comment]
All is clear now! Problem solved!
