### ISSUE TITLE
how to make `.libs/libsecp256k1.so` 

### ISSUE THREAD

**Issue by anjurochan** [bitcoinj/bitcoinj#2241]
./configure --enable-jni --enable-experimental --enable-module-schnorr --enable-module-ecdh
 
 it doesn't work

**Comment by schildbach** [comment]
What's happening?

**Comment by anjurochan** [comment]
i want to make libsecp256k1.so

**Comment by msgilligan** [comment]
Did you have any luck with this?

@schildbach Is anything or anyone testing this regularly?

**Comment by schildbach** [comment]
Also see #2267

**Comment by schildbach** [comment]
I'm afraid we don't have the capacity to support libsecp256k1.so any further and will remove its native interface from bitcoinj for now. I recommend to use Bouncy Castle instead, until we can (maybe!) in future offer different implementations.

**Comment by msgilligan** [comment]
Note that we have a new project to create a secp256k1 API for Java/JDK, see https://github.com/bitcoinj/secp256k1-jdk
