### ISSUE TITLE
Could not deserialize transactions containing P2TR addresses correctly

### ISSUE THREAD

**Issue by henta** [bitcoinj/bitcoinj#2242]
My sdk-version:Master or 0.16.1
I use the following code to deserialize：

 byte[] txhex = Utils.HEX.decode("0100000001515c948db912aba3eeb89fe5f2c1fa949703f38f0314720a7ec6f37ae17578d400000000fdfe0000483045022100a6da1d1afdd0eaa9972dbe5fd97d90dc0042ba8259492f5fccf5ac61589a42bb0220113d96faa2b75a36a07da38ad15b0a58d42c7fc6b7e5f946f9e36e89ac5af065014830450221008b59d8e27ae4cf9d4f37bc6a81601922c8bd872fde57c57e0eed9e26c9320dcc022056732bb4ea933b47c3ee09c1b05881ff059fe6790a26bd99a957fd68f13e7968014c69522102b09c72ee2fa77abc24613b227d1cb6944c70af7f96711d5f1c4675daaa7554d221029787faf77569cdc59db5a34e0e9f552b9950b61d593e797ae12ac1d69eb5f98821022e9df5da07c71f7e8f5f639a28900d967714f2ae72b096c69c93fd76837b01a753aeffffffff0210270000000000002251200000000000000000000000000000000000000000000000000000000000000000cc3201000000000017a914d06f57927ef98f7dfd25e9abdf5de65e1e7215698700000000");

Transaction tx = new Transaction(TESTNET, txhex);`

The resolved address format is unknown like the picture  and the correct type should be P2TR
![image](https://user-images.githubusercontent.com/18660021/142844990-7c879f25-b7bc-47d3-9b8e-736445659786.png)

**Comment by schildbach** [comment]
Is this txn on the testnet blockchain? If yes, can you provide a txid?

**Comment by schildbach** [comment]
Txid is c296a2269fcca6da5125b50d74bfa022749a72a29abf111ea66cfd007eca4d37

Can you show the code you actually use for printing the address? A tx.toString() yields the correct address for me: tb1pqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkgkkf5

**Comment by schildbach** [comment]
Fixed via 04378aa6389deb5143f66cf2ab0abec52dc9d394. This is a purely cosmetic error in toString(), so no need to worry. I will backport the fix to 0.16.

**Comment by henta** [comment]
> Fixed via [04378aa](https://github.com/bitcoinj/bitcoinj/commit/04378aa6389deb5143f66cf2ab0abec52dc9d394). This is a purely cosmetic error in toString(), so no need to worry. I will backport the fix to 0.16.

Great,I tried this fix and it worked
