### ISSUE TITLE
Migrate from Guava ListenableFuture to JDK8+ CompletableFuture

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2254]
(This is an expansion of Issue #2101 to include all usage of `ListenableFuture` in the **bitcoinj** API to `CompletableFuture`.)

`CompletableFuture` is the JDK 8 equivalent of Guava's `ListenableFuture` and now that `bitcoin-core` is using JDK 8/Android API 24, we should convert all usage of `ListenableFuture` in our API to `CompletableFuture`. I propose doing this in two steps:

1. Replace all returns of `ListenableFuture` with `ListenableCompletableFuture` which is a subclass of `CompletableFuture` that implements the `ListenableFuture` interface. This will be backward-compatible, but allow clients to migrate to `CompletableFuture`.  Targeted for bitcoinj 0.17 release.  (`ListenableCompletableFuture` will probably be marked as `@Deprecated` since it will be removed in a future release)

2. Replace `ListenableCompletableFuture` with `CompletableFuture` (proposed for bitcoinj 0.18 release)

I'll be submitting a PR with implementation of `ListenableCompletableFuture` and conversion of `AbstractBlockChain` to use this class shortly.

**Comment by schildbach** [comment]
That sounds like a good migration strategy to me.

**Comment by schildbach** [comment]
I just noticed I should have commented this here:

Looks like we need replacements for the various `Futures` helpers. There is a [nice cheat sheet](https://gist.github.com/kofemann/a721af324f8c35f6e9840f583ca40f05), but the replacement methods operate on `CompletableFuture` not `ListenableCompletableFuture`.

**Comment by msgilligan** [comment]
> [nice cheat sheet](https://gist.github.com/kofemann/a721af324f8c35f6e9840f583ca40f05), but the replacement methods operate on `CompletableFuture` not `ListenableCompletableFuture`.


* All of the methods that operate on a `CompletableFuture` instance, (`future` in the cheat sheet) will work on `ListenableCompletableFuture`.
* The two entries in the table that call `new CompletableFuture()` constructor will need to use `new ListenableCompletableFuture()`
* We can add a `static` method `ListenableCompletableFuture.completedFuture(value)`

I don't think we need to create static/factor methods for these cases just change the code as is described in the cheat sheet.

**Comment by msgilligan** [comment]
> I don't think we need to create static/factory methods for all these cases just change our code as to use the inline code in the right column of the cheat sheet.

Although, if we do it might make it easier when we:

> Replace ListenableCompletableFuture withCompletableFuture (proposed for bitcoinj 0.18 release)

**Comment by msgilligan** [comment]
> I don't think we need to create static/factory methods for all these cases just change our code as to use the inline code in the right column of the cheat sheet.

I've discovered that in some cases we do need these static/factory methods because (during the migration period) we need to create `ListenableCompletableFuture`s not `CompletableFuture`s.

**Comment by msgilligan** [comment]
Work has started, See:

* PR #2255
* PR #2291
* PR #2294
* PR #2295
* PR #2296

**Comment by msgilligan** [comment]
It's also worth mentioning that some useful migration may be in PR #2105.

**Comment by msgilligan** [comment]
As of 94451e69847d018a7d98692edfa1e2bb584f2557 `SettableFuture` has been entirely removed from the code.  `ListenableFuture` has been replaced with `CompletableFuture` and `ListenableCompletableFuture`.
