### ISSUE TITLE
Bech32 validation issue with v0.16.1

### ISSUE THREAD

**Issue by MrLouzao** [bitcoinj/bitcoinj#2262]
After the upgrade from version 0.15.5 to 0.16.1, some address validations started to fail for previous valid bech32 addresses.

This is a valid bech32 address referenced in the [BIP0173](https://gist.github.com/foomin10/a7fc324a7ba373a7de224982355d8dbb) in the list of test vectors:

`bc1zw508d6qejxtdg4y5r3zarvaryvg6kdaj`

This is the exceptions raised in the `Address` class, method `fromString(..)`:

```
 org.bitcoinj.core.AddressFormatException$UnexpectedWitnessVersion: Unexpected witness version: 2
```

Reviewing the code, this bech32 address is retrieving a witness 2, that is calculated like that in the v0.15.5, but passing the validations.

Checking the code in version 0.15.5, this address has a witness 2 and passes this validation:

```
// Check script length for version 0
        if (witnessVersion == 0 && witnessProgram.length != WITNESS_PROGRAM_LENGTH_PKH
                && witnessProgram.length != WITNESS_PROGRAM_LENGTH_SH)
            throw new AddressFormatException.InvalidDataLength(
                    "Invalid length for address version 0: " + witnessProgram.length);
```

But in the case of version 0.16.1, the following validation is applied and not passing:

```
 if ((witnessVersion == 0 && bechData.encoding != Bech32.Encoding.BECH32) ||
                (witnessVersion != 0 && bechData.encoding != Bech32.Encoding.BECH32M))
            throw new AddressFormatException.UnexpectedWitnessVersion("Unexpected witness version: " + witnessVersion);
```

Is this an issue with the library or the [BIP0350](https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki#test-vectors-for-v0-v16-native-segregated-witness-addresses) invalidates certain addresses considered valid in the [BIP0173](https://gist.github.com/foomin10/a7fc324a7ba373a7de224982355d8dbb)?

This behaviour is also replied in other addresses that were considered as fine in the 0.15.5. 

Thanks!

**Comment by schildbach** [comment]
If I understand https://github.com/bitcoin/bips/blob/master/bip-0350.mediawiki#compatibility correctly, that address has indeed been declared invalid. The old BIP173 test vectors have been replaced by new BIP350 vectors via commit 183986c9801f10f1bf46bd46621e535973d39ef8.

**Comment by MrLouzao** [comment]
Reading the BIP-0350 as you say, seems like by protocol this addresses are going to be rejected by the network as the validation now is marking as not valid. I'm going to close this issue then. Thank you.
