### ISSUE TITLE
Received Reject: verack  for reason 'a verack message must follow version' (1)

### ISSUE THREAD

**Issue by cooperx7** [bitcoinj/bitcoinj#2508]
./wallettool/build/install/wallet-tool/bin/wallet-tool --net=TEST --wallet=$HOME/bitcoinj/bitcoinj-test.wallet sync
7月 05, 2022 8:40:19 下午 org.bitcoinj.core.Peer processMessage
严重: Peer{[100.38.243.170]:18333, version=70013, subVer=/btcwire:0.5.0/btcd:0.22.0/, services=77 (NETWORK, BLOOM, WITNESS, remaining: 1000000), time=2022-07-05 20:40:18, height=2284207} /btcwire:0.5.0/btcd:0.22.0/: Received Reject: verack  for reason 'a verack message must follow version' (1)

**Comment by schildbach** [comment]
This appears to be a misbehaving peer. However wallet-tool will connect to multiple peers and use the ones that behave well.
