### ISSUE TITLE
java.lang.IllegalStateException: Expected the service WalletAppKit [FAILED] to be RUNNING, but the service has FAILED

### ISSUE THREAD

**Issue by pmrzygweb** [bitcoinj/bitcoinj#2641]
I upgrade the library from 0.14.4 to 0.16.1 and kit's awaitRunning threw the error.
java.lang.IllegalStateException: Expected the service WalletAppKit [FAILED] to be RUNNING, but the service has FAILED

Nothing has been changed in the code of initialization.

```
params = MainNetParams.get();
kit = new WalletAppKit(params, fp, "walletappkit");
kit.setBlockingStartup(false);
kit.startAsync();
kit.awaitRunning();
```

Can you please help what's wrong with?

**Comment by pmrzygweb** [comment]
Can I get a response?

**Comment by pmrzygweb** [comment]
@msgilligan Can you please advise?

**Comment by msgilligan** [comment]
Hi @pmrzygweb I'm sorry you're having trouble.

In general, you can't expect a response here in less than 1 business day, so it is not helpful to comment multiple times until you get a response.

You can ask for community help in our Matrix room: https://matrix.to/#/#bitcoinj-users:matrix.org and you will likely get a quicker response there.

To report a bug, it is best to provide a complete one-file application that reproduces the problem. You should also let us know the OS version and Java version that you are using.

There are many apps that use the basic functionality that you are using, so to resolve your problem you're going to need to figure out what is different or specific to your use case. The likely problem is that something is throwing an exception in the `startUp()` method or WalletAppKit. Here are few suggestions that you can try to narrow this down.

1. Create a single-file reproducer app as suggested above.
2. Make sure logging is enabled and look at log messages.
3. Set a debugger breakpoint in `startUp()` and step through the code
4. Try running your app with 0.17-SNAPSHOT by checking out and building the `master` branch.

**Comment by pmrzygweb** [comment]
@msgilligan Thanks for your reply.
The problem is that above code works well with the library 0.14.4 but threw exception with 0.16.1.
I want to know if this code needs to be updated to be working or it would be hardware issue.

**Comment by msgilligan** [comment]
I see you joined Matrix, let's continue the discussion there.
