### ISSUE TITLE
Wallet sync not working correctly on MAINNET

### ISSUE THREAD

**Issue by abhaygupta1999** [bitcoinj/bitcoinj#2651]
Hi all,
So, I am using my bitcoin wallet with P2WPKH script on MAINNET using a mnemonic. But when I try to resync the whole wallet again with same mnemonic again from start, all transactions are not syncing correctly. The balance in the new one is less than the old wallet. 
Please can anyone suggest how to solve this issue?

**Comment by schildbach** [comment]
Without logs and maybe a wallet dump this there is hardly anything we can do.

Can you join our Matrix space, maybe we can support you there?
https://bitcoinj.org/#community

**Comment by abhaygupta1999** [comment]
Hi.
So, I have found the issue. It was because the default lookaheadsize is 100, but in my wallet I have indexes upto 3000.
So, after setting lookaheadsize of 10000 in keychain group, wallet sync works fine.
But the sync time increased a lot.

**Comment by schildbach** [comment]
Ok, great to hear you've found out what the problem it. Yes, those gaps in address usage cannot exceed the lookahead. Anyway, thanks for letting us know.
