### ISSUE TITLE
SPV block store file hangs at size of 1281024 bytes

### ISSUE THREAD

**Issue by ivandavidov** [bitcoinj/bitcoinj#2652]
Here is my code where I'm trying to get the balance for a specific address which I successfully derived from a private key:

```
        String inputPrivateKeyEncrypted = "*****";
        String inputPass = "*****";

        NetworkParameters params = MainNetParams.get();

        BIP38PrivateKey bip38PrivateKey = BIP38PrivateKey.fromBase58(params, inputPrivateKeyEncrypted);
        ECKey privateKey = bip38PrivateKey.decrypt(inputPass);

        Wallet wallet = Wallet.createDeterministic(params, Script.ScriptType.P2PKH);
        wallet.importKey(privateKey);

        BlockStore blockStore = new SPVBlockStore(params, new File("./spv.store"));
        BlockChain blockChain = new BlockChain(params, wallet, blockStore);

        PeerGroup peerGroup = new PeerGroup(params, blockChain);
        peerGroup.setBloomFilteringEnabled(true);
        peerGroup.start();     // Also tried with startAsync()
        peerGroup.downloadBlockChain();

        Coin coin = wallet.getBalance();
        System.out.println(coin.toFriendlyString());
```

The issue is that when I invoke ``peerGroup.downloadBlockChain();`` the code execution blocks (as expected) but the file ``spv.store`` is generated with size of 1281024 bytes and this size never goes up even after waiting for over an hour. No errors, no exceptions, nothing. Therefore, I never get to the point where the code checks the balance. And if I don't download the blockchain, then I get a balance of zero.

I tried optimizing the blockchain download by enabling bloom filtering but nothing changed.

I am using bitcoinj-core 0.16.1

I am interested in only one particular address and (at least for now) I am interested in only getting the latest available balance which I know is non-zero.

So, any suggestions?

**Comment by schildbach** [comment]
It won't go up, it's a rolling store. See the class-level JavaDoc.
