### ISSUE TITLE
Send Transaction and check Balance without Download blockChain 

### ISSUE THREAD

**Issue by saeedishayan76** [bitcoinj/bitcoinj#2672]
hi i want to create a bitcoin wallet and send transaction or check balance , if i wait for download SPV block Store or use block chain it takes 20-40 minutes , But I don't want this, in many example i saw the sign transaction offline with UTXO , how to get utxo from a wallet or how to pass it to my wallet ? im use version 0.16.2

here is my sample :

    val words = arrayListOf<String>(
            "sister", "proof" ,"spare", "miracle", "write", "hero" ,"cargo" ,"rigid" ,"remain" ,"bulb", "elevator" ,"beauty"
        )
        val menmonic = "sister proof spare miracle write hero cargo rigid remain bulb elevator beauty"
        val params = TestNet3Params.get()

        val seed = DeterministicSeed(menmonic, null, "", System.currentTimeMillis())

        val wallet = Wallet.fromSeed(params, seed, Script.ScriptType.P2PKH)

for send transaction im using the sendRequest class but i get error insufficiency Money but i have 0.010 btc in  testnet 3 my address that created by bitcoinJ wallet .

**Comment by msgilligan** [comment]
You can't check balance with an SPV (or full or pruned node) wallet without downloading a block store. You could use some kind of centralized wallet API server to do that.

To send a transaction without a chain download you could use `PeerGroup.broadcastTransaction` but you would be doing so without some of the validation (e.g. insufficient money check) that you get when using a full wallet.

If you have any further questions please ask on the mailing list or in our Matrix room: https://bitcoinj.org/#community

@schildbach You can close this issue.
