### ISSUE TITLE
SegwitAddress: Store witnessProgram in 8-bit bytes (not 5-bit bytes)

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2697]
Currently the `SegwitAddress` class stores the `witnessProgram` in a partially-converted-to-Bech32 format that is:

1. non-standard
2. not very useful
3. confusing to maintainers (and is currently making the Bech32 class hard to use for general Bech32 encoding/decoding)
4. requires slightly more storage space.

The Bech32 encoding of binary data can be viewed as a two-step process:

1. Convert from an arbitrary byte-array (where each `byte` can contain any value) to a 8/5 larger byte-array where each `byte` only contains values from 0-32 (5-bits.)  This is currently done by the calling: `convertBits(witnessProgram, 0, witnessProgram.length, 8, 5, true)`
2. Convert each 5-byte value to a valid Bech32 ascii character using a string/array containing: `"qpzry9x8gf2tvdw0s3jn54khce6mua7l"`.

The current `SegwitAddress(Network network, int witnessVersion, byte[] witnessProgram)` constructor, performs step1 1 of the Bech32 conversion (using `convertBits`) on the `witnessProgram` and stores the results in the `byte[] bytes` array in `Address`. I propose removing this step and instead just pre-pending the `witnessProgram` to a `byte` representation of `witnessVersion`.

This will require internal conversion changes in the following places:

1. `getWitnessProgram()` - this method currently must convert from the 5-bit format back to the 8-bit format. With the proposed change, this conversion can be removed.
2. `toBech32()` - this method currently performs step 2 of the Bech32 conversion and would be modified to perform step 1 and step 2.
3. There is also a conversion back to 8-bit format in the constructor (for witness length validation) that would be unnecessary with the proposed change.

Note that the proposed change would affect the Java hash of `SegwitAddress` instances, but I don't think we are providing an API-level guarantee that this will be unchanged between versions.

Related PR: https://github.com/bitcoinj/bitcoinj/pull/1840 I think this PR had a good idea and its current status is that it needs rebasing and a new review. #1840 differs slightly from what I am proposing in that it removes the `witnessVersion` from `byte[] bytes` in the `Address` superclass and adds `private final int witnessVersion` to the `SegwitAddress` subclass. My recommendation is that we implement the change from 5-bit to 8-bit representation first and then separately consider removing `witnessVersion` from `byte[] bytes`.

**Comment by schildbach** [comment]
> and instead just pre-pending the `witnessProgram` to a `byte` representation of `witnessVersion`

So the `witnessVersion` is unchanged?

> Note that the proposed change would affect the Java hash of `SegwitAddress` instances

I don't see any problem with that.

Sounds good. I think I coded it this way because I was under the impression `toBech32` is called a lot and I wanted to cache the conversion into groups.

**Comment by msgilligan** [comment]
See PR #2745. (it is part of a chain of PRs that decouple `Address`/`LegacyAddress`/`SegwitAddress`, but it's the one that converts from 5 to 8 bits internally)

**Comment by msgilligan** [comment]
PR #2745 has been merged. Closing.
