### ISSUE TITLE
Blockchain download from peer stuck

### ISSUE THREAD

**Issue by abhaygupta1999** [bitcoinj/bitcoinj#2806]
I have setup my own node in AWS, and use that only in peer group. Like below:
peerGroup.addAddress(InetAddress.getByName(host));
peerGroup.setMaxConnections(1);

But it got stuck, and not downloading new blocks of data. Can anyone please help me here? I was debugging from this morning, but can't able to find the issue. 

Here are the logs:
org.bitcoinj.core.Peer : Peer{[10.17.10.55]:8333, version=70015, subVer=/Bitcoin Cash Node:24.0.0(EB32.0)/, services=1061 (NETWORK, BLOOM, NETWORK_LIMITED, remaining: 100000), time=2023-03-14 11:21:53, height=783873}: Too many pending pings, disconnecting
org.bitcoinj.core.PeerGroup : [10.17.10.55]:8333: Peer died (2 connected, 0 pending, 1 max)
org.bitcoinj.core.PeerGroup : Download peer died. Picking a new one.
org.bitcoinj.core.PeerGroup : Unsetting download peer: Peer{[10.17.10.55]:8333, version=70015, subVer=/Bitcoin Cash Node:24.0.0(EB32.0)/, services=1061 (NETWORK, BLOOM, NETWORK_LIMITED, remaining: 100000), time=2023-03-14 11:21:53, height=783873}
org.bitcoinj.core.PeerGroup : Setting download peer: Peer{[10.17.10.55]:8333, version=70015, subVer=/Bitcoin Cash Node:24.0.0(EB32.0)/, services=1061 (NETWORK, BLOOM, NETWORK_LIMITED, remaining: 100000), time=2023-03-14 11:21:53, height=783873}
o.b.c.listeners.DownloadProgressTracker : Chain download switched to Peer{[10.17.10.55]:8333, version=70015, subVer=/Bitcoin Cash Node:24.0.0(EB32.0)/, services=1061 (NETWORK, BLOOM, NETWORK_LIMITED, remaining: 100000), time=2023-03-14 11:21:53, height=783873}
org.bitcoinj.core.PeerSocketHandler : [10.17.10.55]:8333 - java.nio.channels.CancelledKeyException
c.PeerGroup$ChainDownloadSpeedCalculator : 0 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, avg/last 0.00/0.00 kilobytes per sec, chain/common height 769180/783874, stall disabled (threshold <0.78 KB/sec for 10 seconds)

And then below log groups keeps on coming with waiting time increasing.

org.bitcoinj.core.PeerGroup              : [10.17.10.55]:8333: Peer died      (0 connected, 0 pending, 1 max)
org.bitcoinj.core.PeerGroup              : Peer discovery took 3.630 ?s and returned 0 items from 0 discoverers
org.bitcoinj.core.PeerGroup              : Waiting 600066 ms before next connect attempt to [10.17.10.55]:8333

@schildbach Please see if you have time. Its a PROD issue. An urgent help will be much appreciated.

**Comment by schildbach** [comment]
You've already posted this to the mailing list, but please see this link for our Matrix space and the mailing list:
https://bitcoinj.org/#community
