### ISSUE TITLE
Replace usage of com.google.c.b.Preconditions

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2811]
This is one of the few remaining usages of Guava in the `base` and `crypto` packages (modules in 0.18)

There are (at least) three possible ways we can do this:

1. Create our own (internal?) `Preconditions` utility class that is a subset of the Guava class
2. Create our own replacement class with a different name and/or method names
3. Do direct validation of parameters in each method with: `if (! test) { throws new Illegal[Argument|State]Exception (message + badparameteror) }` and `Object.requireNonNull()`, etc.

I suppose we could also do 1 or 2 as a refactoring and then deprecate the internal class/methods and migrate towards number 3.

**Comment by schildbach** [comment]
What end result would you favor?

**Comment by msgilligan** [comment]
It looks like we've decided to use `Object.requireNonNull()` and our new, "internal" `o.b.base.internal.Preconditions` class.

See merged PR #2819 and PR #2817.

**Comment by msgilligan** [comment]
@schildbach Can you make a PR to use `o.b.base.internal.Precondition` in the `crypto` package/module, too?

**Comment by schildbach** [comment]
See #2824.

**Comment by msgilligan** [comment]
Fixed by PR #2824
