### ISSUE TITLE
Rename `Transaction.estimateLockTimeInstant()`?

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#2812]
I think this would be better named something like `estimateFinality`or `estimateUnlockTime`, because we are not estimating a `LockTime` value -- we are estimating when the condition will be satisfied, which is slightly different.

This would also allow us to remove the somewhat redundant `Instant` from the name.

**Comment by schildbach** [comment]
Fixed via e11fa0686f62ec6da2644586aa7df829863704be.

Though in all honesty, even the `LockTime` class doesn't specify a lock time but an unlock time…
