### ISSUE TITLE
Grammatical error on the website

### ISSUE THREAD

**Issue by aland1298** [bitcoinj/bitcoinj#2816]
![image](https://user-images.githubusercontent.com/57577639/225506076-9be50330-15e8-48ca-8250-4582d669f74f.png)

Should be _may_ not _many_

**Comment by schildbach** [comment]
Good catch, thanks! I fixed this.

Btw. the website is on GitHub at https://github.com/bitcoinj/bitcoinj.github.io – you could fix wording errors like this in a pull request directly on GitHub.
