### ISSUE TITLE
BitcoinURI: Discover (via Service Loader mechanism) the correct Network from the URI string

### ISSUE THREAD

**Issue by schildbach** [bitcoinj/bitcoinj#2887]
There is a TODO in BitcoinURI, which actually breaks my app for any non-mainnet.

```
// TODO: Discover (via Service Loader mechanism) the correct Network from the URI string
```

**Comment by schildbach** [comment]
For the records, my 0.16-based code uses `new BitcoinURI(null, uri);` with uri coming from a QR code, link or similar. The idea is it should let the class detect the network.

Two problems:

1. When used with `null` like above, the compile now cannot decide between the two overloads and crashes (!).
2. When I cast `(NetworkParameters) null` or use the suggested method from the deprecation notice, that one doesn't detect the network but has mainnet hardcoded.

**Comment by schildbach** [comment]
https://github.com/bitcoinj/bitcoinj/pull/2898 will help with case 1 above.

**Comment by msgilligan** [comment]
PR #3041 will help with solving problem 2 above.

**Comment by schildbach** [comment]
I believe both of the above have been fixed.
