### ISSUE TITLE
BTC transaction not broadcasting to mempool

### ISSUE THREAD

**Issue by abhaygupta1999** [bitcoinj/bitcoinj#3095]
I have created a BTC transaction in MAINNET with 4 sat/vByte as fee. A transaction is created by bitcoinj wallet, and also got the log of "broadcasting txHash to mempool", but this transaction never went to mempool. The network fee of this transaction was around 2000 satoshis.

But when I created the same transaction with 37 sat/vByte, the transaction is broadcasted and a network fee of 5028 satoshis occur.

The code is same, the node I am using is also inhouse with latest bitcoin-core version. I am not getting what exactly is being wrong here. Please help me out.

**Comment by msgilligan** [comment]
Try running this with a local **Bitcoin Core** node. Send it a `logging '["mempoolrej"]'`  RPC message and `tail -f` the log. Then send it your transaction.

If you think this is a **bitcoinj** issue, you'll need to provide us with more information including:
1. The version of bitcoinj
2. Extracted, simplified code that reproduces the issue
3. The transactions in question in hex, JSON, and/or bitcoinj toString (log) format.

**Comment by abhaygupta1999** [comment]
Hi @msgilligan 
This is the log I got: 
2023-05-24T07:41:49Z [mempoolrej] 7ba2957bf8eb243dac0dd40f6f1450c9e0a934334fa7205eb743c2ff02dee0b5 from peer=124061 was not accepted: mempool min fee not met, 144 < 1521

So, it means the transaction is broadcasted from bitcoinj, but this rejection error is not handled by bitcoinj. So, the transaction remains in bitcoinj wallet, but it does not exist in mempool.

The bitcoinj version I am using is: v0.16.1

1. Please help me here.
2. Also, 144 is the network fee from my transaction, where does this 1521 coming from. Also, I see for different transactions this threshold limit is changing. Do you know why?

**Comment by abhaygupta1999** [comment]
Thanks @msgilligan
