### ISSUE TITLE
Peer discovery error [NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException  java.nio.channels.CancelledKeyException

### ISSUE THREAD

**Issue by arnabmitra** [bitcoinj/bitcoinj#3119]
Hi, i have a very simple application using TestNet, If i use version 0.15.6 i get this error but it is not very frequent, very occasional,
However anything above 0.15.7 it will basically stall 

``` [NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[5.75.250.210]:18333, version=70016, subVer=/Satoshi:22.0.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2023-06-30 17:46:07, height=2439826}
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[5.75.250.210]:18333, version=70016, subVer=/Satoshi:22.0.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2023-06-30 17:46:07, height=2439826}: New peer      (5 connected, 0 pending, 12 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[5.75.250.210]:18333, version=70016, subVer=/Satoshi:22.0.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2023-06-30 17:46:07, height=2439826}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [5.75.250.210]:18333: Peer died      (4 connected, 0 pending, 12 max)
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
        at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
        at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
        at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:245)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50)
        at java.base/java.lang.Thread.run(Thread.java:829)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1001 ms before next connect attempt to [35.214.213.127]:18333
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [2001:67c:16dc:1202:5054:ff:fe64:f426]:18333
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [2001:41d0:303:146e:0:0:0:0]:18333     (4 connected, 1 pending, 12 max)
[PeerGroup Thread] WARN org.bitcoinj.core.PeerGroup - Failed to connect to [2001:41d0:303:146e:0:0:0:0]:18333: Network is unreachable
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - [2001:41d0:303:146e:0:0:0:0]:18333: Peer died      (4 connected, 0 pending, 12 max)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1500
```
I am assuming i a doing something wrong but the release note from 0.15.7 maybe indicate something did change with peer discovery ? 
```
Version 0.15.7
This is a bug fix / maintenance release:

Introduce a peer priority for connecting and being picked as for chain download.
Implement service bit filtering for DnsDiscovery.
When a transaction is broadcast, peers being broadcasted to are disconnected afterwards. Others will take their place. This improves privacy and avoids rarely tested code paths.
```

Not much going on with my code just a simple start 
```
 kit = new WalletAppKit(params, Script.ScriptType.P2PKH, null, new File("/tmp/"), filePrefix)
 kit.restoreWalletFromSeed(seed);
 kit.startAsync();
 kit.awaitRunning();
```
Can anyone help why anything >0.15.7 would just stall?

**Comment by msgilligan** [comment]
Try this:
```
    kit.setBlockingStartup(false);  // Don't wait for blockchain synchronization before entering RUNNING state
    kit.startAsync();               // Connect to the network and start downloading transactions
    kit.awaitRunning();             // Wait for the service to reach the RUNNING state
    kit.peerGroup().setMaxConnections(4);
```

**Comment by schildbach** [comment]
The `CancelledKeyException` itself is harmless. This happens if a remote peer drops the connection in a non-standard way (or network disconnection).

**Comment by Bigjohn2396** [comment]
kit = new WalletAppKit(params, Script.ScriptType.P2PKH, null, new File("/tmp/"), filePrefix)
 kit.restoreWalletFromSeed(seed);
 kit.startAsync();
 kit.awaitRunning();    kit.setBlockingStartup(false);  // Don't wait for blockchain synchronization before entering RUNNING state
    kit.startAsync();               // Connect to the network and start downloading transactions
    kit.awaitRunning();             // Wait for the service to reach the RUNNING state
    kit.peerGroup().setMaxConnections(4);

**Comment by Bigjohn2396** [comment]
kit.setBlockingStartup(false);  // Don't wait for blockchain synchronization before entering RUNNING state
    kit.startAsync();               // Connect to the network and start downloading transactions
    kit.awaitRunning();             // Wait for the service to reach the RUNNING state
    kit.peerGroup().setMaxConnections(4);

**Comment by Bigjohn2396** [comment]
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - Peer{[5.75.250.210]:18333, version=70016, subVer=/Satoshi:22.0.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2023-06-30 17:46:07, height=2439826}: New peer      (5 connected, 0 pending, 12 max)
[NioClientManager] INFO org.bitcoinj.core.Peer - Peer{[5.75.250.210]:18333, version=70016, subVer=/Satoshi:22.0.0/, services=1033 (NETWORK, WITNESS, NETWORK_LIMITED), time=2023-06-30 17:46:07, height=2439826}: Peer does not support bloom filtering.
[NioClientManager] INFO org.bitcoinj.core.PeerGroup - [5.75.250.210]:18333: Peer died      (4 connected, 0 pending, 12 max)
[NioClientManager] WARN org.bitcoinj.net.ConnectionHandler - Error handling SelectionKey: java.nio.channels.CancelledKeyException 
java.nio.channels.CancelledKeyException
        at java.base/sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:71)
        at java.base/sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:130)
        at java.base/java.nio.channels.SelectionKey.isWritable(SelectionKey.java:377)
        at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:245)
        at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:86)
        at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:122)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:66)
        at com.google.common.util.concurrent.Callables$4.run(Callables.java:121)
        at org.bitcoinj.utils.ContextPropagatingThreadFactory$1.run(ContextPropagatingThreadFactory.java:50)
        at java.base/java.lang.Thread.run(Thread.java:829)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1001 ms before next connect attempt to [35.214.213.127]:18333
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1000 ms before next connect attempt to [2001:67c:16dc:1202:5054:ff:fe64:f426]:18333
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Attempting connection to [2001:41d0:303:146e:0:0:0:0]:18333     (4 connected, 1 pending, 12 max)
[PeerGroup Thread] WARN org.bitcoinj.core.PeerGroup - Failed to connect to [2001:41d0:303:146e:0:0:0:0]:18333: Network is unreachable
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - [2001:41d0:303:146e:0:0:0:0]:18333: Peer died      (4 connected, 0 pending, 12 max)
[PeerGroup Thread] INFO org.bitcoinj.core.PeerGroup - Waiting 1500

**Comment by arnabmitra** [comment]
> Try this:
> 
> ```
>     kit.setBlockingStartup(false);  // Don't wait for blockchain synchronization before entering RUNNING state
>     kit.startAsync();               // Connect to the network and start downloading transactions
>     kit.awaitRunning();             // Wait for the service to reach the RUNNING state
>     kit.peerGroup().setMaxConnections(4);
> ```

thanks that does get the chain moving, still see a lot of `CancelledKeyException` but at least it catches up.
