### ISSUE TITLE
Enable Gradle Build Scans on GitHub Actions

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#3238]
[Gradle Build Scans](https://gradle.com/gradle-enterprise-solutions/build-scan-root-cause-analysis-data/) are a nice feature of Gradle Enterprise that are available for free to open source projects that build with Gradle. When troubleshooting build failures they provide a wealth of easily navigated information that can be very handy.

Unfortunately given that our build needs to support Gradle 4.4.x through Gradle 8.3 (as of today) it is not easy to configure the Gradle Enterprise plugin to work across that range of Gradle versions.  (See PR #3130 and PR #3213)

As mentioned in https://github.com/bitcoinj/bitcoinj/pull/3130#issuecomment-1703345198 our best approach is to use a new feature of the GitHub Gradle Plugin called [Gradle Enterprise Plugin Injection](https://github.com/gradle/gradle-build-action/blob/v2.8.0/README.md#gradle-enterprise-plugin-injection).  Unfortunately, I was unable to figure out how to get the _access key_ needed to configure it. I created an issue in the GitHub Gradle Plugin project asking for clarification (see https://github.com/gradle/gradle-build-action/issues/870.)

I'm opening this issue so we don't forget to follow up on this and so I can close PR #3130 and PR #3213.

**Comment by msgilligan** [comment]
Update: We may not need "Gradle Enterprise Plugin Injection" or an access key. We can just add `--scan` to the `gradle` command used by CI. However, I couldn't get this to work because apparently there is **no way to agree to the Terms of Service** without installing the Enterprise Plugin.

**Comment by msgilligan** [comment]
In addition to the issue I opened on the Gradle Build Action, I opened an issue on Gradle itself (since the `--scan` option is built-in): https://github.com/gradle/gradle/issues/26316

**Comment by msgilligan** [comment]
The documentation for the Gradle Build GitHub Action has been updated.  See https://github.com/gradle/gradle-build-action/issues/870 -- This does not resolve the issue but does confirm what I had already suspected.

Still waiting for a response on https://github.com/gradle/gradle/issues/26316

**Comment by msgilligan** [comment]
We got a response from Stefan Wolf at Gradle: https://github.com/gradle/gradle/issues/26316#issuecomment-1739245349

I have made two PRs using  the suggested init script:

* PR #3289
* PR #3290

**Comment by msgilligan** [comment]
PR #3289 and PR #3290 have both been merged. Closing...

**Comment by schildbach** [comment]
Note that I've merged these two on the assumption that build scans are useful to devs. Should that cease to be the case I'm happy to revert sooner rather than later.
