### ISSUE TITLE
Something in PBKDF2SHA512.java confuse me

### ISSUE THREAD

**Issue by dice36D** [bitcoinj/bitcoinj#3244]
I'm learning BIP definitions lately and following this code to know how the specs becomes code logic.
This probably not effect any execution result, but I would like to ask: "Why hLen in method derive() is set to 20?"
By RFC document, it is length in octets of pseudorandom function output. And HMACSHA512 output should not just 20 octets, right?

**Comment by msgilligan** [comment]
Yes, it should be 64. The code works for the main use case we currently have, but I will prepare a PR with the fix.

Good catch! Thank you!

**Comment by msgilligan** [comment]
Fixed in PR #3248

**Comment by msgilligan** [comment]
PR #3248 is merged.
