### ISSUE TITLE
Bitcoin Taproot address issue

### ISSUE THREAD

**Issue by ronaldoguedess** [bitcoinj/bitcoinj#3335]
I can't generate the Bitcoin Taproot address

```
val privateKey = ECKey.fromPrivate(BigInteger(privateKeyHex, 16))
val address = Address = Address.fromKey(MainNetParams.get(), privateKey, ScriptType.P2TR)
```

### **ERROR**
```
FATAL EXCEPTION: DefaultDispatcher-worker-5
     Process: org.ecoinwallet, PID: 17059
     java.lang.IllegalArgumentException: P2TR
     at org.bitcoinj.core.Address.fromKey(Address.java:89)
```

**Comment by msgilligan** [comment]
Currently bitcoinj only supports sending to P2TR addresses, not generating them from private keys. This is something we would like to implement and if you are interested in helping with this or testing pre-release versions please join us on Matrix.

See Issue #1949. Closing as duplicate.
