### ISSUE TITLE
KeyChainGroup.Builder: fromKey() and fromSeed() (still) create a `fallBackChain` when creating `P2WPKH`

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#3336]
See: [KeyChainGroup.java#L141-L151](https://github.com/bitcoinj/bitcoinj/blob/36dce3d9d52c322270192eadb7fa53f0dd7c13a5/core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java#L141-L151)

In the JavaDoc comment for both methods [it says](https://github.com/bitcoinj/bitcoinj/blob/36dce3d9d52c322270192eadb7fa53f0dd7c13a5/core/src/main/java/org/bitcoinj/wallet/KeyChainGroup.java#L128-L130):

```
In the case of P2WPKH, both a P2PKH and a P2WPKH chain are created and activated, the latter being the default
chain. This behaviour will likely be changed with bitcoinj 0.16 such that only a P2WPKH chain is created and
activated.
 ```
 
 @schildbach What do you think we should we do? (At the very least we need to update the comment.)

**Comment by schildbach** [comment]
Fixed via 7230fbf7e5d80f70cc1bb3957475bae24a36fb8a.

I think what we need first is versioned mnenonic seeds, such that version 0 will create chains for P2PKH and later (the current behaviour), version 1 will create chains for P2WPKH and later, and version 2 will likely create chains for P2TR and later.
