### ISSUE TITLE
When will Bitcoinj support spending p2tr input?

### ISSUE THREAD

**Issue by apufvqsp** [bitcoinj/bitcoinj#3341]
When will Bitcoinj support spending p2tr type address input?

I searched on github and google for two days and found that other languages such as Golang, Javascript, and Python already support the input of p2tr type addresses, but bitcoinj still does not have related functions.

I'm feeling a bit down.

**Comment by schildbach** [comment]
Can you join our Matrix chat for discussion about this? Thanks.

**Comment by msgilligan** [comment]
See also Issue #1949
