### ISSUE TITLE
how to connect bitcoin testnet

### ISSUE THREAD

**Issue by Wang-jiong-han** [bitcoinj/bitcoinj#3395]
I am using a Bitcoin wallet based on BitcoinJ, but the wallet cannot connect to the test network. I would like to know if someone can give me an IP address to link to

**Comment by ItoroD** [comment]
Hello, can you be a bit more specific? launching a bitcoinj wallet kit will automatically connect to an available testnet node as long as the network as been specified. See example here

https://github.com/bitcoinj/bitcoinj/blob/v0.17-alpha3/examples/src/main/java/org/bitcoinj/examples/Kit.java

**Comment by schildbach** [comment]
Closing, as the question has been answered.
