### ISSUE TITLE
Please release more frequently

### ISSUE THREAD

**Issue by daniel-b2c2** [bitcoinj/bitcoinj#3409]
You have a bouncycastle dependency (I can see from other issues you're looking to reduce your dependency on it), your last major release from what I can see was december 2022, which was 18 months ago. 

It would be good to see a patch release for every time that a dependency is updated - completely independent of functional releases.

I see the alpha releases, but many projects are setup to ignore releases that aren't considered stable.

Is this planned or? How are releases currently performed - part of CI or manually?

**Comment by msgilligan** [comment]
* Your project can upgrade Bouncy Castle to a newer (minor release) without upgrading your bitcoinj
* The 0.17 release is fairly stable at this point and a beta is expected soon. I do recommend updating to it asap.
* Feel free to submit a PR to the 0.16 branch with an updated Bouncy Castle (or other dependency) -- this will make it possible to run CI tests against the updated dependency.
* At this point, I can't promise that we'll make releases each time a dependency is updated
* The current release process is at least partly manual.

**Comment by msgilligan** [comment]
@daniel-b2c2 We are in the process of releasing version 0.16.3 which has an updated Bouncy Castle dependency.

**Comment by schildbach** [comment]
Bitcoinj 0.16.3 has BouncyCastle 1.73:
https://bitcoinj.org/release-notes#version-0163

I recommend to update your project to 0.16.3 as soon as you can.

Issues like this are best discussed in our Matrix rooms. I'm closing this.
https://bitcoinj.org/#community
