### ISSUE TITLE
getting ArrayIndexOutOfBoundsException while trying to parse from raw transaction

### ISSUE THREAD

**Issue by manzicek** [bitcoinj/bitcoinj#3439]
Hi,

I have encountered the above mentioned exception while trying to parse from raw. I have written this simple test which replicates the error:

```
@Test
    void test() {
       var transactionBytes HexFormat.of().parseHex("0100000000010a000000000000001976a91471169e4eb2e2087a34200d98e2b9c66004735fbb88acffffffff");
        var t = new Transaction(MainNetParams.get(), transactionBytes);
        Assertions.assertNotNull(t);
}
```

When you run this you get **java.lang.ArrayIndexOutOfBoundsException: Index 44 out of bounds for length 44**.

BitcoinJ version being used is `0.16.2`.

What is the issue here? The raw transaction used seems ok.

**Comment by schildbach** [comment]
A quick check at https://www.blockchain.com/explorer/assets/btc/decode-transaction yields:

> "error": "Trying to access beyond buffer length"

Why do you believe the transaction is ok?

**Comment by schildbach** [comment]
Bitcoinj is for Bitcoin only. I suspect BSV has changed something about the format when they forked.

**Comment by manzicek** [comment]
Decoded by hand, could there also be a problem that it has no inputs?

```
01000000 - Version 1
00 - 0 inputs
01 - 1 output
0a00000000000000 - Value (10 sat)
19 - Script length (25 bytes)
76a91471169e4eb2e2087a34200d98e2b9c66004735fbb88ac - the p2pkh script
00000000 - sequence no.
```

**Comment by schildbach** [comment]
Transactions without inputs _do_ exist, in the form of coinbase.

I'll close this, as this is not an issue in bitcoinj. Feel free to discuss in our [Matrix rooms](https://matrix.to/#/#bitcoinj:matrix.org), or in any forum dedicated to BSV.
