### ISSUE TITLE
Add more clear (and more stern) warning about ListenableFuture being removed.

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#3480]
In the 0.17 release we have replaced all instances of `ListenableFuture` in the API with `ListenableCompletableFuture`.  `ListenableCompletableFuture` is meant as a temporary measure to allow migration to `CompletableFuture` before the 0.18 release. And for a handful of technical and practical reasons, there are no deprecation tags indicating it will be going away.

We should add a very clear warning to the 0.17 release notes **and JavaDoc** that this is 100% going to happen in the 0.18 release.

**Comment by schildbach** [comment]
Do we already have warnings in place in JavaDocs and comments?

**Comment by msgilligan** [comment]
> Do we already have warnings in place in JavaDocs and comments?

I'll make sure there are.

**Comment by msgilligan** [comment]
PR #3508 adds @Deprecations and warnings to the Java source.

**Comment by schildbach** [comment]
The v0.17-rc1 pre-release notes come with a warning. We can reword it for the final release notes if desired, but I'm now closing this reminder.
