### ISSUE TITLE
Support Bitcoin Taproot (Generating a Taproot Address)

### ISSUE THREAD

**Issue by Good-rgb** [bitcoinj/bitcoinj#3509]
I will generate the Taproot Address as follows
SegwitAddress.fromProgram(MainNetParams.get(),1 ,“Public Key”）
But I don't know how to generate the correct 32-bit public key 
Can someone tell me

**Comment by schildbach** [comment]
Our wallet implementation doesn't support Taproot at the moment.

If you join our Matrix chat (see https://bitcoinj.org/#community) and describe your usecase, we could help you with finding a solution.
