### ISSUE TITLE
Script creationTime behavior may have changed. We need to verify behavior.

### ISSUE THREAD

**Issue by msgilligan** [bitcoinj/bitcoinj#3523]
In our refactoring, we may have changed the behavior of `Script` with respect to unknown creation times.

`@Nullable private final Instant creationTime` is never `null` despite the `@Nullable` annotation and the `public Optional<Instant> creationTime()` getter.

There are factory methods and deprecated constructors that set `creationTime` to `TimeUtils.currentTime()`. Is there a use-case where we need to represent the creation time as "unknown"?

In a private conversation, Andreas said:

> I'd assume that if a script doesn't associate a key then the creation time is unknown. Or if the creation time of an associated key is unknown itself. If I understand the field comment correctly, it's always about keys not the script itself

This recent PR is also relevant:

https://github.com/bitcoinj/bitcoinj/pull/3513

We should verify what the past behavior was and what the correct behavior should be and update the code and JavaDoc to match.

**Comment by schildbach** [comment]
I looked at `release-0.16` and the behaviour is inconsistent:

- The constructor `public Script(byte[] programBytes, long creationTimeSeconds)` uses the supplied creation time.
- The constructor `public Script(byte[] programBytes)` initialized it to zero.
- The package-private constructor `Script(List<ScriptChunk> chunks)` is used only by `ScriptBuilder.build()` and inititalizes the creation time to the current time.

I'm not sure if we should try to preserve this behaviour.

**Comment by schildbach** [comment]
`ScriptBuilder` has two related JavaDocs:

> If this is not set, the current time is used by the builder.

This was added in 838d14d027b63381ac0317fa51900a3f9035ad8d, after 0.16.

> The creation time will be the current time.

This was added in 15ee38aae08372d8524d2fd1b916ac3aca88d190, also after 0.16.

**Comment by schildbach** [comment]
Investigated more into the usages of `Script.setCreationTimeSeconds()`, and it's only used for watching addresses like I suspected.

**Comment by schildbach** [comment]
To sum it up, I think we should make clear that for generic case, scripts don't have a creation time and thus it's `null` not  current time. Only if a script is a scriptPubKey, it could be set to the creation date of the public/private keypair and thus the corresponding address.

**Comment by schildbach** [comment]
Furthermore, we should perhaps think about removing `@Deprecated public Script(byte[] program)` again?

**Comment by msgilligan** [comment]
> Investigated more into the usages of `Script.setCreationTimeSeconds()`, and it's only used for watching addresses like I suspected.

If that's the only place it is used, maybe we should make a wrapper class (in the wallet package/module) for watch-only wallets that adds creation time and move to deprecate it in `Script` and `ScriptBuilder`?

**Comment by msgilligan** [comment]
> Furthermore, we should perhaps think about removing `@Deprecated public Script(byte[] program)` again?

I'm not sure what you mean here. We've already removed it on `master`. Are you suggesting we add it back?

**Comment by schildbach** [comment]
> > Investigated more into the usages of `Script.setCreationTimeSeconds()`, and it's only used for watching addresses like I suspected.
> 
> If that's the only place it is used, maybe we should make a wrapper class (in the wallet package/module) for watch-only wallets that adds creation time and move to deprecate it in `Script` and `ScriptBuilder`?

Well, it's our own only use. It's public API though, so it could be used by others. However I suspect nobody uses it.

So I agree we should try to remove it from the `Script` class, and a wrapper (which would not go to base, rather stay close to wallet) seems reasonable. I'd prefer to target this for 0.18 though, if you agree. For 0.17 I think the documentation I added via #3535 is enough. Any thoughts?

**Comment by schildbach** [comment]
> > Furthermore, we should perhaps think about removing `@Deprecated public Script(byte[] program)` again?
> 
> I'm not sure what you mean here. We've already removed it on `master`. Are you suggesting we add it back?

I was thinking about 0.17, as that is what this issue is targetting. But actually I didn't think it through. After merging #3535, the changed behaviour would be with ScriptBuidler, not the public Script constructors. So just ignore my quoted comment.

**Comment by schildbach** [comment]
I believe this is resolved. We now have [more (accurate) documentation](https://github.com/bitcoinj/bitcoinj/pull/3541) and a [PR to change behaviour a bit](https://github.com/bitcoinj/bitcoinj/pull/3535).
