### ISSUE TITLE
Upgrade to Guava 17 and start using BaseEncodings/Closeables

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#551]
Originally reported on Google Code with ID 185

```
It will happily decode ANY string and produce garbage! Also there's no need for it,
BigInteger can do this itself:

new BigInteger(str, 16);


```

Reported by `hearn@google.com` on 2012-05-02 15:40:06

**Comment by Polve** [comment]
Why not version 18?

Since guava gets pulled in by a project using bitcoinj, it would be nice to have the latest release, if possible.

**Comment by mikehearn** [comment]
You're looking at a bug that worked on a year ago. Guava 18 didn't exist back then, I think.

**Comment by Polve** [comment]
Ok.
Should I open an issue to just upgrade the guava version then?
(it should be backward compatible)

**Comment by msgilligan** [comment]
@schildbach What is the status of this issue? Can it be closed? At the very least we should remove the reference to Guava 17 in the title as we're currently on Guava 29.

**Comment by msgilligan** [comment]
I'm closing this issue as it may have already been implemented and we are migrating away from Guava. See Issue #2000.
