### ISSUE TITLE
Prepare for maven-release-plugin

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#574]
Originally reported on Google Code with ID 208

```
I experimented a bit with automation of the release process. If we want to use the maven-release-plugin,
we'd need the following changes to our base POM:

1) SCM configuration

add
<connection>scm:git:https://code.google.com/p/bitcoinj/</connection>
to the existing <scm> tag.

You should be able to validate this with 
mvn scm:validate

2) maven-release-plugin configuration

add
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-release-plugin</artifactId>
    <version>2.3.1</version>
    <configuration>
        <pushChanges>false</pushChanges>
    </configuration>
</plugin>
to the existing <build><plugins> tag.

This allows you to prepare a release with
mvn release:prepare
and perform a release with
mvn release:perform

Note that I intentionally disabled automatic push, because I think pushing should ultimately
stay in the hand of the developer. Thus, don't forget to push manually when you are
finished with the release.

```

Reported by `andreas.schildbach` on 2012-06-13 14:15:50

**Comment by cedricwalter** [comment]
Bisq has a fork for now of bitcoinj, and we are in the process of pushing bitcoinj in our own namespace io.bisq.bitcoinj following http://www.debonair.io/post/maven-cd/, we have our own PR https://github.com/bitsquare/bitcoinj/pull/9     maybe you are interested to do something similar? hence my comment in here

Concerning the maven release plugin, i recommend you to not use it, instead keep the pom version to anything-snapshot and use my plugin https://github.com/cedricwalter/git-branch-renamer-maven-plugin
Why you would ask? read https://www.waltercedric.com/index.php/development/2212-maven-release-plugin-with-git

Moreover we also need deterministic build for Bisq (previously Bitsquare), so i may implement some of your comments.

**Comment by msgilligan** [comment]
@schildbach Now that we are using Gradle I think we can close this issue.
