### ISSUE TITLE
API Cleanup:   Rename FooEventListener top level classes -> Foo.Listener

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#614]
Originally reported on Google Code with ID 248
```
Event listener interfaces are conceptually a part of their objects interface, so it
makes sense for them to be subclasses/subinterfaces.
```

Reported by `hearn@google.com` on 2012-08-30 21:27:21

**Comment by schildbach** [comment]
This would have been the structure I had in mind. Interesting to learn that you had the same idea in mind, @mikehearn.

**Comment by schildbach** [comment]
Guess this is out of date.
