### ISSUE TITLE
Using Maven

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#659]
Originally reported on Google Code with ID 293

```
Hello,

I am trying to add bitcoinj to my project as a dependency but it seems that the instructions
here http://code.google.com/p/bitcoinj/wiki/UsingMaven are no longer valid.

If you simply try to visit http://nexus.bitcoinj.org/content/repositories/releases
you will be getting an Internal Server error.

Can someone shed some light on this please?
```

Reported by `arekanderu` on 2013-01-25 12:51:51

**Comment by skillachie** [comment]
Ran into similar issue today and have been trying to resolve by checking my dns servers and other troubleshooting  remedies. Currently there is no dns entry for  the nexus subdomain

```
** server can't find nexus.bitcoinj.org: NXDOMAIN
```

Was trying to retrieve the 0.13-SNAPSHOT https://github.com/bitcoinj/wallet-template
