### ISSUE TITLE
Wallet contained duplicate transaction

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#735]
Originally reported on Google Code with ID 369
```
I got this exception on bitcoinj-0.7.2.

Exception in thread "main" java.lang.IllegalStateException: Wallet contained duplicate
transaction 4bed2b83d79877a5e33c91f8522e61b1152ab1336bbe4975635c032a4609bd57
	at com.google.common.base.Preconditions.checkState(Preconditions.java:172)
	at com.google.bitcoin.store.WalletProtobufSerializer.readTransaction(WalletProtobufSerializer.java:350)
	at com.google.bitcoin.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:280)
	at com.google.bitcoin.core.Wallet.loadFromFileStream(Wallet.java:685)
	at com.google.bitcoin.core.Wallet.loadFromFile(Wallet.java:612)

My test wallet is attached to issue
```

Reported by `pshmarev` on 2013-03-26 12:37:32

<hr>
 * *Attachment: [wallet](https://storage.googleapis.com/google-code-attachments/bitcoinj/issue-369/comment-0/wallet)*

**Comment by posita** [comment]
Using `HEAD` (fc9ae41883727dd3cb4103feb9dc37b3274ce56f):

```java
./wallet-tool reset --force --wallet=.../com.google.bitcoin.params.MainNetParams.wallet
Failed to load wallet '.../com.google.bitcoin.params.MainNetParams.wallet': Wallet contained duplicate transaction 9daa66814ba6087853b20caa177e16ad49b7bf200e09d35c1421287191abcfbb
org.bitcoinj.store.UnreadableWalletException: Wallet contained duplicate transaction 9daa66814ba6087853b20caa177e16ad49b7bf200e09d35c1421287191abcfbb
        at org.bitcoinj.store.WalletProtobufSerializer.readTransaction(WalletProtobufSerializer.java:621)
        at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:455)
        at org.bitcoinj.store.WalletProtobufSerializer.readWallet(WalletProtobufSerializer.java:398)
        at org.bitcoinj.tools.WalletTool.main(WalletTool.java:318)
```

If one can't even force a reset on the wallet with `wallet-tool`, how is one supposed to handle or correct this?

**Comment by mikehearn** [comment]
You're replying to a bug filed in 2013. I haven't seen any reports of that error for years. How did you get a wallet into that state? You will need to disable the sanity checks and repair it manually to fix things (can be as simple as loading the wallet without loading any transactions and replaying it)

**Comment by posita** [comment]
> You will need to **disable the sanity checks** and repair it manually to fix things (can be as simple as **loading the wallet without loading any transactions** and replaying it)

Isn't this precisely what `wallet-tool --force reset` is supposed to allow. Maybe I've misunderstood?

**Comment by posita** [comment]
> How did you get a wallet into that state?

The wallet was created recently using `v0.11.3`. My use of `wallet-tool` above was built from `HEAD`. Unfortunately I don't have (m)any other details. :disappointed:

**Comment by posita** [comment]
```
% ./wallet-tool --help
 WalletTool: print and manipulate wallets

 Usage: wallet-tool --flags action-name
        wallet-tool action-name --flags

 >>> ACTIONS
...
   reset                Deletes all transactions from the wallet, for if you want to replay the chain.
...

 >>> GENERAL OPTIONS
...
   --force              Overrides any safety checks on the requested action.
...
```

**Comment by posita** [comment]
Ah, I see. `--force` [only applies to wallet creation](https://github.com/bitcoinj/bitcoinj/blob/fc9ae41883727dd3cb4103feb9dc37b3274ce56f/tools/src/main/java/org/bitcoinj/tools/WalletTool.java#L890). :confounded:

**Comment by mikehearn** [comment]
Reset isn't intended to load corrupted wallets. 0.11.3 is ancient, the latest release is 0.13.2

It's easy to hack around this though. Just modify the code in WalletProtobufSerializer to skip loading the transactions.

**Comment by posita** [comment]
> It's easy to hack around this though. Just modify the code in WalletProtobufSerializer to skip loading the transactions.

It seems to me this path should be available via the library itself (rather than requiring users/developers to copy-paste-modify `WalletProtobufSerializer.readWallet`. I've filed issue #1078 and submitted PR #1079 to do just that.

That allows for a *work-around* for this issue, but doesn't fix how wallets get into the state described in this issue in the first place. Because the wallet in which I observed the problem was created with "ancient" `v0.11.3`, and because I (unfortunately) don't have more insight into how to reproduce the problem, I'm afraid I won't be of much more help in this thread. :disappointed:

**Comment by mikehearn** [comment]
I agree that for libraries in a mature area like an HTTP stack a year old release wouldn't be considered ancient, but bitcoinj is sadly not so straightforward. It changes constantly and bugs are resolved all the time. Between 0.11.3 and current master there were over a thousand commits. It's quite probable that wallets just don't get into this state anymore. Anyway, thanks for the PR, looks like Andreas is reviewing it.

**Comment by posita** [comment]
FWIW, its apparent that there have been a large number of significant changes since `v0.11.3`. Closing this is probably the right thing to do for housekeeping purposes. It can always be reopened if it is observed in more recent version.
