### ISSUE TITLE
Hammering on DNS seed

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#924]
Originally reported on Google Code with ID 558
```
Bitcoinj (master) still hammers on the DNS seed if not available. See attached log.

```

Reported by `andreas.schildbach` on 2014-05-15 09:57:29

<hr>
 * *Attachment: [logcat.txt](https://storage.googleapis.com/google-code-attachments/bitcoinj/issue-558/comment-0/logcat.txt)*

**Comment by schildbach** [comment]
Likely fixed by cfb942a7fa99a017aefb0eef023ae0573e3e6210.
