### ISSUE TITLE
Zero fee despite feePerKb != 0

### ISSUE THREAD

**Issue by mikehearn** [bitcoinj/bitcoinj#945]
Originally reported on Google Code with ID 579

```
On bitcoinj 0.12, I've completed a transaction on mainnet using

sendRequest.feePerKb = Coin.valueOf(1000);
sendRequest.ensureMinRequiredFee = false;

and (I think)

sendRequest.emptyWallet = true;

It came up with a fee of 0. I think it's wrong, I had expected 0.01 mBTC (the tx is
smaller than 1 kB).

See attached log.

```

Reported by `andreas.schildbach` on 2014-10-08 09:51:32

<hr>
- _Attachment: [wallet.2014-10-07.1007902125.log](https://storage.googleapis.com/google-code-attachments/bitcoinj/issue-579/comment-0/wallet.2014-10-07.1007902125.log)_

**Comment by schildbach** [comment]
This is fixed in bitcoinj 0.14.
