### ISSUE TITLE
Support for constructing unsigned transactions

### ISSUE THREAD

**Issue by bitsim-chris** [bitcoinj/bitcoinj#995]
I have a need to construct unsigned transactions from UTXO data, and I've found this can't be done with BitcoinJ.  To get around this, I changed `Transaction.setHash()` from private to public, and in my code I'm padding out the `List<TransactionOutput>` with "spacer" transactions in order to set an output's index:

```
      Transaction t;
      TransactionOutput spacer, to;

      for (Object o : utxoData) {
        JsonObject jo = (JsonObject)o;
        t = new Transaction(params);

        // pad out the outputs list with spacers to set the vout
        spacer = new TransactionOutput(params, null, Coin.valueOf(0), destAddr);
        int vout = jo.getInteger("vout");
        for (int a = 0; a < vout; a++)
          t.addOutput(spacer);

        ....

        // add the output
        to = new TransactionOutput(params, t, c, destAddr);
        t.addOutput(to);

        // set the hash manually
        t.setHash(new Sha256Hash(   .... txid....  );
```
Currently in BitcoinJ, `TransactionOutput.getIndex()` finds the output's vout by querying its position in the Transaction's output list.  I have some changes to this mechanism planned so I don't have to pad out the list with dummy outputs, as I've done above.  This involves adding `index` and `indexMode` instance variables to TransactionOutput, adding a `setIndex()` method, and altering `getIndex()` to either return the local `index` or use the current mechanism depending on `indexMode`.

I'd like to get some discussion going before submitting a pull request.

**Comment by mikehearn** [comment]
Sure it's possible.

What you need is the out*point* not out*put*. An outpoint is a pointer to an output: it's just a (txhash, index) pair.

Once you have an outpoint, you can add unsigned inputs that reference it quite easily:

TransactionOutPoint outpoint = new TransactionOutPoint(params, index, txhash);
tx.addInput(new TransactionInput(params, null /*parent*/, new byte[]{}, outpoint));

That creates the input with an empty script. Later on you can sign it in the usual manner.

**Comment by bitsim-chris** [comment]
Thanks, I will look into this.
